# Generated by Django 5.0 on 2026-01-20 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_orders', '0010_customerordercommissionrecipient_employeecommission'),
        ('orders', '0015_order_offer_document'),
        ('users', '0033_user_can_write_meetings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('event_type', models.CharField(choices=[('vs_meeting', 'VS-Meeting'), ('doctor_visit', 'Arztbesuch'), ('business_trip', 'Dienstreiseplanung'), ('birthday', 'Geburtstag'), ('inhouse_demo', 'In-House Demo'), ('remote_demo', 'Remote Demo'), ('remote_session', 'Remote Session'), ('event', 'Veranstaltung'), ('other', 'Sonstige'), ('vacation', 'Urlaub'), ('sick_leave', 'Krankheit'), ('order_delivery', 'Liefertermin Bestellung'), ('customer_order_delivery', 'Liefertermin Kundenauftrag')], default='other', max_length=30, verbose_name='Termintyp')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('is_all_day', models.BooleanField(default=True, verbose_name='Ganztägig')),
                ('is_system_generated', models.BooleanField(default=False, verbose_name='Systemgeneriert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='customer_orders.customerorder', verbose_name='Kundenauftrag')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='orders.order', verbose_name='Bestellung')),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='users.vacationrequest', verbose_name='Urlaubsantrag')),
            ],
            options={
                'verbose_name': 'Kalendereintrag',
                'verbose_name_plural': 'Kalendereinträge',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_all', models.BooleanField(default=False, verbose_name='Alle benachrichtigen')),
                ('minutes_before', models.IntegerField(choices=[(0, 'Zum Zeitpunkt'), (5, '5 Minuten vorher'), (15, '15 Minuten vorher'), (30, '30 Minuten vorher'), (60, '1 Stunde vorher'), (120, '2 Stunden vorher'), (1440, '1 Tag vorher'), (2880, '2 Tage vorher'), (10080, '1 Woche vorher')], default=60, verbose_name='Erinnerung')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gesendet')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='company_calendar.calendarevent', verbose_name='Termin')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'Terminerinnerung',
                'verbose_name_plural': 'Terminerinnerungen',
                'ordering': ['event', 'minutes_before'],
            },
        ),
    ]
