# Generated by Django 5.0 on 2026-01-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='company_calendar.calendarevent', verbose_name='Ursprünglicher Termin'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Wiederholen bis'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Keine Wiederholung'), ('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default='none', max_length=20, verbose_name='Wiederholung'),
        ),
    ]
