# Generated by Django 5.0 on 2026-01-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_field', models.CharField(help_text='Name des Statusfelds im Model (z.B. "status")', max_length=100, verbose_name='Statusfeld')),
                ('trigger_status', models.CharField(help_text='Der Statuswert, bei dem die Benachrichtigung ausgelöst wird', max_length=100, verbose_name='Auslösender Status')),
                ('name', models.CharField(help_text='Beschreibende Bezeichnung für diese Mitteilungsaufgabe', max_length=200, verbose_name='Bezeichnung')),
                ('message_template', models.TextField(blank=True, help_text='Optionale Vorlage für die Nachricht. Variablen: {object}, {old_status}, {new_status}, {changed_by}', verbose_name='Nachrichtenvorlage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Das Modul, auf dessen Statusänderungen reagiert werden soll', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modul')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Mitteilungsaufgabe',
                'verbose_name_plural': 'Mitteilungsaufgaben',
                'ordering': ['content_type__app_label', 'content_type__model', 'trigger_status'],
                'unique_together': {('content_type', 'status_field', 'trigger_status', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NotificationTaskRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_creator_only', models.BooleanField(default=False, help_text='Wenn aktiv, wird nur der Ersteller des Objekts benachrichtigt', verbose_name='Nur Ersteller benachrichtigen')),
                ('notify_assigned_only', models.BooleanField(default=False, help_text='Wenn aktiv, wird nur der zugewiesene Bearbeiter benachrichtigt', verbose_name='Nur zugewiesener Bearbeiter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notificationtask', verbose_name='Mitteilungsaufgabe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_task_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'Mitteilungsempfänger',
                'verbose_name_plural': 'Mitteilungsempfänger',
                'unique_together': {('task', 'user')},
            },
        ),
    ]
