# Generated by Django 5.0 on 2026-01-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtaskrecipient',
            name='notify_hr_approvers',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden alle Benutzer mit HR-Schreibrechten benachrichtigt (für Urlaubsanträge)', verbose_name='Alle HR-Genehmiger benachrichtigen'),
        ),
    ]
