# Generated by Django 5.0 on 2025-12-20 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0013_supplier_customer_number_supplier_payment_terms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, help_text='Format: B-001-10/25', max_length=20, null=True, unique=True, verbose_name='Bestellnummer')),
                ('order_type', models.CharField(choices=[('online', 'Online-Bestellung'), ('direct', 'Direkte Bestellung'), ('customer_order', 'Kundenauftrags-Bestellung')], default='online', max_length=20, verbose_name='Bestelltyp')),
                ('status', models.CharField(choices=[('angelegt', 'Angelegt'), ('bestellt', 'Bestellt'), ('bestaetigt', 'Bestätigt'), ('geliefert', 'Geliefert'), ('bezahlt', 'Bezahlt'), ('zahlung_on_hold', 'Zahlung on hold')], default='angelegt', max_length=20, verbose_name='Status')),
                ('order_date', models.DateField(blank=True, help_text='Datum an dem bestellt wurde', null=True, verbose_name='Bestelldatum')),
                ('delivery_date', models.DateField(blank=True, help_text='Tatsächliches oder geplantes Lieferdatum', null=True, verbose_name='Lieferdatum')),
                ('payment_date', models.DateField(blank=True, help_text='Datum der Zahlung', null=True, verbose_name='Zahlungsdatum')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen zur Bestellung', verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(help_text='Artikelnummer des Lieferanten', max_length=100, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=500, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('list_price', models.DecimalField(decimal_places=2, help_text='Preis pro Einheit', max_digits=10, verbose_name='Listenpreis')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabatt %')),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Preis pro Einheit nach Rabatt', max_digits=10, verbose_name='Endpreis')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('position', models.PositiveIntegerField(default=0, help_text='Reihenfolge in der Bestellung', verbose_name='Position')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.asset', verbose_name='Asset')),
                ('material_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.materialsupply', verbose_name='Material Supply')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Bestellung')),
                ('trading_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.tradingproduct', verbose_name='Trading Product')),
            ],
            options={
                'verbose_name': 'Bestellposition',
                'verbose_name_plural': 'Bestellpositionen',
                'ordering': ['order', 'position'],
            },
        ),
    ]
