# Generated by Django 5.0 on 2025-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_date',
            field=models.DateField(blank=True, help_text='Datum der Auftragsbestätigung durch den Lieferanten', null=True, verbose_name='Auftragsbestätigungsdatum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('angelegt', 'Angelegt'), ('bestellt', 'Bestellt'), ('bestaetigt', 'Bestätigt'), ('geliefert', 'Geliefert'), ('bezahlt', 'Bezahlt'), ('zahlung_on_hold', 'Zahlung on hold'), ('storniert', 'Storniert')], default='angelegt', max_length=20, verbose_name='Status'),
        ),
    ]
