# Generated by Django 5.0 on 2025-12-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_confirmation_date_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_order_number',
            field=models.CharField(blank=True, help_text='Referenz zum Kundenauftrag', max_length=100, verbose_name='Kundenauftragsnummer'),
        ),
    ]
