# Generated by Django 5.0 on 2025-12-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_text',
            field=models.TextField(blank=True, help_text='Text der im Bestelldokument erscheint', verbose_name='Benutzerdefinierter Text'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_reference',
            field=models.CharField(blank=True, help_text='Referenz zum zugehörigen Angebot', max_length=100, verbose_name='Angebotsreferenz'),
        ),
    ]
