# Generated by Django 5.0 on 2025-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_custom_text_order_offer_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_document',
            field=models.FileField(blank=True, help_text='Hochgeladenes Bestelldokument (z.B. PDF von Online-Bestellung)', null=True, upload_to='orders/documents/%Y/%m/', verbose_name='Bestelldokument'),
        ),
    ]
