# Generated by Django 5.0 on 2025-12-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_document'),
        ('verp_settings', '0005_populate_incoterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='verp_settings.deliveryinstruction', verbose_name='Lieferanweisungen'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='verp_settings.deliveryterm', verbose_name='Lieferbedingungen (Incoterm)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='verp_settings.paymentterm', verbose_name='Zahlungsbedingungen'),
        ),
    ]
