# Generated by Django 5.0 on 2025-12-20 16:39

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_instruction_order_delivery_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_document',
            field=models.FileField(blank=True, help_text='Hochgeladenes Bestelldokument (z.B. PDF von Online-Bestellung)', null=True, upload_to=orders.models.order_document_upload_path, verbose_name='Bestelldokument'),
        ),
    ]
