# Generated by Django 5.0 on 2025-12-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online-Bestellung'), ('direct', 'Direkte Bestellung'), ('customer_order', 'Kundenauftrag')], default='online', help_text='Typ der Bestellung (z.B. Kundenauftrag)', max_length=20, verbose_name='Bestelltyp'),
        ),
    ]
