# Generated by Django 5.0 on 2025-12-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_expected_delivery_and_supplier_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Die Gesamtsumme nach Auftragsbestätigung (fixiert)', max_digits=12, null=True, verbose_name='Bestätigter Bestellpreis'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='confirmed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vom Lieferanten bestätigter Preis pro Einheit (bleibt erhalten)', max_digits=10, null=True, verbose_name='Bestätigter Positionspreis'),
        ),
    ]
