# Generated by Django 5.0 on 2025-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_confirmed_total_orderitem_confirmed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='controlling_checked',
            field=models.BooleanField(default=False, help_text='Markiert, ob Controlling die Position geprüft/abgenommen hat', verbose_name='Controlling geprüft'),
        ),
    ]
