# Generated by Django 5.0 on 2025-12-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_controlling_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='asset',
        ),
    ]
