# Generated by Django 5.0 on 2025-12-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderitem_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='incoming_recorded',
            field=models.BooleanField(default=False, help_text='Setzt an, dass für diese Bestellung bereits ein Wareneingang angelegt wurde', verbose_name='Wareneingang erfasst'),
        ),
    ]
