# Generated by Django 5.0 on 2026-01-06 07:45

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_incoming_recorded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_document',
            field=models.FileField(blank=True, help_text='Hochgeladenes Angebotsdokument vom Lieferanten', null=True, upload_to=orders.models.order_document_upload_path, verbose_name='Angebotsdokument'),
        ),
    ]
