# Generated by Django 5.0 on 2025-12-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customersystem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, editable=False, help_text='Automatisch generierte Projektnummer (P-00001)', max_length=10, null=True, unique=True, verbose_name='Projektnummer')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Projektname')),
                ('description', models.TextField(blank=True, verbose_name='Projektbeschreibung')),
                ('status', models.CharField(choices=[('NEU', 'Neu'), ('IN_BEARBEITUNG', 'In Bearbeitung'), ('ANGEBOT_ERSTELLT', 'Angebot erstellt'), ('DEMO_GEPLANT', 'Demo geplant'), ('AUSSCHREIBUNG', 'Ausschreibung'), ('AUFTRAG_ERTEILT', 'Auftrag erteilt'), ('IN_FERTIGUNG', 'In Fertigung'), ('LIEFERUNG', 'Lieferung'), ('INSTALLATION', 'Installation'), ('ABGESCHLOSSEN', 'Abgeschlossen'), ('STORNIERT', 'Storniert')], default='NEU', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customers.customer', verbose_name='Kunde')),
                ('systems', models.ManyToManyField(blank=True, related_name='projects', to='customers.customersystem', verbose_name='Systeme')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-created_at'],
            },
        ),
    ]
