# Generated by Django 5.0 on 2025-12-31 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='systems.system', verbose_name='Verknüpftes System'),
        ),
    ]
