# Generated by Django 5.0 on 2026-01-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_linked_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forecast_probability',
            field=models.IntegerField(blank=True, help_text='Wahrscheinlichkeit des Auftragseingangs (0-100%)', null=True, verbose_name='Wahrscheinlichkeit (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='forecast_quarter',
            field=models.CharField(blank=True, help_text='z.B. Q1 2026', max_length=10, verbose_name='Forecast Quartal'),
        ),
        migrations.AddField(
            model_name='project',
            name='forecast_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Erwarteter Auftragsumsatz', max_digits=12, null=True, verbose_name='Erwarteter Umsatz'),
        ),
    ]
