# Generated by Django 5.0 on 2026-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_forecast_probability_and_more'),
        ('systems', '0004_remove_system_warranty_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='linked_system',
        ),
        migrations.AlterField(
            model_name='project',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='projects', to='systems.system', verbose_name='Systeme'),
        ),
    ]
