# Generated by Django 5.0 on 2026-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_change_systems_to_systems_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='forecast_quarter',
        ),
        migrations.AddField(
            model_name='project',
            name='forecast_date',
            field=models.DateField(blank=True, help_text='Voraussichtliches Datum des Auftragseingangs', null=True, verbose_name='Erwartetes Auftragsdatum'),
        ),
    ]
