# Generated by Django 5.0 on 2026-01-14 09:48

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0010_customerordercommissionrecipient_employeecommission'),
        ('manufacturing', '0005_productionorder_observers'),
        ('orders', '0015_order_offer_document'),
        ('projects', '0005_change_forecast_quarter_to_date'),
        ('users', '0031_extended_project_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tatsächliches Lieferdatum'),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tatsächliches Installationsdatum'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Demo-Datum von'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Demo-Datum bis'),
        ),
        migrations.AddField(
            model_name='project',
            name='linked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='customer_orders.customerorder', verbose_name='Verknüpfter Auftrag'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geplantes Lieferdatum'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geplantes Installationsdatum'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to='users.employee', verbose_name='Zuständiger Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='project',
            name='tender_award_deadline',
            field=models.DateField(blank=True, help_text='Frist für Zuschlagserteilung', null=True, verbose_name='Zuschlagsfrist'),
        ),
        migrations.AddField(
            model_name='project',
            name='tender_bidder_questions_deadline',
            field=models.DateField(blank=True, help_text='Frist für Bieterfragen', null=True, verbose_name='Ende Bieterfragen'),
        ),
        migrations.AddField(
            model_name='project',
            name='tender_submission_deadline',
            field=models.DateField(blank=True, help_text='Frist für Angebotsabgabe', null=True, verbose_name='Angebotsabgabefrist'),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projekt Kommentar',
                'verbose_name_plural': 'Projekt Kommentare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.project_document_upload_path, verbose_name='Datei')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Projekt')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_document_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Projekt-Dokument',
                'verbose_name_plural': 'Projekt-Dokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Aufgabe')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_todos', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDos',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_order_created', models.BooleanField(default=False, verbose_name='Lieferantenbestellung erstellt')),
                ('production_order_created', models.BooleanField(default=False, verbose_name='Fertigungsauftrag erstellt')),
                ('visiview_order_created', models.BooleanField(default=False, verbose_name='VisiView-Auftrag erstellt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_positions', to='customer_orders.customerorderitem', verbose_name='Auftragsposition')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_positions', to='manufacturing.productionorder', verbose_name='Fertigungsauftrag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to='projects.project', verbose_name='Projekt')),
                ('supplier_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_positions', to='orders.order', verbose_name='Lieferantenbestellung')),
            ],
            options={
                'verbose_name': 'Projekt-Auftragsposition',
                'verbose_name_plural': 'Projekt-Auftragspositionen',
                'unique_together': {('project', 'order_item')},
            },
        ),
    ]
