# Generated by Django 5.0 on 2025-12-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_add_customer_salutation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMACase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True, verbose_name='RMA-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel/Betreff')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('waiting_parts', 'Warte auf Teile'), ('repaired', 'Repariert'), ('not_repairable', 'Nicht reparierbar'), ('returned', 'Zurückgesendet'), ('closed', 'Abgeschlossen')], default='open', max_length=20, verbose_name='Status')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='Kundenname')),
                ('customer_contact', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Produktbezeichnung')),
                ('product_serial', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('product_purchase_date', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('warranty_status', models.CharField(choices=[('unknown', 'Unbekannt'), ('in_warranty', 'In Garantie'), ('out_of_warranty', 'Außerhalb Garantie'), ('extended_warranty', 'Erweiterte Garantie')], default='unknown', max_length=20, verbose_name='Garantiestatus')),
                ('fault_description', models.TextField(blank=True, verbose_name='Fehlerbeschreibung vom Kunden')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Eingangsdatum')),
                ('received_by', models.CharField(blank=True, max_length=200, verbose_name='Angenommen von')),
                ('received_condition', models.CharField(blank=True, max_length=20, verbose_name='Zustand bei Eingang')),
                ('tracking_inbound', models.CharField(blank=True, max_length=100, verbose_name='Sendungsverfolgung Eingang')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='Versanddatum')),
                ('shipped_by', models.CharField(blank=True, max_length=200, verbose_name='Versandt von')),
                ('tracking_outbound', models.CharField(blank=True, max_length=100, verbose_name='Sendungsverfolgung Ausgang')),
                ('shipping_notes', models.TextField(blank=True, verbose_name='Versandnotizen')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Geschätzte Kosten')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tatsächliche Gesamtkosten')),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Materialkosten')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Arbeitskosten')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Versandkosten')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gesamtkosten (berechnet)')),
                ('quote_sent', models.BooleanField(default=False, verbose_name='KV gesendet')),
                ('quote_accepted', models.BooleanField(default=False, verbose_name='KV akzeptiert')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnose / Fehleranalyse')),
                ('repair_actions', models.TextField(blank=True, verbose_name='Durchgeführte Maßnahmen')),
                ('parts_used', models.TextField(blank=True, verbose_name='Verwendete Ersatzteile')),
                ('repair_date', models.DateField(blank=True, null=True, verbose_name='Reparaturdatum')),
                ('repaired_by', models.CharField(blank=True, max_length=200, verbose_name='Repariert von')),
                ('test_results', models.TextField(blank=True, verbose_name='Testergebnisse')),
                ('final_notes', models.TextField(blank=True, verbose_name='Abschlussnotizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rma_cases', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rma_cases', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_cases', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'RMA-Fall',
                'verbose_name_plural': 'RMA-Fälle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True, verbose_name='Ticket-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('IN_PROGRESS', 'In Bearbeitung'), ('WAITING', 'Wartend'), ('RESOLVED', 'Gelöst'), ('CLOSED', 'Geschlossen')], default='OPEN', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'Niedrig'), ('MEDIUM', 'Mittel'), ('HIGH', 'Hoch'), ('CRITICAL', 'Kritisch')], default='MEDIUM', max_length=20, verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Service Ticket',
                'verbose_name_plural': 'Service Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format VSS-00001', max_length=10, null=True, unique=True, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Kurzbeschreibung (Deutsch)')),
                ('short_description_en', models.CharField(blank=True, max_length=500, verbose_name='Kurzbeschreibung (Englisch)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (Deutsch)')),
                ('description_en', models.TextField(blank=True, help_text='English description for international quotations', verbose_name='Beschreibung (Englisch)')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsservice_products_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'VS-Service Produkt',
                'verbose_name_plural': 'VS-Service Produkte',
                'ordering': ['article_number'],
            },
        ),
        migrations.CreateModel(
            name='VSServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Kalkulierter Einkaufspreis/Kosten', max_digits=12, verbose_name='Einkaufspreis (EUR)')),
                ('sales_price', models.DecimalField(decimal_places=2, help_text='Listenpreis für Angebote', max_digits=12, verbose_name='Verkaufspreis (EUR)')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, help_text='Leer = unbegrenzt gültig', null=True, verbose_name='Gültig bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsservice_prices_created', to=settings.AUTH_USER_MODEL)),
                ('vs_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='service.vsservice', verbose_name='VS-Service')),
            ],
            options={
                'verbose_name': 'VS-Service Preis',
                'verbose_name_plural': 'VS-Service Preise',
                'ordering': ['vs_service', '-valid_from'],
            },
        ),
    ]
