# Generated by Django 5.0 on 2025-12-31 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customeraddress_address_type'),
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceticket',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Service Ticket', 'verbose_name_plural': 'Service Tickets'},
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='priority',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='billing',
            field=models.CharField(blank=True, choices=[('invoice', 'Rechnung'), ('warranty', 'Garantie'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='Abrechnung'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Kontakt-E-Mail für dieses Ticket', max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='linked_rma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tickets', to='service.rmacase', verbose_name='Verknüpfte RMA'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='linked_visiview_ticket',
            field=models.CharField(blank=True, help_text='Verknüpftes VisiView-Ticket', max_length=50, verbose_name='VisiView Ticket'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Beobachter'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='customers.customer', verbose_name='Kunde/Dealer'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('assigned', 'Zugewiesen'), ('waiting_customer', 'Warten Kunde'), ('waiting_thirdparty', 'Warten Third-Party'), ('no_solution', 'Keine Lösung'), ('resolved', 'Gelöst')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Thema/Titel'),
        ),
        migrations.CreateModel(
            name='TicketChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Geändertes Feld')),
                ('old_value', models.TextField(blank=True, verbose_name='Alter Wert')),
                ('new_value', models.TextField(blank=True, verbose_name='Neuer Wert')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_changes', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='service.serviceticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Änderung',
                'verbose_name_plural': 'Ticket Änderungen',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service.serviceticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Kommentar',
                'verbose_name_plural': 'Ticket Kommentare',
                'ordering': ['-created_at'],
            },
        ),
    ]
