# Generated by Django 5.0 on 2025-12-31 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_serviceticket_options_and_more'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='linked_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_system_tickets', to='systems.system', verbose_name='Verknüpftes System'),
        ),
    ]
