# Generated by Django 5.0 on 2026-01-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceticket_linked_system'),
        ('verp_settings', '0004_alter_productcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsservice',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsservice_products', to='verp_settings.productcategory', verbose_name='Warenkategorie'),
        ),
    ]
