# Generated by Django 5.0 on 2026-01-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_outgoing_checks'),
        ('service', '0004_vsservice_product_category'),
        ('systems', '0002_system_visiview_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_cases', to='inventory.inventoryitem', verbose_name='Warenlager-Artikel'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='linked_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_cases', to='systems.system', verbose_name='Verknüpftes System'),
        ),
    ]
