# Generated by Django 5.0 on 2026-01-04 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_rmacase_inventory_item_rmacase_linked_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleshootingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True, verbose_name='Ticket-Nummer')),
                ('title', models.CharField(max_length=300, verbose_name='Thema/Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('in_progress', 'In Bearbeitung'), ('resolved', 'Gelöst'), ('closed', 'Geschlossen')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('normal', 'Normal'), ('high', 'Hoch'), ('urgent', 'Dringend')], default='normal', max_length=20, verbose_name='Priorität')),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('application', 'Applikation'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('affected_version', models.CharField(blank=True, max_length=100, verbose_name='Betroffene Version')),
                ('root_cause', models.TextField(blank=True, help_text='Ursache des Problems', verbose_name='Root Cause')),
                ('corrective_action', models.TextField(blank=True, help_text='Korrekturmaßnahme / Lösung', verbose_name='Corrective Action')),
                ('related_tickets', models.CharField(blank=True, help_text='Kommagetrennte Ticketnummern oder IDs', max_length=500, verbose_name='Zugehörige Tickets')),
                ('files', models.TextField(blank=True, help_text='Dateinamen oder Links', verbose_name='Dateien')),
                ('last_comments', models.TextField(blank=True, verbose_name='Letzte Kommentare')),
                ('legacy_id', models.IntegerField(blank=True, help_text='Original-Ticket-Nummer aus dem alten System', null=True, unique=True, verbose_name='Legacy ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geschlossen am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_troubleshooting', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_troubleshooting', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('last_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_changed_troubleshooting', to=settings.AUTH_USER_MODEL, verbose_name='Zuletzt geändert von')),
            ],
            options={
                'verbose_name': 'Troubleshooting Ticket',
                'verbose_name_plural': 'Troubleshooting Tickets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleshooting_comments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='service.troubleshootingticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Troubleshooting Kommentar',
                'verbose_name_plural': 'Troubleshooting Kommentare',
                'ordering': ['-created_at'],
            },
        ),
    ]
