# Generated by Django 5.0 on 2026-01-04 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_ticketchangelog_field_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicketTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum der Arbeitsleistung', verbose_name='Datum')),
                ('time', models.TimeField(help_text='Uhrzeit der Arbeitsleistung', verbose_name='Uhrzeit')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Aufgewendete Zeit in Stunden (z.B. 2.5 für 2,5 Stunden)', max_digits=5, verbose_name='Aufgewendete Zeit (Stunden)')),
                ('description', models.TextField(help_text='Kurze Beschreibung der durchgeführten Arbeiten', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='service.serviceticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteinträge',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
