# Generated by Django 5.0 on 2026-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_rmacasetimeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketchangelog',
            name='field_name',
            field=models.CharField(max_length=100, verbose_name='Geändertes Feld'),
        ),
    ]
