# Generated by Django 5.0 on 2026-02-01 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0011_add_procurement_fields'),
        ('customers', '0005_customer_advertising_status_customer_description_and_more'),
        ('service', '0010_alter_ticketchangelog_field_name'),
        ('systems', '0006_add_responsible_employee_and_sales_territory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('travel', 'Reisebericht'), ('service', 'Servicebericht')], default='travel', max_length=20, verbose_name='Berichtstyp')),
                ('date', models.DateField(verbose_name='Datum')),
                ('location', models.CharField(max_length=255, verbose_name='Ort')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_reports', to='customers.customer', verbose_name='Kunde')),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_reports', to='customer_orders.customerorder', verbose_name='Verknüpfter Auftrag')),
                ('linked_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_reports', to='systems.system', verbose_name='Verknüpftes System')),
            ],
            options={
                'verbose_name': 'Reisebericht',
                'verbose_name_plural': 'Reiseberichte',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelReportMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Flexible Tabellendaten als JSON', verbose_name='Messdaten')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='service.travelreport', verbose_name='Reisebericht')),
            ],
            options={
                'verbose_name': 'Messung',
                'verbose_name_plural': 'Messungen',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='travel_reports/photos/%Y/%m/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Bildunterschrift')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('travel_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service.travelreport', verbose_name='Reisebericht')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
