# Generated by Django 5.0 on 2026-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_add_travel_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelreportmeasurement',
            name='title',
            field=models.CharField(blank=True, default='Messungen', max_length=255, verbose_name='Titel'),
        ),
    ]
