# Generated by Django 5.0 on 2026-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_add_title_to_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleshootingattachment',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Hauptfoto'),
        ),
    ]
