# Generated by Django 5.0 on 2026-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_troubleshooting_attachment_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='redmine_id',
            field=models.IntegerField(blank=True, help_text='ID des Tickets im Redmine-System', null=True, unique=True, verbose_name='Redmine Issue ID'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Redmine Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='troubleshootingticket',
            name='redmine_id',
            field=models.IntegerField(blank=True, help_text='ID des Tickets im Redmine-System', null=True, unique=True, verbose_name='Redmine Issue ID'),
        ),
        migrations.AddField(
            model_name='troubleshootingticket',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Redmine Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='troubleshootingticket',
            name='category',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('application', 'Applikation'), ('artefakte', 'Artefakte'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie'),
        ),
    ]
