# Generated by Django 5.0 on 2026-08-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_travelreport_notes_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelreport',
            name='notes',
            field=models.TextField(blank=True, help_text='Wird beim ersten Speichern mit Editor automatisch aus notes_html abgeleitet', verbose_name='Notizen (Plain-Text, Legacy)'),
        ),
    ]
