# Generated by Django 5.0 on 2026-08-17 09:53

import core.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_travelreport_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('product_name', models.CharField(max_length=200, verbose_name='Warenname')),
                ('article_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(default='Stück', max_length=20, verbose_name='Einheit')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('rma_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.rmacase', verbose_name='RMA-Fall')),
            ],
            options={
                'verbose_name': 'RMA-Position',
                'verbose_name_plural': 'RMA-Positionen',
                'ordering': ['rma_case', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RMAItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=core.upload_paths.rma_item_photo_path, verbose_name='Foto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rma_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service.rmaitem', verbose_name='RMA-Position')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['rma_item', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='Wareneingangsdatum')),
                ('delivery_note', models.FileField(blank=True, help_text='Lieferschein des Kunden/Absenders als PDF/Bild', null=True, upload_to=core.upload_paths.rma_receipt_document_path, verbose_name='Eingangslieferschein')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen zum Wareneingang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_receipts_received', to=settings.AUTH_USER_MODEL, verbose_name='Entgegengenommen von')),
                ('rma_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='service.rmacase', verbose_name='RMA-Fall')),
            ],
            options={
                'verbose_name': 'Wareneingang',
                'verbose_name_plural': 'Wareneingänge',
            },
        ),
        migrations.CreateModel(
            name='RMAReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert', max_length=20, null=True, unique=True, verbose_name='Lieferschein-Nr.')),
                ('return_date', models.DateField(verbose_name='Versanddatum')),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, verbose_name='Versanddienstleister')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Sendungsnummer')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=core.upload_paths.rma_return_pdf_path, verbose_name='Lieferschein PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_returns_created', to=settings.AUTH_USER_MODEL)),
                ('rma_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='service.rmacase', verbose_name='RMA-Fall')),
            ],
            options={
                'verbose_name': 'Warenausgang',
                'verbose_name_plural': 'Warenausgänge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Menge')),
                ('condition_notes', models.CharField(blank=True, max_length=200, verbose_name='Zustand/Bemerkung')),
                ('rma_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='service.rmaitem', verbose_name='RMA-Position')),
                ('rma_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.rmareturn', verbose_name='Warenausgang')),
            ],
            options={
                'verbose_name': 'Warenausgangs-Position',
                'verbose_name_plural': 'Warenausgangs-Positionen',
            },
        ),
    ]
