# Generated by Django 5.0 on 2026-08-17 11:26

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_rmaitem_rmaitemphoto_rmareceipt_rmareturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='address_country',
            field=models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='address_house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='address_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empfänger'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.upload_paths.rma_report_pdf_path, verbose_name='Reparaturbericht PDF'),
        ),
    ]
