# Generated by Django 5.0 on 2026-08-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_rmacase_address_city_rmacase_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmareturn',
            name='pdf_language',
            field=models.CharField(blank=True, default='de', max_length=10, verbose_name='PDF-Sprache'),
        ),
    ]
