# Generated by Django 5.0 on 2026-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_rmacase_evaluation_cost_rmacase_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='admin_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wird automatisch aus den Firmeneinstellungen übernommen, bleibt aber editierbar', max_digits=12, null=True, verbose_name='Verwaltungskostenpauschale'),
        ),
    ]
