# Generated by Django 5.0 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0001_initial'),
        ('service', '0024_rmacase_admin_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_cases', to='customer_orders.customerorder', verbose_name='Kundenauftrag'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='service_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_cases', to='service.serviceticket', verbose_name='Service Ticket'),
        ),
    ]