# Generated by Django 5.0 on 2026-08-18 14:57

import core.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_rmacase_customer_order_rmacase_service_ticket'),
        ('suppliers', '0021_supplierattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_manufacturer_cases', to='suppliers.supplier', verbose_name='Hersteller'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_quotation',
            field=models.FileField(blank=True, null=True, upload_to=core.upload_paths.rma_manufacturer_quotation_path, verbose_name='Kostenvoranschlag des Herstellers'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_quotation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kostenvoranschlag / Evaluierungsgebühr'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_quotation_currency',
            field=models.CharField(blank=True, default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_rma_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hersteller-RMA-Nummer'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_ship_date',
            field=models.DateField(blank=True, null=True, verbose_name='Versanddatum zum Hersteller'),
        ),
        migrations.CreateModel(
            name='RMAManufacturerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert', max_length=20, null=True, unique=True, verbose_name='Lieferschein-Nr.')),
                ('return_date', models.DateField(verbose_name='Versanddatum')),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, verbose_name='Versanddienstleister')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Sendungsnummer')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=core.upload_paths.rma_manufacturer_return_pdf_path, verbose_name='Lieferschein PDF')),
                ('pdf_language', models.CharField(blank=True, default='de', max_length=10, verbose_name='PDF-Sprache')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_manufacturer_returns_created', to=settings.AUTH_USER_MODEL)),
                ('rma_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_returns', to='service.rmacase', verbose_name='RMA-Fall')),
            ],
            options={
                'verbose_name': 'Herstellerreparatur',
                'verbose_name_plural': 'Herstellerreparaturen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAManufacturerReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Menge')),
                ('condition_notes', models.CharField(blank=True, max_length=200, verbose_name='Zustand/Bemerkung')),
                ('manufacturer_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.rmamanufacturerreturn', verbose_name='Herstellerreparatur')),
                ('rma_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_return_items', to='service.rmaitem', verbose_name='RMA-Position')),
            ],
            options={
                'verbose_name': 'Herstellerreparatur-Position',
                'verbose_name_plural': 'Herstellerreparatur-Positionen',
            },
        ),
    ]
