# Generated by Django 5.0 on 2026-08-18 15:25

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_rmacase_manufacturer_rmacase_manufacturer_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Proforma Stadt'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_address_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Proforma Land'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_address_house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Proforma Hausnummer'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_address_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proforma Empfänger'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_address_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Proforma PLZ'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Proforma Straße'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_comment',
            field=models.TextField(blank=True, help_text='Wird im PDF unterhalb der Positionen angezeigt', verbose_name='Proforma-Invoice Kommentar'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_pdf',
            field=models.FileField(blank=True, null=True, upload_to=core.upload_paths.rma_manufacturer_return_pdf_path, verbose_name='Proforma-Invoice PDF'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_title',
            field=models.CharField(blank=True, default='Proforma Invoice – For Customs Purposes Only / No Commercial Value', max_length=200, verbose_name='Proforma-Invoice Titel'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='proforma_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Beschreibung (Proforma)'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='proforma_hs_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zolltarifnummer (HS-Code)'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='proforma_origin_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ursprungsland'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='proforma_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Warenwert'),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='proforma_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Gewicht (kg)'),
        ),
        migrations.AlterField(
            model_name='rmacase',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('waiting_parts', 'Warte auf Teile'), ('at_manufacturer', 'Beim Hersteller'), ('repaired', 'Repariert'), ('not_repairable', 'Nicht reparierbar'), ('returned', 'Zurückgesendet'), ('closed', 'Abgeschlossen')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
