# Generated by Django 5.0 on 2026-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_rmareturnitem_custom_article_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hersteller Stadt'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_address_country',
            field=models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Hersteller Land'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_address_house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hersteller Hausnummer'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_address_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hersteller Empfänger'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_address_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hersteller PLZ'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hersteller Straße'),
        ),
    ]
