# Generated by Django 5.0 on 2026-09-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_rmacase_manufacturer_address_city_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='custom_article_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='custom_product_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='custom_serial_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='rmamanufacturerreturnitem',
            name='custom_unit',
            field=models.CharField(blank=True, default='Stk', max_length=50),
        ),
        migrations.AlterField(
            model_name='rmamanufacturerreturnitem',
            name='rma_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_return_items', to='service.rmaitem', verbose_name='RMA-Position'),
        ),
        migrations.AlterField(
            model_name='rmareturnitem',
            name='rma_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='service.rmaitem', verbose_name='RMA-Position'),
        ),
            ],
        ),
    ]
