# Generated by Django 5.0 on 2026-09-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_rmamanufacturerreturnitem_custom_article_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmamanufacturerreturn',
            name='proforma_subtitle',
            field=models.CharField(blank=True, default='For Customs Purposes Only / No Commercial Value', max_length=300, verbose_name='Proforma-Invoice Untertitel'),
        ),
    ]
