# Generated by Django 5.0 on 2026-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_rmamanufacturerreturn_proforma_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmareturn',
            name='proforma_subtitle',
            field=models.CharField(blank=True, default='For Customs Purposes Only / No Commercial Value', max_length=300, verbose_name='Proforma-Invoice Untertitel'),
        ),
    ]
