# Generated by Django 5.0 on 2026-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_rmareturn_proforma_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmacase',
            name='status',
            field=models.CharField(choices=[('open', 'Offen'), ('dead_on_arrival', 'Dead On Arrival'), ('in_progress', 'In Bearbeitung'), ('waiting_parts', 'Warte auf Teile'), ('at_manufacturer', 'Beim Hersteller'), ('repaired', 'Repariert'), ('not_repairable', 'Nicht reparierbar'), ('returned', 'Zurückgesendet'), ('payment_pending', 'Zahlung offen'), ('closed', 'Abgeschlossen')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
