# Generated by Django 5.0 on 2026-10-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_offer_document'),
        ('service', '0037_normalize_rma_delivery_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_manufacturer_cases', to='orders.order', verbose_name='Bestellung an den Hersteller'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_order_comment',
            field=models.TextField(blank=True, help_text='Zum Beispiel vereinbarter Preis, Rücksendebedingungen, Ansprechpartner.', verbose_name='Kommentar zur Beauftragung'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der Beauftragung'),
        ),
        migrations.AddField(
            model_name='rmacase',
            name='manufacturer_order_number',
            field=models.CharField(blank=True, help_text='Die Visitron-Bestellnummer für diese Reparatur. Nur nötig, wenn keine Bestellung ausgewählt wurde.', max_length=100, verbose_name='Bestellnummer Visitron (Freitext)'),
        ),
    ]
