# Generated by Django 5.0 on 2026-09-25 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0011_customer_model_organisms_customer_research_fields_and_more'),
        ('inventory', '0009_inventoryitem_production_checklist_data_and_more'),
        ('users', '0044_user_can_read_inventory_demo_systems_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name der Vorlage')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard-Vorlage')),
                ('data', models.JSONField(default=dict, verbose_name='Konfigurationsdaten')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_config_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_config_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Demo-Konfigurationsvorlage',
                'verbose_name_plural': 'Demo-Konfigurationsvorlagen',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DemoDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('laser_system', 'Lasersystem'), ('camera', 'Kamera'), ('confocal', 'Confocal'), ('microscope', 'Mikroskop'), ('illumination', 'Beleuchtungsgerät'), ('scanning_stage', 'Scanningtisch'), ('incubation_chamber', 'Inkubationskammer'), ('controller', 'Steuerung'), ('pc', 'PC'), ('custom', 'Benutzerdefiniert'), ('other', 'Sonstiges')], default='custom', max_length=20, verbose_name='Gerätetyp')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Freie Eigenschaften als Schlüssel/Wert-Paare (z.B. OS, CPU, RAM bei PC)', verbose_name='Grundeigenschaften')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('defect', 'Defekt'), ('loaned', 'Verliehen')], default='active', max_length=20, verbose_name='Status')),
                ('position_x', models.FloatField(default=0, verbose_name='Position X')),
                ('position_y', models.FloatField(default=0, verbose_name='Position Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_devices_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_device_usages', to='inventory.inventoryitem', verbose_name='Lagerartikel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_devices_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Demo-Gerät',
                'verbose_name_plural': 'Demo-Geräte',
                'ordering': ['demo_system', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemoDeviceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('filter_wheel', 'Filterrad'), ('objective_changer', 'Objektivwechsler'), ('light_path_changer', 'Lichtwegwechsler (motorisiert)'), ('card_changer', 'Einsteckkarten-Wechsler'), ('shutter', 'Shutter'), ('slider', 'Slider (Intensitätsregler)'), ('custom', 'Benutzerdefiniert')], default='custom', max_length=20, verbose_name='Komponententyp')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('slots', models.JSONField(blank=True, default=dict, help_text='Positionsliste (1-10) für Wechsler-Typen: {"slots": [{"position": 1, "label": "...", "comment": "..."}]}', verbose_name='Belegung')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Wert')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_components_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='demo_systems.demodevice', verbose_name='Gerät')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_components_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Demo-Gerätekomponente',
                'verbose_name_plural': 'Demo-Gerätekomponenten',
                'ordering': ['device', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DemoSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format D-00001', max_length=10, null=True, unique=True, verbose_name='Demo-Nummer')),
                ('name', models.CharField(max_length=200, verbose_name='Name des Demo-Systems')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('location', models.CharField(blank=True, help_text='z.B. Labor, Raum, Gebäude', max_length=200, verbose_name='Standort')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_systems_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_demo_systems', to='users.employee', verbose_name='Zuständiger Mitarbeiter')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_systems_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Demo-System',
                'verbose_name_plural': 'Demo-Systeme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='demodevice',
            name='demo_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='demo_systems.demosystem', verbose_name='Demo-System'),
        ),
        migrations.CreateModel(
            name='DemoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_side', models.CharField(choices=[('north', 'Nord'), ('east', 'Ost'), ('south', 'Süd'), ('west', 'West')], max_length=10, verbose_name='Andockpunkt (von)')),
                ('to_side', models.CharField(choices=[('north', 'Nord'), ('east', 'Ost'), ('south', 'Süd'), ('west', 'West')], max_length=10, verbose_name='Andockpunkt (zu)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_connections_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='demo_systems.demodevice', verbose_name='Von Gerät')),
                ('to_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='demo_systems.demodevice', verbose_name='Zu Gerät')),
                ('demo_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='demo_systems.demosystem', verbose_name='Demo-System')),
            ],
            options={
                'verbose_name': 'Demo-Verbindung',
                'verbose_name_plural': 'Demo-Verbindungen',
            },
        ),
        migrations.CreateModel(
            name='DemoChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('system', 'Demo-System'), ('device', 'Gerät'), ('connection', 'Verbindung'), ('component', 'Komponente'), ('booking', 'Buchung')], max_length=20, verbose_name='Objekttyp')),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('entity_label', models.CharField(blank=True, help_text='Lesbare Bezeichnung (bleibt auch nach Löschen des Objekts erhalten)', max_length=255, verbose_name='Objekt')),
                ('action', models.CharField(choices=[('created', 'Angelegt'), ('updated', 'Geändert'), ('deleted', 'Gelöscht'), ('status_changed', 'Status geändert'), ('connected', 'Verbunden'), ('disconnected', 'Getrennt'), ('comment', 'Kommentar')], max_length=20, verbose_name='Aktion')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Feld')),
                ('old_value', models.TextField(blank=True, verbose_name='Alter Wert')),
                ('new_value', models.TextField(blank=True, verbose_name='Neuer Wert')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('comment_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Kommentiert am')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_changelog_comments', to=settings.AUTH_USER_MODEL, verbose_name='Kommentiert von')),
                ('demo_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='demo_systems.demosystem', verbose_name='Demo-System')),
            ],
            options={
                'verbose_name': 'Demo-Änderungsprotokoll',
                'verbose_name_plural': 'Demo-Änderungsprotokoll',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Zweck/Titel')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Storniert')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_bookings_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_bookings', to='customers.customer', verbose_name='Kunde')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Gebucht von')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_bookings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('demo_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='demo_systems.demosystem', verbose_name='Demo-System')),
            ],
            options={
                'verbose_name': 'Demo-Buchung',
                'verbose_name_plural': 'Demo-Buchungen',
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='democonnection',
            constraint=models.UniqueConstraint(fields=('from_device', 'from_side'), name='unique_from_dock'),
        ),
        migrations.AddConstraint(
            model_name='democonnection',
            constraint=models.UniqueConstraint(fields=('to_device', 'to_side'), name='unique_to_dock'),
        ),
    ]
