# Generated by Django 5.0 on 2026-09-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosystem',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('defect', 'Defekt'), ('loaned', 'Verliehen'), ('demo_away', 'Demo außer Haus'), ('fair', 'Auf Messe')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='demodevice',
            name='device_type',
            field=models.CharField(choices=[('laser_system', 'Lasersystem'), ('camera', 'Kamera'), ('confocal', 'Confocal'), ('microscope', 'Mikroskop'), ('illumination', 'Beleuchtungsgerät'), ('scanning_stage', 'Scanningtisch'), ('incubation_chamber', 'Inkubationskammer'), ('virtex', 'ViRTEx'), ('pc', 'PC'), ('custom', 'Benutzerdefiniert')], default='custom', max_length=20, verbose_name='Gerätetyp'),
        ),
        migrations.AlterField(
            model_name='demodevice',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('defect', 'Defekt'), ('loaned', 'Verliehen'), ('removed', 'Abgebaut')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
