# Generated by Django 5.0 on 2026-01-20 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visiview', '0013_alter_visiviewlicensehistory_change_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MondayMeetingTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('priority', models.IntegerField(default=0, help_text='Höhere Zahl = höhere Priorität', verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monday_meeting_todos_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Montagsmeeting Todo',
                'verbose_name_plural': 'Montagsmeeting Todos',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesMeetingTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('priority', models.IntegerField(default=0, help_text='Höhere Zahl = höhere Priorität', verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_meeting_todos_completed', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_meeting_todos_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Vertriebsmeeting Todo',
                'verbose_name_plural': 'Vertriebsmeeting Todos',
                'ordering': ['is_completed', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewMeetingTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('priority', models.IntegerField(default=0, help_text='Höhere Zahl = höhere Priorität', verbose_name='Priorität')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_meeting_todos_completed', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_meeting_todos_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('visiview_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_todos', to='visiview.visiviewticket', verbose_name='Verknüpftes Ticket')),
            ],
            options={
                'verbose_name': 'VisiView-Meeting Todo',
                'verbose_name_plural': 'VisiView-Meeting Todos',
                'ordering': ['is_completed', '-priority', '-created_at'],
            },
        ),
    ]
