# Generated by Django 5.0 on 2025-12-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Visitron System', max_length=200, verbose_name='Firmenname')),
                ('street', models.CharField(max_length=100, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=10, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Bank')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('managing_director', models.CharField(max_length=200, verbose_name='Geschäftsführer')),
                ('commercial_register', models.CharField(help_text='z.B. HRB 123456', max_length=100, verbose_name='Handelsregister')),
                ('register_court', models.CharField(default='Amtsgericht München', max_length=100, verbose_name='Registergericht')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('vat_id', models.CharField(blank=True, max_length=50, verbose_name='USt-IdNr.')),
                ('document_header', models.ImageField(blank=True, help_text='Logo/Header für Bestelldokumente (empfohlen: PNG, ca. 800x150px)', null=True, upload_to='company/headers/', verbose_name='Dokument-Header')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmeneinstellung',
                'verbose_name_plural': 'Firmeneinstellungen',
            },
        ),
    ]
