# Generated by Django 5.0 on 2025-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='managing_director',
            field=models.TextField(blank=True, help_text='Mehrere Geschäftsführer mit Komma trennen', verbose_name='Geschäftsführer'),
        ),
    ]
