# Generated by Django 5.0 on 2025-12-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companysettings_managing_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='bic',
            field=models.CharField(blank=True, max_length=11, verbose_name='BIC'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='commercial_register',
            field=models.CharField(blank=True, help_text='z.B. HRB 123456', max_length=100, verbose_name='Handelsregister'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
    ]
