# Generated by Django 5.0 on 2025-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companysettings_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
