# Generated by Django 5.0 on 2025-12-28 17:49

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companysettings_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='document_header',
            field=models.ImageField(blank=True, help_text='Logo/Header für Bestelldokumente (empfohlen: PNG, ca. 800x150px)', null=True, upload_to=core.upload_paths.company_upload_path, verbose_name='Dokument-Header'),
        ),
    ]
