# Generated by Django 5.0 on 2026-01-11 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_update_document_header_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='fiscal_year_start_day',
            field=models.PositiveIntegerField(default=1, help_text='Tag, an dem das Geschäftsjahr beginnt (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Geschäftsjahr Starttag'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='fiscal_year_start_month',
            field=models.PositiveIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], default=4, help_text='Monat, in dem das Geschäftsjahr beginnt (1-12)', verbose_name='Geschäftsjahr Startmonat'),
        ),
    ]
