# Generated by Django 5.0 on 2026-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companysettings_fiscal_year_start_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wird automatisch in der RMA-Kalkulation übernommen (bleibt editierbar)', max_digits=10, verbose_name='Standard-Stundensatz'),
        ),
    ]
