# Generated by Django 5.0 on 2026-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companysettings_default_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wird automatisch in der RMA-Kalkulation übernommen (bleibt editierbar)', max_digits=12, verbose_name='Verwaltungskostenpauschale'),
        ),
    ]
