# Generated by Django 5.0 on 2026-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companysettings_default_admin_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tagline',
            field=models.CharField(blank=True, default='Bildverarbeitung · Mikroskopie', help_text='Kleine Zeile rechts unter dem Logo, z.B. "Bildverarbeitung · Mikroskopie"', max_length=200, verbose_name='Briefkopf-Unterzeile'),
        ),
    ]
