# Generated by Django 5.0 on 2026-10-01 08:55

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_companysettings_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tagline_english',
            field=models.CharField(blank=True, default='Imaging · Microscopy', help_text='Gegenstück zur deutschen Unterzeile für englische Dokumente.', max_length=200, verbose_name='Briefkopf-Unterzeile (englisch)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='document_header',
            field=models.ImageField(blank=True, help_text='Logo für die Bestelldokumente. Optional: leer lassen, dann wird das mitgelieferte Standard-Logo verwendet, das exakt aus der Vorlage Q-373Du-0826.pdf geschnitten wurde. Empfohlenes Format: PNG mit transparentem Hintergrund.', null=True, upload_to=core.upload_paths.company_upload_path, verbose_name='Dokument-Header'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='tagline',
            field=models.CharField(blank=True, default='Bildverarbeitung · Mikroskopie', help_text='Kleine Zeile rechts unter dem Logo. Wird automatisch ins Englische übersetzt, solange dieser Wert unverändert bleibt. Ein eigener Text erscheint in beiden Sprachen.', max_length=200, verbose_name='Briefkopf-Unterzeile (deutsch)'),
        ),
    ]
