# Generated by Django 5.0 on 2026-04-07 13:38

import customer_loans.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_add_customer_legacy_mapping'),
        ('inventory', '0009_inventoryitem_production_checklist_data_and_more'),
        ('users', '0039_user_can_read_inventory_customer_loans_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format VL-00001', max_length=10, null=True, unique=True, verbose_name='Verleihnummer')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('verliehen', 'Verliehen'), ('teilrueckgabe', 'Teilrückgabe'), ('abgeschlossen', 'Abgeschlossen')], default='offen', max_length=20, verbose_name='Status')),
                ('loan_date', models.DateField(verbose_name='Verleihdatum')),
                ('return_deadline', models.DateField(blank=True, null=True, verbose_name='Rückgabefrist')),
                ('delivery_address_name', models.CharField(blank=True, max_length=200, verbose_name='Empfänger')),
                ('delivery_address_street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('delivery_address_house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('delivery_address_postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('delivery_address_city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('delivery_address_country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('standard_clause', models.TextField(default='Schäden und Verlust an der Leihware gehen zu Ihren Lasten. Verlängerung der Leihung nur nach Absprache.', help_text='Wird auf dem Leihlieferschein abgedruckt', verbose_name='Standardklausel')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=customer_loans.models.customer_loan_upload_path, verbose_name='Leihlieferschein PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loans_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_loans', to='customers.customer', verbose_name='Kunde')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_customer_loans', to='users.employee', verbose_name='Zuständiger Mitarbeiter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loans_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Verleihung',
                'verbose_name_plural': 'Verleihungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('article_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(default='Stück', max_length=20, verbose_name='Einheit')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Zurückgegeben')),
                ('is_returned_complete', models.BooleanField(default=False, verbose_name='Vollständig zurückgegeben')),
                ('is_returned_intact', models.BooleanField(default=False, verbose_name='Intakt zurückgegeben')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Vom Kunden gekauft')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Rückgabedatum')),
                ('return_notes', models.TextField(blank=True, verbose_name='Rückgabe-Notizen')),
                ('customer_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_loans.customerloan', verbose_name='Verleihung')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loan_items', to='inventory.inventoryitem', verbose_name='Lagerartikel')),
            ],
            options={
                'verbose_name': 'Verleihungsposition',
                'verbose_name_plural': 'Verleihungspositionen',
                'ordering': ['position'],
            },
        ),
    ]
