# Generated by Django 5.0 on 2025-12-28 20:38

import django.db.models.deletion
import manufacturing.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_orders', '0003_customerorder_vat_id'),
        ('suppliers', '0018_tradingproduct_release_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VSHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format VSH-00001', max_length=10, null=True, unique=True, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('model_designation', models.CharField(blank=True, max_length=100, verbose_name='Modellbezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('release_manual', models.FileField(blank=True, help_text='Freigegebenes Handbuch', null=True, upload_to=manufacturing.models.vsh_manual_upload_path, verbose_name='Release-Manual')),
                ('draft_manual', models.FileField(blank=True, help_text='Entwurf des Handbuchs', null=True, upload_to=manufacturing.models.vsh_manual_upload_path, verbose_name='Draft-Manual')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vshardware_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'VS-Hardware',
                'verbose_name_plural': 'VS-Hardware',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingegangen am')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bearbeitet am')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_inbox_items', to='customer_orders.customerorder', verbose_name='Kundenauftrag')),
                ('customer_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_inbox_entries', to='customer_orders.customerorderitem', verbose_name='Auftragsposition')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_inbox_processed', to=settings.AUTH_USER_MODEL, verbose_name='Bearbeitet von')),
                ('vs_hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_inbox_entries', to='manufacturing.vshardware', verbose_name='VS-Hardware')),
            ],
            options={
                'verbose_name': 'Fertigungsauftragseingang',
                'verbose_name_plural': 'Fertigungsauftragseingänge',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format FA-XXXXX', max_length=15, null=True, unique=True, verbose_name='Fertigungsauftragsnummer')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='created', max_length=20, verbose_name='Status')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Geplanter Start')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Geplantes Ende')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='customer_orders.customerorder', verbose_name='Kundenauftrag')),
                ('inbox_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_order', to='manufacturing.productionorderinbox', verbose_name='Eingangs-Eintrag')),
                ('vs_hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='manufacturing.vshardware', verbose_name='VS-Hardware')),
            ],
            options={
                'verbose_name': 'Fertigungsauftrag',
                'verbose_name_plural': 'Fertigungsaufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VSHardwareCostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Arbeitsstunden')),
                ('labor_rate', models.DecimalField(decimal_places=2, default=Decimal('65.00'), max_digits=8, verbose_name='Stundensatz (EUR)')),
                ('development_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamtentwicklungskosten (EUR)')),
                ('expected_sales_volume', models.PositiveIntegerField(default=1, verbose_name='Erwarteter Absatz (Stück)')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Materialkosten (EUR)')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arbeitskosten (EUR)')),
                ('development_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Entwicklungskosten pro Stück (EUR)')),
                ('total_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamt-Einkaufspreis (EUR)')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, verbose_name='Marge (%)')),
                ('calculated_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kalkulierter Verkaufspreis (EUR)')),
                ('name', models.CharField(blank=True, help_text='z.B. "Version 2024-Q1"', max_length=100, verbose_name='Kalkulationsname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_calculations_created', to=settings.AUTH_USER_MODEL)),
                ('vs_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_calculations', to='manufacturing.vshardware', verbose_name='VS-Hardware')),
            ],
            options={
                'verbose_name': 'Kostenkalkulation',
                'verbose_name_plural': 'Kostenkalkulationen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VSHardwareDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('drawing', 'Zeichnung (CAD)'), ('assembly', 'Aufbauanleitung'), ('adjustment', 'Justageanleitung'), ('photo', 'Foto'), ('test_report', 'Testbericht'), ('other', 'Sonstiges')], max_length=20, verbose_name='Dokumenttyp')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('file', models.FileField(upload_to=manufacturing.models.vsh_document_upload_path, verbose_name='Datei')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vshardware_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('vs_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='manufacturing.vshardware', verbose_name='VS-Hardware')),
            ],
            options={
                'verbose_name': 'Fertigungsdokument',
                'verbose_name_plural': 'Fertigungsdokumente',
                'ordering': ['document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VSHardwareMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Menge')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notizen')),
                ('material_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vshardware_usages', to='suppliers.materialsupply', verbose_name='Material & Supply')),
                ('vs_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='manufacturing.vshardware', verbose_name='VS-Hardware')),
            ],
            options={
                'verbose_name': 'Material-Position',
                'verbose_name_plural': 'Material-Positionen',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VSHardwarePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Kalkulierter Einkaufspreis', max_digits=12, verbose_name='Einkaufspreis (EUR)')),
                ('sales_price', models.DecimalField(decimal_places=2, help_text='Listenpreis für Angebote', max_digits=12, verbose_name='Verkaufspreis (EUR)')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, help_text='Leer = unbegrenzt gültig', null=True, verbose_name='Gültig bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vshardware_prices_created', to=settings.AUTH_USER_MODEL)),
                ('vs_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='manufacturing.vshardware', verbose_name='VS-Hardware')),
            ],
            options={
                'verbose_name': 'VS-Hardware Preis',
                'verbose_name_plural': 'VS-Hardware Preise',
                'ordering': ['vs_hardware', '-valid_from'],
            },
        ),
    ]
