# Generated by Django 5.0 on 2025-12-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vshardware',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description for international quotations', verbose_name='Beschreibung (Englisch)'),
        ),
    ]
