# Generated by Django 5.0 on 2026-01-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_vshardware_product_category'),
        ('projects', '0003_project_forecast_probability_and_more'),
        ('verp_settings', '0004_alter_productcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='checklist_data',
            field=models.JSONField(blank=True, help_text='Checklistendaten abhängig von der Warenkategorie', null=True, verbose_name='Fertigungscheckliste'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='estimated_completion_date',
            field=models.DateField(blank=True, help_text='Voraussichtliches Datum der Fertigstellung', null=True, verbose_name='Avisiertes Fertigungsende'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product_category',
            field=models.ForeignKey(blank=True, help_text='Erforderlich zum Starten des Fertigungsauftrags', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='verp_settings.productcategory', verbose_name='Warenkategorie'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Seriennummer der gefertigten Ware', max_length=100, verbose_name='Seriennummer'),
        ),
    ]
