# Generated by Django 5.0 on 2025-12-19 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(blank=True, editable=False, help_text='Automatisch generierte Kundennummer', max_length=10, null=True, unique=True, verbose_name='Kundennummer')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titel')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('language', models.CharField(choices=[('DE', 'Deutsch'), ('EN', 'English'), ('FR', 'Français'), ('ES', 'Español'), ('IT', 'Italiano')], default='DE', max_length=2, verbose_name='Sprache')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('Office', 'Büro'), ('Labor', 'Labor'), ('Post', 'Postanschrift'), ('Lieferung', 'Lieferadresse'), ('Rechnung', 'Rechnungsadresse')], default='Office', max_length=20, verbose_name='Adresstyp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Universität')),
                ('institute', models.CharField(blank=True, max_length=200, verbose_name='Institut')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Lehrstuhl/Abteilung')),
                ('street', models.CharField(max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=20, verbose_name='Hausnummer')),
                ('address_supplement', models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz')),
                ('postal_code', models.CharField(max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Bundesland/Region')),
                ('country', models.CharField(default='DE', help_text='ISO 3166-1 Alpha-2 Code', max_length=2, verbose_name='Land')),
                ('directions', models.TextField(blank=True, verbose_name='Anfahrtsbeschreibung')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Kundenadresse',
                'verbose_name_plural': 'Kundenadressen',
                'ordering': ['-is_active', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primär')),
                ('newsletter_consent', models.BooleanField(default=False, verbose_name='Newsletter erlaubt')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Werbung erlaubt')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'E-Mail-Adresse',
                'verbose_name_plural': 'E-Mail-Adressen',
                'ordering': ['-is_primary', 'email'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('Büro', 'Büro'), ('Mobil', 'Mobil'), ('Lab', 'Labor')], default='Büro', max_length=20, verbose_name='Typ')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefonnummer')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primär')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Telefonnummer',
                'verbose_name_plural': 'Telefonnummern',
                'ordering': ['-is_primary', 'phone_type'],
            },
        ),
    ]
