# Generated by Django 5.0 on 2025-12-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_number', models.CharField(blank=True, editable=False, help_text='Automatisch generierte Systemnummer', max_length=20, null=True, unique=True, verbose_name='Systemnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Systemname')),
                ('system_type', models.CharField(blank=True, max_length=200, verbose_name='Systemtyp')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installationsdatum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Kundensystem',
                'verbose_name_plural': 'Kundensysteme',
                'ordering': ['-created_at'],
            },
        ),
    ]
