# Generated by Django 5.0 on 2025-12-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customersystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], help_text='z.B. Herr, Frau, Mr., Mrs.', max_length=20, verbose_name='Anrede'),
        ),
    ]
