# Generated by Django 5.0 on 2025-12-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_add_customer_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('Office', 'Büro'), ('Labor', 'Labor'), ('Post', 'Postanschrift'), ('Lieferung', 'Lieferadresse'), ('Rechnung', 'Rechnungsadresse'), ('Einkauf', 'Einkaufsadresse')], default='Office', max_length=20, verbose_name='Adresstyp'),
        ),
    ]
