# Generated by Django 5.0 on 2026-01-01 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customeraddress_address_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advertising_status',
            field=models.CharField(choices=[('neu', 'Neu'), ('zugestimmt', 'Zugestimmt'), ('abgelehnt', 'Abgelehnt')], default='neu', help_text='Status für Werbung/Newsletter', max_length=20, verbose_name='Werbestatus'),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Kunde ist als Referenz geeignet', verbose_name='Referenzkunde'),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_customers', to=settings.AUTH_USER_MODEL, verbose_name='Zuständiger Mitarbeiter'),
        ),
    ]
