# Generated by Django 5.0 on 2026-02-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_advertising_status_customer_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField(verbose_name='Kontaktdatum')),
                ('contact_type', models.CharField(choices=[('EMAIL', 'E-Mail'), ('PHONE', 'Telefon'), ('MEETING', 'Treffen')], max_length=20, verbose_name='Kontaktart')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_history', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_history', to='customers.customer', verbose_name='Kunde')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_history', to='customers.customersystem', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Kontakthistorie',
                'verbose_name_plural': 'Kontakthistorie',
                'ordering': ['-contact_date', '-created_at'],
            },
        ),
    ]
