# Generated by Django 5.0 on 2026-02-09 15:46

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_ids(apps, schema_editor):
    """Kopiert bestehende legacy_sql_id Werte in die neue Mapping-Tabelle."""
    Customer = apps.get_model('customers', 'Customer')
    CustomerLegacyMapping = apps.get_model('customers', 'CustomerLegacyMapping')

    customers_with_legacy = Customer.objects.filter(legacy_sql_id__isnull=False)
    mappings = []
    for customer in customers_with_legacy:
        mappings.append(CustomerLegacyMapping(
            customer=customer,
            sql_id=customer.legacy_sql_id,
        ))
    if mappings:
        CustomerLegacyMapping.objects.bulk_create(mappings, ignore_conflicts=True)


def reverse_migrate(apps, schema_editor):
    """Rückwärtsmigration: Mapping-Tabelle → legacy_sql_id."""
    CustomerLegacyMapping = apps.get_model('customers', 'CustomerLegacyMapping')
    for mapping in CustomerLegacyMapping.objects.all():
        mapping.customer.legacy_sql_id = mapping.sql_id
        mapping.customer.save(update_fields=['legacy_sql_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_legacy_sql_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='legacy_sql_id',
            field=models.IntegerField(blank=True, help_text='Primäre AdressenID - für mehrere IDs siehe Legacy-Mappings', null=True, verbose_name='Legacy SQL ID (primär)'),
        ),
        migrations.CreateModel(
            name='CustomerLegacyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_id', models.IntegerField(help_text='AdressenID aus der externen SQL-Datenbank', unique=True, verbose_name='SQL AdressenID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Verknüpft am')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_mappings', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Legacy-Mapping',
                'verbose_name_plural': 'Legacy-Mappings',
                'ordering': ['sql_id'],
            },
        ),
        migrations.RunPython(migrate_legacy_ids, reverse_migrate),
    ]
