# Generated by Django 5.0 on 2026-04-17 12:37

import customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_add_customer_legacy_mapping'),
        ('orders', '0015_order_offer_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLProjektExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_projekt_id', models.IntegerField(help_text='InteressenID aus der SQL-Datenbank', unique=True, verbose_name='SQL InteressenID')),
                ('projekt_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Projektname')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sql_projekte', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sql_projekte', to='customers.customer', verbose_name='VERP-Kunde')),
                ('verp_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sql_projekte', to='orders.order', verbose_name='VERP-Auftrag')),
            ],
            options={
                'verbose_name': 'SQL-Projekt Zusatzinfo',
                'verbose_name_plural': 'SQL-Projekt Zusatzinfos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SQLProjektDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=customers.models.sql_projekt_document_path, verbose_name='Datei')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Bezeichnung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
                ('sql_projekt_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.sqlprojektextra', verbose_name='SQL-Projekt')),
            ],
            options={
                'verbose_name': 'SQL-Projekt Dokument',
                'verbose_name_plural': 'SQL-Projekt Dokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SQLProjektAngebotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_angebot_nummer', models.IntegerField(help_text='AngebotNummer aus der SQL-Datenbank', verbose_name='SQL Angebotsnummer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sql_projekt_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angebot_links', to='customers.sqlprojektextra', verbose_name='SQL-Projekt')),
            ],
            options={
                'verbose_name': 'SQL-Angebot-Verknüpfung',
                'verbose_name_plural': 'SQL-Angebot-Verknüpfungen',
                'unique_together': {('sql_projekt_extra', 'sql_angebot_nummer')},
            },
        ),
    ]
