# Generated by Django 5.0 on 2026-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_sqlprojektextra_sqlprojektdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlprojektextra',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
