# Generated by Django 5.0 on 2026-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_sqlprojektextra_is_active'),
        ('systems', '0014_workgroupoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='model_organisms',
            field=models.ManyToManyField(blank=True, related_name='customers', to='systems.modelorganismoption', verbose_name='Modellorganismen'),
        ),
        migrations.AddField(
            model_name='customer',
            name='research_fields',
            field=models.ManyToManyField(blank=True, related_name='customers', to='systems.researchfieldoption', verbose_name='Forschungsgebiete'),
        ),
        migrations.AddField(
            model_name='customer',
            name='work_groups',
            field=models.ManyToManyField(blank=True, related_name='customers', to='systems.workgroupoption', verbose_name='Arbeitsgruppen'),
        ),
    ]
