# Generated by Django 5.0 on 2025-12-28 18:50

import django.db.models.deletion
import systems.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customersystem'),
        ('inventory', '0004_change_order_item_on_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format S-00001', max_length=10, null=True, unique=True, verbose_name='Systemnummer')),
                ('system_name', models.CharField(help_text='Name des Systems (z.B. IAU-Sternname)', max_length=100, verbose_name='Systemname')),
                ('description', models.TextField(blank=True, verbose_name='Systembeschreibung')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('maintenance', 'In Wartung'), ('decommissioned', 'Außer Betrieb')], default='active', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, help_text='z.B. Labor, Raum, Gebäude', max_length=200, verbose_name='Standort')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installationsdatum')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='Garantie bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_records', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systeme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('component_type', models.CharField(choices=[('inventory', 'Aus Warenlager'), ('custom', 'Benutzerdefiniert')], default='custom', max_length=20, verbose_name='Komponententyp')),
                ('name', models.CharField(max_length=200, verbose_name='Modell/Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='Version/Treiber')),
                ('category', models.CharField(choices=[('microscope', 'Mikroskop'), ('camera', 'Kamera'), ('objective', 'Objektiv'), ('stage', 'Tisch/Stage'), ('illumination', 'Beleuchtung'), ('filter', 'Filter'), ('controller', 'Controller'), ('software', 'Software'), ('accessory', 'Zubehör'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_usages', to='inventory.inventoryitem', verbose_name='Lagerartikel')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='systems.system', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Systemkomponente',
                'verbose_name_plural': 'Systemkomponenten',
                'ordering': ['system', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SystemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=systems.models.system_photo_upload_path, verbose_name='Foto')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptbild')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='systems.system', verbose_name='System')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Systemfoto',
                'verbose_name_plural': 'Systemfotos',
                'ordering': ['system', 'position'],
            },
        ),
    ]
