# Generated by Django 5.0 on 2026-01-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
        ('visiview', '0006_visiviewticket_visiview_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='visiview_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_systems', to='visiview.visiviewlicense', verbose_name='VisiView Lizenz'),
        ),
    ]
