# Generated by Django 5.0 on 2026-01-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_advertising_status_customer_description_and_more'),
        ('systems', '0002_system_visiview_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_records', to='customers.customer', verbose_name='Kunde'),
        ),
    ]
