# Generated by Django 5.0 on 2026-01-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_alter_system_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='warranty_end',
        ),
    ]
