# Generated by Django 5.0 on 2026-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_remove_system_warranty_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='location_address_supplement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_country',
            field=models.CharField(blank=True, default='DE', help_text='ISO 3166-1 Alpha-2 Code', max_length=2, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lehrstuhl/Abteilung'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_institute',
            field=models.CharField(blank=True, max_length=200, verbose_name='Institut'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_university',
            field=models.CharField(blank=True, max_length=200, verbose_name='Universität/Institution'),
        ),
    ]
