# Generated by Django 5.0 on 2026-02-01 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_add_location_address_fields'),
        ('users', '0034_add_responsible_employee_and_sales_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_systems', to='users.employee', verbose_name='Zuständiger Mitarbeiter'),
        ),
    ]
