# Generated by Django 5.0 on 2026-02-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_add_responsible_employee_and_sales_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Breitengrad (Latitude)'),
        ),
        migrations.AddField(
            model_name='system',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Längengrad (Longitude)'),
        ),
    ]
