# Generated by Django 5.0 on 2026-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_add_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='status',
            field=models.CharField(choices=[('unbekannt', 'Unbekannt'), ('in_nutzung', 'In Nutzung'), ('in_wartung', 'In Wartung'), ('ausser_betrieb', 'Außer Betrieb')], default='unbekannt', max_length=20, verbose_name='Status'),
        ),
    ]
