# Generated by Django 5.0 on 2026-02-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_change_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcomponent',
            name='is_legacy',
            field=models.BooleanField(default=False, verbose_name='Legacy/Veraltet'),
        ),
        migrations.AddField(
            model_name='systemphoto',
            name='is_outdated',
            field=models.BooleanField(default=False, verbose_name='Veraltet'),
        ),
    ]
