# Generated by Django 5.0 on 2026-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_model_organism_research_field_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='maintenance_offer_declined',
            field=models.BooleanField(default=False, verbose_name='Maintenance Angebot abgelehnt'),
        ),
        migrations.AddField(
            model_name='system',
            name='maintenance_offer_received',
            field=models.BooleanField(default=False, verbose_name='Maintenance Angebot erhalten'),
        ),
        migrations.AlterField(
            model_name='modelorganismoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='researchfieldoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
