# Generated by Django 5.0 on 2026-02-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_add_customer_legacy_mapping'),
        ('systems', '0012_system_maintenance_offer_declined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Ansprechpartner beim Kunden für dieses System', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_systems', to='customers.customer', verbose_name='Ansprechpartner'),
        ),
    ]
