# Generated by Django 5.0 on 2026-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_add_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Arbeitsgruppe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Arbeitsgruppe',
                'verbose_name_plural': 'Arbeitsgruppen',
                'ordering': ['name'],
            },
        ),
    ]
