# Generated by Django 5.0 on 2025-12-21 13:14

import customer_orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('angelegt', 'Angelegt'), ('bestaetigt', 'Bestätigt'), ('in_produkt', 'In Produktion'), ('geliefert', 'Geliefert'), ('abgeschlossen', 'Abgeschlossen'), ('storniert', 'Storniert')], default='angelegt', max_length=30)),
                ('project_reference', models.CharField(blank=True, max_length=200)),
                ('system_reference', models.CharField(blank=True, max_length=200)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('customer_document', models.FileField(blank=True, null=True, upload_to=customer_orders.models.customer_order_document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Kundenauftrag',
                'verbose_name_plural': 'Kundenaufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='Stück', max_length=50)),
                ('list_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('position', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_orders.customerorder')),
            ],
            options={
                'verbose_name': 'Kundenauftragsposition',
                'verbose_name_plural': 'Kundenauftragspositionen',
                'ordering': ['order', 'position'],
            },
        ),
    ]
