# Generated by Django 5.0 on 2025-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='billing_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Rechnungsadresse'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Rechnungs-E-Mail'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='confirmation_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Bestätigungsadresse'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='confirmation_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Bestätigungs-E-Mail'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name des Bestellers'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kundenbestellnummer'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Bemerkungen'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Versandadresse'),
        ),
    ]
