# Generated by Django 5.0 on 2025-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0002_customerorder_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='vat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Umsatzsteuer-ID'),
        ),
    ]
