# Generated by Django 5.0 on 2025-12-30 10:24

import customer_orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0003_customerorder_vat_id'),
        ('sales', '0012_alter_quotation_date_field'),
        ('verp_settings', '0007_warrantyterm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorderitem',
            options={'ordering': ['order', 'position'], 'verbose_name': 'Auftragsposition', 'verbose_name_plural': 'Auftragspositionen'},
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='vat_id',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bestätigungsdatum'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='confirmation_pdf',
            field=models.FileField(blank=True, null=True, upload_to=customer_orders.models.order_confirmation_upload_path, verbose_name='Auftragsbestätigung PDF'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Besteller Name'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_vat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='USt-ID des Kunden'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lieferkosten'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='verp_settings.deliveryterm', verbose_name='Lieferbedingung'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='delivery_time_weeks',
            field=models.PositiveIntegerField(default=0, verbose_name='Lieferzeit (Wochen)'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='order_notes',
            field=models.TextField(blank=True, verbose_name='Bemerkungen für Kunden'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='verp_settings.paymentterm', verbose_name='Zahlungsbedingung'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='sales.quotation', verbose_name='Angebot'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='tax_enabled',
            field=models.BooleanField(default=True, verbose_name='MwSt aktiviert'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='MwSt-Satz (%)'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='warranty_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='verp_settings.warrantyterm', verbose_name='Garantiebedingung'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='delivery_note_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Lieferschein-Nr.'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabatt %'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='invoice_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Rechnung-Nr.'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Geliefert'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='Berechnet'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EK-Preis'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='quotation_position',
            field=models.PositiveIntegerField(default=0, verbose_name='Angebotsposition'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Seriennummer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_document',
            field=models.FileField(blank=True, null=True, upload_to=customer_orders.models.customer_order_document_upload_path, verbose_name='Kunden-Bestelldokument'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kunden-Bestellnummer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lieferdatum'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Interne Bemerkungen'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Auftragsdatum'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='project_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Projekt-Referenz'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='shipping_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Lieferadresse'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('angelegt', 'Angelegt'), ('bestaetigt', 'Bestätigt'), ('in_produktion', 'In Produktion'), ('geliefert', 'Geliefert'), ('berechnet', 'Berechnet'), ('bezahlt', 'Bezahlt'), ('abgeschlossen', 'Abgeschlossen'), ('storniert', 'Storniert')], default='angelegt', max_length=30),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='system_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='System-Referenz'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='article_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='VS-Artikelnummer'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Währung'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Endpreis'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Listenpreis (VK)'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Artikelname'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='customerorderitem',
            name='unit',
            field=models.CharField(default='Stück', max_length=50, verbose_name='Einheit'),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(max_length=20, unique=True, verbose_name='Lieferschein-Nr.')),
                ('sequence_number', models.PositiveIntegerField(default=1, verbose_name='Laufende Nr.')),
                ('shipping_address', models.JSONField(blank=True, null=True, verbose_name='Lieferadresse')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Lieferdatum')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Versanddatum')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=customer_orders.models.delivery_note_upload_path, verbose_name='PDF')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking-Nr.')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Versanddienstleister')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='customer_orders.customerorder')),
            ],
            options={
                'verbose_name': 'Lieferschein',
                'verbose_name_plural': 'Lieferscheine',
                'ordering': ['order', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Rechnungs-Nr.')),
                ('sequence_number', models.PositiveIntegerField(default=1, verbose_name='Laufende Nr.')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('overdue', 'Überfällig'), ('cancelled', 'Storniert')], default='draft', max_length=20)),
                ('billing_address', models.JSONField(blank=True, null=True, verbose_name='Rechnungsadresse')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Rechnungsdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Netto')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MwSt')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Brutto')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=customer_orders.models.invoice_upload_path, verbose_name='PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer_orders.customerorder')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['order', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('payment_date', models.DateField(verbose_name='Zahlungsdatum')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Überweisung'), ('credit_card', 'Kreditkarte'), ('paypal', 'PayPal'), ('cash', 'Bar'), ('other', 'Sonstige')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Referenz/Verwendungszweck')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer_orders.invoice')),
            ],
            options={
                'verbose_name': 'Zahlungseingang',
                'verbose_name_plural': 'Zahlungseingänge',
                'ordering': ['-payment_date'],
            },
        ),
    ]
