# Generated by Django 5.0 on 2025-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0004_alter_customerorderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='tax_included',
            field=models.BooleanField(default=False, verbose_name='MwSt in Preisen enthalten'),
        ),
    ]
