# Generated by Django 5.0 on 2025-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0005_customerorder_tax_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_notes_text',
            field=models.TextField(blank=True, verbose_name='Lieferhinweise'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='production_notes',
            field=models.TextField(blank=True, verbose_name='Produktions-Hinweise'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gruppen-ID'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='is_group_header',
            field=models.BooleanField(default=False, verbose_name='Ist Gruppen-Header'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='position_display',
            field=models.CharField(blank=True, max_length=20, verbose_name='Positionsanzeige'),
        ),
    ]
