# Generated by Django 5.0 on 2025-12-30 18:16

import customer_orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0008_add_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='xrechnung_file',
            field=models.FileField(blank=True, null=True, upload_to=customer_orders.models.invoice_upload_path, verbose_name='XRechnung XML'),
        ),
    ]
