# Generated by Django 5.0 on 2026-01-11 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0009_add_xrechnung_file'),
        ('users', '0029_user_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderCommissionRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Prozentualer Anteil an der Gesamtprovision (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Provisionsanteil (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_recipients', to='customer_orders.customerorder', verbose_name='Kundenauftrag')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_assignments', to='users.employee', verbose_name='Provisionsempfänger')),
            ],
            options={
                'verbose_name': 'Provisionsempfänger',
                'verbose_name_plural': 'Provisionsempfänger',
                'ordering': ['-created_at'],
                'unique_together': {('customer_order', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='Geschäftsjahr')),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Berechneter Provisionsbetrag in €', max_digits=10, verbose_name='Provisionsbetrag')),
                ('order_net_total', models.DecimalField(decimal_places=2, help_text='Netto-Gesamtbetrag des Auftrags als Berechnungsgrundlage', max_digits=10, verbose_name='Auftrags-Netto-Gesamt')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Provisionssatz des Mitarbeiters zum Zeitpunkt der Berechnung', max_digits=5, verbose_name='Provisionssatz (%)')),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Prozentualer Anteil des Mitarbeiters an diesem Auftrag', max_digits=5, verbose_name='Provisionsanteil (%)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Berechnet am')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='customer_orders.customerorder', verbose_name='Kundenauftrag')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='users.employee', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Mitarbeiterprovision',
                'verbose_name_plural': 'Mitarbeiterprovisionen',
                'ordering': ['-fiscal_year', '-calculated_at'],
                'unique_together': {('employee', 'customer_order')},
            },
        ),
    ]
