# Generated by Django 5.0 on 2026-01-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0010_customerordercommissionrecipient_employeecommission'),
        ('manufacturing', '0005_productionorder_observers'),
        ('orders', '0015_order_offer_document'),
        ('suppliers', '0021_supplierattachment_and_more'),
        ('visiview', '0013_alter_visiviewlicensehistory_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderitem',
            name='hardware_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_items', to='manufacturing.productionorder', verbose_name='Hardware Fertigungsauftrag'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='procurement_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('ordered', 'Bestellt'), ('in_production', 'In Fertigung'), ('completed', 'Abgeschlossen')], default='pending', max_length=30, verbose_name='Beschaffungsstatus'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_items', to='suppliers.supplier', verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='supplier_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_items', to='orders.order', verbose_name='Lieferantenbestellung'),
        ),
        migrations.AddField(
            model_name='customerorderitem',
            name='visiview_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order_items', to='visiview.visiviewproductionorder', verbose_name='VisiView Fertigungsauftrag'),
        ),
    ]
