# Generated by Django 5.0 on 2026-02-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0011_add_procurement_fields'),
        ('customers', '0008_add_customer_legacy_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='legacy_adressen_id',
            field=models.IntegerField(blank=True, help_text='Originale AdressenID aus der SQL-Datenbank', null=True, verbose_name='Legacy AdressenID'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='legacy_customer_address',
            field=models.TextField(blank=True, help_text='Vollständige Adresse aus der Legacy-Datenbank', verbose_name='Legacy Kundenadresse'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='legacy_customer_company',
            field=models.CharField(blank=True, help_text='Firma/Universität aus der Legacy-Datenbank', max_length=300, verbose_name='Legacy Firma/Uni'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='legacy_customer_name',
            field=models.CharField(blank=True, help_text='Name des Kunden aus der Legacy-Datenbank', max_length=200, verbose_name='Legacy Kundenname'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Verknüpfter VERP-Kunde (kann bei Legacy-Aufträgen leer sein)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='customers.customer', verbose_name='Kunde'),
        ),
    ]
