# Generated by Django 5.0 on 2026-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0012_customerorder_legacy_adressen_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderitem',
            name='quotation_position',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Position aus dem zugeordneten Angebot (null bei Legacy-Aufträgen)', null=True, verbose_name='Angebotsposition'),
        ),
    ]
