# Generated by Django 5.0 on 2026-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0013_make_quotation_position_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='legacy_auftrags_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Originale AuftragsID aus der SQL-Datenbank', null=True, verbose_name='Legacy AuftragsID'),
        ),
    ]
