# Generated by Django 5.0 on 2025-12-24 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0013_remove_orderitem_asset'),
        ('suppliers', '0017_delete_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=100, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=500, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gelieferte Menge')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einkaufspreis pro Stück')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('item_function', models.CharField(choices=[('TRADING_GOOD', 'Handelsware'), ('STORAGE', 'Lager'), ('MS', 'Material & Supplies')], default='TRADING_GOOD', max_length=20, verbose_name='Warenfunktion')),
                ('item_category', models.CharField(blank=True, help_text='Abhängig von Warenfunktion: z.B. Software, Mikroskope für Trading Good; Rohstoff, Hilfsstoff, Betriebsstoff für M&S', max_length=50, verbose_name='Warenkategorie')),
                ('serial_number', models.CharField(blank=True, help_text='Für Trading Good und Storage erforderlich; nicht für M&S Kategorien', max_length=100, verbose_name='Seriennummer')),
                ('order_number', models.CharField(max_length=20, verbose_name='Bestellnummer')),
                ('customer_order_number', models.CharField(blank=True, max_length=100, verbose_name='Kundenauftragsnummer')),
                ('management_info', models.JSONField(blank=True, default=dict, help_text='Projekt, System, etc.', null=True, verbose_name='Management Info')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='Ins Lager überführt')),
                ('transferred_at', models.DateTimeField(blank=True, null=True, verbose_name='Überführt am')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Empfangen am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_goods_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('material_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.materialsupply', verbose_name='Material Supply')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_goods', to='orders.orderitem', verbose_name='Bestellposition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Lieferant')),
                ('trading_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.tradingproduct', verbose_name='Trading Product')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_incoming_goods', to=settings.AUTH_USER_MODEL, verbose_name='Überführt von')),
            ],
            options={
                'verbose_name': 'Wareneingang',
                'verbose_name_plural': 'Wareneingänge',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(editable=False, help_text='Format: I-00001', max_length=10, unique=True, verbose_name='Inventarnummer')),
                ('article_number', models.CharField(max_length=100, verbose_name='Lieferanten-Artikelnummer')),
                ('visitron_part_number', models.CharField(blank=True, max_length=100, verbose_name='Visitron-Artikelnummer')),
                ('name', models.CharField(max_length=500, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_function', models.CharField(choices=[('TRADING_GOOD', 'Handelsware'), ('STORAGE', 'Lager'), ('MS', 'Material & Supplies')], max_length=20, verbose_name='Warenfunktion')),
                ('item_category', models.CharField(max_length=50, verbose_name='Warenkategorie')),
                ('serial_number', models.CharField(blank=True, help_text='Für einzelne Instanzen (Trading Good, Storage)', max_length=100, verbose_name='Seriennummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Anzahl für Waren ohne Seriennummer', max_digits=10, verbose_name='Stückzahl')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einkaufspreis pro Stück')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('order_number', models.CharField(max_length=20, verbose_name='Bestellnummer')),
                ('customer_order_number', models.CharField(blank=True, max_length=100, verbose_name='Kundenauftragsnummer')),
                ('management_info', models.JSONField(blank=True, default=dict, help_text='Projekt, System, Kunde, etc.', null=True, verbose_name='Management Info')),
                ('status', models.CharField(choices=[('AUF_LAGER', 'Auf Lager'), ('RMA', 'RMA'), ('BEI_KUNDE', 'Bei Kunde')], default='AUF_LAGER', max_length=20, verbose_name='Status')),
                ('stored_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingelagert am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('material_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.materialsupply', verbose_name='Material Supply')),
                ('stored_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items_stored', to=settings.AUTH_USER_MODEL, verbose_name='Eingelagert von')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='suppliers.supplier', verbose_name='Lieferant')),
                ('trading_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.tradingproduct', verbose_name='Trading Product')),
            ],
            options={
                'verbose_name': 'Lagerartikel',
                'verbose_name_plural': 'Lagerartikel',
                'ordering': ['-stored_at'],
                'indexes': [models.Index(fields=['inventory_number'], name='inventory_i_invento_f42bd7_idx'), models.Index(fields=['article_number'], name='inventory_i_article_537e9a_idx'), models.Index(fields=['visitron_part_number'], name='inventory_i_visitro_670853_idx'), models.Index(fields=['serial_number'], name='inventory_i_serial__203210_idx'), models.Index(fields=['status'], name='inventory_i_status_77888d_idx'), models.Index(fields=['item_function'], name='inventory_i_item_fu_ef4386_idx'), models.Index(fields=['item_category'], name='inventory_i_item_ca_9109fd_idx')],
            },
        ),
    ]
