# Generated by Django 5.0 on 2025-12-28 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_map_item_function_values'),
        ('orders', '0014_order_incoming_recorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incominggoods',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_goods', to='orders.orderitem', verbose_name='Bestellposition'),
        ),
    ]
