# Generated by Django 5.0 on 2025-12-29 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0003_customerorder_vat_id'),
        ('customers', '0002_customersystem'),
        ('inventory', '0004_change_order_item_on_delete'),
        ('orders', '0014_order_incoming_recorded'),
        ('projects', '0001_initial'),
        ('systems', '0001_initial'),
        ('verp_settings', '0006_add_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incominggoods',
            name='model_designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modellbezeichnung'),
        ),
        migrations.AddField(
            model_name='incominggoods',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_goods', to='verp_settings.productcategory', verbose_name='Warenkategorie'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='customers.customer', verbose_name='Kunde'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Für manuelle Eingabe falls kein Kunde im System', max_length=200, verbose_name='Kundenname'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='customer_orders.customerorder', verbose_name='Kundenauftrag'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='equipment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Kategorie-spezifische Ausstattung/Zubehör', null=True, verbose_name='Ausstattungsdaten'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='firmware_notes',
            field=models.TextField(blank=True, verbose_name='Firmware-Notizen'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Firmware-Version'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='model_designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modellbezeichnung'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='orders.order', verbose_name='Bestellung'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='verp_settings.productcategory', verbose_name='Warenkategorie'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='projects.project', verbose_name='Projekt'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Projektnummer'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qm_data',
            field=models.JSONField(blank=True, default=dict, help_text='Kategorie-spezifische Qualitätsprüfungen', null=True, verbose_name='QM-Daten'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='systems.system', verbose_name='System'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='system_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Systemnummer'),
        ),
        migrations.AlterField(
            model_name='incominggoods',
            name='item_category',
            field=models.CharField(blank=True, help_text='Abhängig von Warenfunktion: z.B. Software, Mikroskope für Trading Good; Rohstoff, Hilfsstoff, Betriebsstoff für M&S', max_length=50, verbose_name='Warenkategorie (Legacy)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Warenkategorie (Legacy)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='management_info',
            field=models.JSONField(blank=True, default=dict, help_text='Projekt, System, Kunde, etc.', null=True, verbose_name='Management Info (Legacy)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bestellnummer'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='visitron_part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='VS-Artikelnummer'),
        ),
    ]
