# Generated by Django 5.0 on 2026-01-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_inventory_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='outgoing_checks',
            field=models.JSONField(blank=True, default=dict, help_text='Allgemeine Ausgangschecks für Warenausgang', null=True, verbose_name='Ausgangschecks'),
        ),
    ]
