# Generated by Django 5.0 on 2026-01-06 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_outgoing_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reservation_reason',
            field=models.TextField(blank=True, verbose_name='Reservierungsgrund'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Reserviert durch'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reserved_until',
            field=models.DateField(blank=True, null=True, verbose_name='Reserviert bis'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('FREI', 'Frei'), ('RESERVIERT', 'Reserviert'), ('GELIEFERT', 'Geliefert'), ('RMA_IN_HOUSE', 'RMA in house'), ('RMA_OUT_HOUSE', 'RMA out house')], default='FREI', max_length=20, verbose_name='Status'),
        ),
    ]
