# Generated by Django 5.0 on 2026-01-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_reservation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Datum der Warenlieferung', null=True, verbose_name='Lieferdatum'),
        ),
    ]
