# Generated by Django 5.0 on 2026-02-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='production_checklist_data',
            field=models.JSONField(blank=True, default=dict, help_text='Kategorie-spezifische Fertigungscheckliste (aus ChecklistTemplate)', null=True, verbose_name='Fertigungscheckliste'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='outgoing_checks',
            field=models.JSONField(blank=True, default=dict, help_text='Kategorie-spezifische Ausgangscheckliste (aus ChecklistTemplate)', null=True, verbose_name='Ausgangschecks'),
        ),
    ]
