# Generated by Django 5.0 on 2026-09-29
# Adds provenance fields for the Excel warehouse sync (sync_inventory_from_excel).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryitem_production_checklist_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='source_file',
            field=models.CharField(blank=True, default='', help_text='Name der Excel-/CSV-Datei, aus der der Artikel importiert wurde', max_length=255, verbose_name='Quelldatei'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, help_text='Zeilennummer in der Quelldatei (inkl. Kopfzeile)', null=True, verbose_name='Quellzeile'),
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-stored_at'], 'verbose_name': 'Lagerartikel', 'verbose_name_plural': 'Lagerartikel'},
        ),
    ]
