# Generated by Django 5.0 on 2025-12-20 18:47

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customers', '0001_initial'),
        ('verp_settings', '0005_populate_incoterms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert', max_length=20, null=True, unique=True, verbose_name='Angebotsnummer')),
                ('project_reference', models.CharField(blank=True, help_text='Interne Projekt-Zuordnung (erscheint nicht im Angebot)', max_length=200, verbose_name='Projekt-Referenz')),
                ('system_reference', models.CharField(blank=True, help_text='Interne System-Zuordnung (erscheint nicht im Angebot)', max_length=200, verbose_name='System-Referenz')),
                ('reference', models.CharField(blank=True, help_text='Erscheint im Angebot', max_length=200, verbose_name='Angebotsreferenz')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Angebotsdatum')),
                ('valid_until', models.DateField(verbose_name='Gültig bis')),
                ('delivery_time_weeks', models.PositiveIntegerField(default=0, verbose_name='Lieferzeit (Wochen)')),
                ('status', models.CharField(choices=[('DRAFT', 'In Arbeit'), ('ACTIVE', 'Aktiv'), ('EXPIRED', 'Abgelaufen'), ('ORDERED', 'Bestellt')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('language', models.CharField(choices=[('DE', 'Deutsch'), ('EN', 'English')], default='DE', max_length=2, verbose_name='Sprache')),
                ('show_terms_conditions', models.BooleanField(default=True, verbose_name='AGB-Hinweis anzeigen')),
                ('recipient_company', models.CharField(blank=True, max_length=200, verbose_name='Empfänger Firma')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Empfänger Name')),
                ('recipient_street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('recipient_postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('recipient_city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('recipient_country', models.CharField(blank=True, default='DE', max_length=2, verbose_name='Land')),
                ('notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('quotation_document', models.FileField(blank=True, null=True, upload_to=sales.models.quotation_document_upload_path, verbose_name='Angebotsdokument')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer', verbose_name='Kunde')),
                ('delivery_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='verp_settings.deliveryinstruction', verbose_name='Lieferanweisung')),
                ('delivery_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='verp_settings.deliveryterm', verbose_name='Lieferbedingung (Incoterm)')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='verp_settings.paymentterm', verbose_name='Zahlungsbedingung')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-date', '-quotation_number'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('description_type', models.CharField(choices=[('SHORT', 'Kurzbeschreibung'), ('LONG', 'Langbeschreibung')], default='SHORT', max_length=10, verbose_name='Beschreibungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabatt (%)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='MwSt. (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Positions-Notizen')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'suppliers'), ('model', 'tradingproduct')), models.Q(('app_label', 'suppliers'), ('model', 'asset')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation', verbose_name='Angebot')),
            ],
            options={
                'verbose_name': 'Angebotsposition',
                'verbose_name_plural': 'Angebotspositionen',
                'ordering': ['quotation', 'position'],
            },
        ),
    ]
