# Generated by Django 5.0 on 2025-12-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='delivery_instruction',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_document',
        ),
    ]
