# Generated by Django 5.0 on 2025-12-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='group_id',
            field=models.CharField(blank=True, help_text='Für Warensammlungen - alle Items mit gleicher group_id gehören zusammen', max_length=50, null=True, verbose_name='Gruppen-ID'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='group_name',
            field=models.CharField(blank=True, help_text='Name der Warensammlung (nur für Gruppen-Header)', max_length=200, verbose_name='Gruppenname'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='is_group_header',
            field=models.BooleanField(default=False, help_text='True wenn dies die Haupt-Position einer Warensammlung ist', verbose_name='Ist Gruppen-Header'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='pricing_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Einzelpreis'), ('SYSTEM', 'Systempreis')], default='INDIVIDUAL', help_text='Einzelpreis oder zum Systempreis gehörig', max_length=20, verbose_name='Preistyp'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Für Marge-Berechnung', max_digits=10, verbose_name='Einkaufspreis'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='system_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gesamtpreis für System/Gruppe', max_digits=10, null=True, verbose_name='Systempreis'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'suppliers'), ('model', 'tradingproduct')), models.Q(('app_label', 'suppliers'), ('model', 'asset')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (Verkauf)'),
        ),
    ]
