# Generated by Django 5.0 on 2025-12-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_group_and_system_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='system_price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='system_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Systempreis für Positionen die auf Systempreis gesetzt sind', max_digits=10, null=True, verbose_name='Systempreis'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wird bei Gruppen aus Summe der Listenpreise berechnet, kann manuell angepasst werden', max_digits=10, null=True, verbose_name='Verkaufspreis'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='uses_system_price',
            field=models.BooleanField(default=False, help_text='Wenn True, wird der Systempreis des Angebots verwendet statt dem Verkaufspreis', verbose_name='Verwendet Systempreis'),
        ),
    ]
