# Generated by Django 5.0 on 2025-12-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_quotationitem_pricing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='commission_user',
            field=models.ForeignKey(blank=True, help_text='Mitarbeiter der die Provision erhält', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_commission', to=settings.AUTH_USER_MODEL, verbose_name='Provisionsempfänger'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_enabled',
            field=models.BooleanField(default=True, help_text='MwSt auf alle Positionen anwenden', verbose_name='MwSt aktiviert'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=19, help_text='Globaler MwSt-Satz für das Angebot', max_digits=5, verbose_name='MwSt-Satz (%)'),
        ),
    ]
