# Generated by Django 5.0 on 2025-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quotation_commission_user_quotation_tax_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lieferkosten werden zur Nettosumme addiert vor MwSt-Berechnung', max_digits=10, verbose_name='Lieferkosten'),
        ),
    ]
