# Generated by Django 5.0 on 2025-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_quotation_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='item_article_number',
            field=models.CharField(blank=True, help_text='Automatisch generiert für Warensammlungen (Format: 100-WS00001)', max_length=20, verbose_name='Visitron Artikelnummer'),
        ),
    ]
