# Generated by Django 5.0 on 2025-12-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_quotationitem_item_article_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='show_group_item_prices',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, werden die Preise der einzelnen Artikel in Warensammlungen angezeigt', verbose_name='Preise von Gruppen-Artikeln anzeigen'),
        ),
    ]
