# Generated by Django 5.0 on 2025-12-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0008_add_show_group_item_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'suppliers'), ('model', 'tradingproduct')), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
