# Generated by Django 5.0 on 2025-12-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_quotationitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='custom_description',
            field=models.TextField(blank=True, help_text='Editierbare Beschreibung für das Angebot (wird aus Produktbeschreibung geladen)', verbose_name='Beschreibungstext'),
        ),
    ]
