# Generated by Django 5.0 on 2025-12-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0010_add_custom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='description_text',
            field=models.TextField(blank=True, help_text='Einleitender Text der über den Positionen erscheint', verbose_name='Angebotsbeschreibung'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Text der unter den Konditionen im PDF erscheint', verbose_name='Fußtext'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Gespeichertes PDF des Angebots', null=True, upload_to='quotations/%Y/', verbose_name='PDF Datei'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'In Arbeit'), ('SENT', 'Verschickt'), ('ACTIVE', 'Aktiv'), ('EXPIRED', 'Abgelaufen'), ('ORDERED', 'Bestellt')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'suppliers'), ('model', 'tradingproduct')), models.Q(('app_label', 'visiview'), ('model', 'visiviewproduct')), models.Q(('app_label', 'manufacturing'), ('model', 'vshardware')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
