# Generated by Django 5.0 on 2025-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_add_quotation_description_footer_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Angebotsdatum'),
        ),
    ]
