# Generated by Django 5.0 on 2026-01-05 09:08

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_marketingitem_marketingitemfile'),
        ('users', '0025_vacationyearbalance_vacationadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketingitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Marketing-Material', 'verbose_name_plural': 'Marketing-Materialien'},
        ),
        migrations.AlterModelOptions(
            name='marketingitemfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Marketing-Datei', 'verbose_name_plural': 'Marketing-Dateien'},
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='category',
            field=models.CharField(choices=[('newsletter', 'Newsletter'), ('appnote', 'AppNote'), ('technote', 'TechNote'), ('brochure', 'Broschüre'), ('show', 'Show'), ('workshop', 'Workshop')], max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_items', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Nur für Shows und Workshops', null=True, verbose_name='Veranstaltungsdatum'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='event_location',
            field=models.CharField(blank=True, help_text='Nur für Shows und Workshops', max_length=300, verbose_name='Veranstaltungsort'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='responsible_employees',
            field=models.ManyToManyField(blank=True, related_name='marketing_items', to='users.employee', verbose_name='Zuständige Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='marketingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Content-Type'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='file',
            field=models.FileField(upload_to=sales.models.marketing_item_upload_path, verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='Dateiname'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='marketing_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sales.marketingitem', verbose_name='Marketing-Material'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am'),
        ),
        migrations.AlterField(
            model_name='marketingitemfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_file_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von'),
        ),
    ]
