# Generated by Django 5.0 on 2026-01-05 10:01

import core.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_marketingitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingitemfile',
            name='file',
            field=models.FileField(upload_to=core.upload_paths.marketing_upload_path, verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Gespeichertes PDF des Angebots', null=True, upload_to=core.upload_paths.quotation_upload_path, verbose_name='PDF Datei'),
        ),
        migrations.CreateModel(
            name='SalesTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ticketnummer')),
                ('category', models.CharField(choices=[('appnote', 'AppNote'), ('technote', 'TechNote'), ('usermanual', 'User Manual'), ('fieldservicemanual', 'Field Service Manual'), ('brochure', 'Broschüre'), ('newsletter', 'Newsletter'), ('trainingvideo', 'Training Video'), ('marketingvideo', 'Marketing Video'), ('helparticle', 'Helpeintrag'), ('marketresearch', 'Markterkundung')], max_length=30, verbose_name='Kategorie')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('assigned', 'Zugewiesen'), ('in_progress', 'In Bearbeitung'), ('review', 'Review'), ('completed', 'Erledigt'), ('rejected', 'Abgelehnt')], default='new', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Avisiertes Abgabedatum')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Abschlussdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Sales-Ticket',
                'verbose_name_plural': 'Sales-Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Sales/Sales-Tickets/', verbose_name='Datei')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file_size', models.IntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sales.salesticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Sales-Ticket Anhang',
                'verbose_name_plural': 'Sales-Ticket Anhänge',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sales.salesticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Sales-Ticket Kommentar',
                'verbose_name_plural': 'Sales-Ticket Kommentare',
                'ordering': ['created_at'],
            },
        ),
    ]
