# Generated by Django 5.0 on 2026-01-05 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_marketingitemfile_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='sales_tickets_watching', to=settings.AUTH_USER_MODEL, verbose_name='Beobachter'),
        ),
        migrations.CreateModel(
            name='SalesTicketChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Geändertes Feld')),
                ('old_value', models.TextField(blank=True, verbose_name='Alter Wert')),
                ('new_value', models.TextField(blank=True, verbose_name='Neuer Wert')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_ticket_changes', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.salesticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Sales-Ticket Änderung',
                'verbose_name_plural': 'Sales-Ticket Änderungen',
                'ordering': ['-changed_at'],
            },
        ),
    ]
