# Generated by Django 5.0 on 2026-01-07 15:25

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_salesticket_watchers_salesticketchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesticketattachment',
            name='file',
            field=models.FileField(upload_to=core.upload_paths.sales_ticket_attachment_path, verbose_name='Datei'),
        ),
    ]
