# Generated by Django 5.0 on 2026-01-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_salesticketattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='recipient_salutation',
            field=models.CharField(blank=True, help_text='Anrede des Empfängers (z.B. Herr, Frau)', max_length=20, verbose_name='Empfänger Anrede'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='recipient_title',
            field=models.CharField(blank=True, help_text='Titel des Empfängers (z.B. Dr., Prof.)', max_length=50, verbose_name='Empfänger Titel'),
        ),
    ]
