# Generated by Django 5.0 on 2026-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_quotation_recipient_salutation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesticket',
            name='redmine_id',
            field=models.IntegerField(blank=True, help_text='ID des Tickets im Redmine-System', null=True, unique=True, verbose_name='Redmine Issue ID'),
        ),
        migrations.AddField(
            model_name='salesticket',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Redmine Aktualisiert am'),
        ),
    ]
