# Generated by Django 5.0 on 2026-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_add_redmine_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingitemfile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Sales/Marketing/thumbnails/', verbose_name='Vorschaubild'),
        ),
    ]
