# Generated by Django 5.0 on 2026-04-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_add_customer_legacy_mapping'),
        ('sales', '0020_add_thumbnail_to_marketingitemfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Allgemeine Anmerkungen zur Veranstaltung', verbose_name='Allgemeiner Kommentar')),
                ('conclusion', models.TextField(blank=True, help_text='Fazit / Zusammenfassung der Veranstaltung', verbose_name='Fazit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_event_reports', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('marketing_item', models.OneToOneField(limit_choices_to={'category__in': ['show', 'workshop']}, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='sales.marketingitem', verbose_name='Veranstaltung')),
            ],
            options={
                'verbose_name': 'Veranstaltungsbericht',
                'verbose_name_plural': 'Veranstaltungsberichte',
            },
        ),
        migrations.CreateModel(
            name='EventReportLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Ort')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('has_purchase_interest', models.BooleanField(default=False, verbose_name='Konkretes Kaufinteresse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_leads', to='customers.customer', verbose_name='Kunde (optional)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='sales.eventreport', verbose_name='Bericht')),
            ],
            options={
                'verbose_name': 'Teilnehmer/Lead',
                'verbose_name_plural': 'Teilnehmer/Leads',
                'ordering': ['name'],
            },
        ),
    ]
