# Generated by Django 5.0 on 2025-12-31 12:44

import django.db.models.deletion
import pricelists.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0019_tradingproduct_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist_type', models.CharField(choices=[('vs_hardware', 'VS-Hardware'), ('visiview', 'VisiView'), ('trading', 'Trading Products'), ('vs_service', 'VS-Service'), ('combined', 'Combined Price List')], max_length=20, verbose_name='Preislistentyp')),
                ('include_vs_hardware', models.BooleanField(default=False, verbose_name='VS-Hardware einschließen')),
                ('include_visiview', models.BooleanField(default=False, verbose_name='VisiView einschließen')),
                ('include_trading', models.BooleanField(default=False, verbose_name='Trading Products einschließen')),
                ('include_vs_service', models.BooleanField(default=False, verbose_name='VS-Service einschließen')),
                ('valid_from_month', models.PositiveSmallIntegerField(help_text='Monat (1-12)', verbose_name='Gültig ab Monat')),
                ('valid_from_year', models.PositiveSmallIntegerField(verbose_name='Gültig ab Jahr')),
                ('valid_until_month', models.PositiveSmallIntegerField(help_text='Monat (1-12)', verbose_name='Gültig bis Monat')),
                ('valid_until_year', models.PositiveSmallIntegerField(verbose_name='Gültig bis Jahr')),
                ('subtitle', models.CharField(blank=True, help_text='Optionaler Untertitel für die Preisliste', max_length=200, verbose_name='Untertitel')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=pricelists.models.pricelist_upload_path, verbose_name='PDF-Datei')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelists_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('supplier', models.ForeignKey(blank=True, help_text='Nur bei Trading Products: Filter nach Lieferant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_pricelists', to='suppliers.supplier', verbose_name='Lieferant')),
                ('trading_supplier', models.ForeignKey(blank=True, help_text='Lieferant für Trading Products im Combined-Modus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_pricelists', to='suppliers.supplier', verbose_name='Trading Products Lieferant')),
            ],
            options={
                'verbose_name': 'Verkaufs-Preisliste',
                'verbose_name_plural': 'Verkaufs-Preislisten',
                'ordering': ['-valid_from_year', '-valid_from_month', 'pricelist_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='salespricelist',
            constraint=models.CheckConstraint(check=models.Q(('valid_from_month__gte', 1), ('valid_from_month__lte', 12)), name='valid_from_month_range'),
        ),
        migrations.AddConstraint(
            model_name='salespricelist',
            constraint=models.CheckConstraint(check=models.Q(('valid_until_month__gte', 1), ('valid_until_month__lte', 12)), name='valid_until_month_range'),
        ),
    ]
