# Generated by Django 5.0 on 2025-12-31 12:11

import dealers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0012_alter_quotation_date_field'),
        ('service', '0003_serviceticket_linked_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_number', models.CharField(blank=True, editable=False, help_text='Automatisch generierte Händlernummer im Format H-00001', max_length=10, null=True, unique=True, verbose_name='Händlernummer')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('address_supplement', models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Bundesland/Region')),
                ('country', models.CharField(default='DE', max_length=2, verbose_name='Land')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Inaktiv')], default='active', max_length=20, verbose_name='Status')),
                ('dealer_discount', models.DecimalField(decimal_places=2, default=0, help_text='Standard-Rabatt für diesen Händler in Prozent', max_digits=5, verbose_name='Händlerrabatt (%)')),
                ('payment_terms', models.CharField(choices=[('prepayment', 'Vorkasse'), ('net_14', '14 Tage netto'), ('net_30', '30 Tage netto'), ('net_60', '60 Tage netto'), ('net_90', '90 Tage netto')], default='net_30', max_length=50, verbose_name='Zahlungskonditionen')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('language', models.CharField(choices=[('DE', 'Deutsch'), ('EN', 'English'), ('FR', 'Français'), ('ES', 'Español'), ('IT', 'Italiano')], default='DE', max_length=2, verbose_name='Sprache')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Händler',
                'verbose_name_plural': 'Händler',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='DealerCustomerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, help_text='Name des Endkunden (falls bekannt)', max_length=200, verbose_name='Kundenname')),
                ('customer_street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('customer_house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('customer_postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('customer_city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('customer_country', models.CharField(blank=True, default='DE', max_length=2, verbose_name='Land')),
                ('visiview_license_id', models.CharField(blank=True, help_text='Vierstellige VisiView Lizenz-ID (falls zutreffend)', max_length=10, verbose_name='VisiView Lizenz-ID')),
                ('system_hardware', models.TextField(blank=True, help_text='Beschreibung der Hardware beim Endkunden', verbose_name='Kundensystem-Hardware')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_systems', to='dealers.dealer', verbose_name='Händler')),
            ],
            options={
                'verbose_name': 'Dealer-Kundensystem',
                'verbose_name_plural': 'Dealer-Kundensysteme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerCustomerSystemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('service', 'Service-Ticket'), ('visiview', 'VisiView-Ticket')], default='service', max_length=20, verbose_name='Ticket-Typ')),
                ('ticket_reference', models.CharField(blank=True, help_text='Manuelle Ticket-Nummer falls nicht im System', max_length=100, verbose_name='Ticket-Referenz')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('dealer_customer_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='dealers.dealercustomersystem', verbose_name='Dealer-Kundensystem')),
                ('service_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_customer_system_links', to='service.serviceticket', verbose_name='Service-Ticket')),
            ],
            options={
                'verbose_name': 'Dealer-Kundensystem-Ticket',
                'verbose_name_plural': 'Dealer-Kundensystem-Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Vertrag'), ('agreement', 'Vereinbarung'), ('certificate', 'Zertifikat'), ('other', 'Sonstiges')], default='other', max_length=50, verbose_name='Dokumenttyp')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('file', models.FileField(upload_to=dealers.models.dealer_document_upload_path, verbose_name='Datei')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dealers.dealer', verbose_name='Händler')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Händler-Dokument',
                'verbose_name_plural': 'Händler-Dokumente',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, choices=[('Herr', 'Herr'), ('Frau', 'Frau'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], max_length=20, verbose_name='Anrede')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Titel')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('language', models.CharField(choices=[('DE', 'Deutsch'), ('EN', 'English'), ('FR', 'Français'), ('ES', 'Español'), ('IT', 'Italiano')], default='DE', max_length=2, verbose_name='Sprache')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobil')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Land')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptansprechpartner')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dealers.dealer', verbose_name='Händler')),
            ],
            options={
                'verbose_name': 'Händler-Mitarbeiter',
                'verbose_name_plural': 'Händler-Mitarbeiter',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DealerPriceListLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricelist_type', models.CharField(choices=[('vs_hardware', 'VS-Hardware Preisliste'), ('visiview', 'VisiView Produkte Preisliste'), ('combined', 'Kombinierte Preisliste'), ('custom', 'Individuelle Preisliste')], max_length=50, verbose_name='Preislisten-Typ')),
                ('sent_date', models.DateField(verbose_name='Versanddatum')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('file', models.FileField(blank=True, null=True, upload_to=dealers.models.dealer_document_upload_path, verbose_name='Preislisten-Datei')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricelist_logs', to='dealers.dealer', verbose_name='Händler')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von')),
            ],
            options={
                'verbose_name': 'Preislisten-Protokoll',
                'verbose_name_plural': 'Preislisten-Protokolle',
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='DealerQuotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, help_text='Wird automatisch vom Angebot übernommen oder manuell eingegeben', max_length=50, verbose_name='Angebotsnummer')),
                ('sent_date', models.DateField(verbose_name='Versanddatum')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Betreff')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_logs', to='dealers.dealer', verbose_name='Händler')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_logs', to='sales.quotation', verbose_name='Angebot')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gesendet von')),
            ],
            options={
                'verbose_name': 'Angebots-Protokoll',
                'verbose_name_plural': 'Angebots-Protokolle',
                'ordering': ['-sent_date'],
            },
        ),
    ]
