# Generated by Django 5.0 on 2025-12-31 13:23

import django.db.models.deletion
import loans.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0019_tradingproduct_description_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format L-00001', max_length=10, null=True, unique=True, verbose_name='Leihnummer')),
                ('status', models.CharField(choices=[('angefragt', 'Angefragt'), ('entliehen', 'Entliehen'), ('abgeschlossen', 'Abgeschlossen')], default='angefragt', max_length=20, verbose_name='Status')),
                ('request_date', models.DateField(help_text='Wann wurde die Leihung angefragt?', verbose_name='Anfragedatum')),
                ('return_deadline', models.DateField(help_text='Bis wann muss die Ware zurückgesendet werden?', verbose_name='Rückgabetermin')),
                ('return_address_name', models.CharField(help_text='Name/Firma für Rücksendung', max_length=200, verbose_name='Empfänger')),
                ('return_address_street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('return_address_house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('return_address_postal_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('return_address_city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('return_address_country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('supplier_reference', models.CharField(blank=True, help_text='Referenznummer/Auftragsnummer des Lieferanten', max_length=100, verbose_name='Lieferanten-Referenz')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='suppliers.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Leihung',
                'verbose_name_plural': 'Leihungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('product_name', models.CharField(max_length=200, verbose_name='Warenname')),
                ('supplier_article_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer Lieferant')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(default='Stück', max_length=20, verbose_name='Einheit')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loan', verbose_name='Leihung')),
            ],
            options={
                'verbose_name': 'Leihposition',
                'verbose_name_plural': 'Leihpositionen',
                'ordering': ['loan', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LoanItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=loans.models.loan_item_photo_path, verbose_name='Foto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='loans.loanitem', verbose_name='Leihposition')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['loan_item', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanItemReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False, help_text='Alle Teile/Zubehör vorhanden?', verbose_name='Vollständig')),
                ('is_intact', models.BooleanField(default=False, help_text='Keine Beschädigungen?', verbose_name='Intakt')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_check', to='loans.loanitem', verbose_name='Leihposition')),
            ],
            options={
                'verbose_name': 'Positions-Checkliste',
                'verbose_name_plural': 'Positions-Checklisten',
            },
        ),
        migrations.CreateModel(
            name='LoanReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='Wareneingangsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen zum Wareneingang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='loans.loan', verbose_name='Leihung')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_receipts_received', to=settings.AUTH_USER_MODEL, verbose_name='Entgegengenommen von')),
            ],
            options={
                'verbose_name': 'Wareneingang',
                'verbose_name_plural': 'Wareneingänge',
            },
        ),
        migrations.CreateModel(
            name='LoanReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert', max_length=20, null=True, unique=True, verbose_name='Rücklieferschein-Nr.')),
                ('return_date', models.DateField(verbose_name='Rücksendedatum')),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, verbose_name='Versanddienstleister')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Sendungsnummer')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=loans.models.loan_upload_path, verbose_name='Rücklieferschein PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_returns_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='loans.loan', verbose_name='Leihung')),
            ],
            options={
                'verbose_name': 'Rücksendung',
                'verbose_name_plural': 'Rücksendungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rückgesendete Menge')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Zustand bei Rücksendung')),
                ('loan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='loans.loanitem', verbose_name='Leihposition')),
                ('loan_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loanreturn', verbose_name='Rücksendung')),
            ],
            options={
                'verbose_name': 'Rücksendungsposition',
                'verbose_name_plural': 'Rücksendungspositionen',
            },
        ),
    ]
