# Generated by Django 5.0 on 2025-12-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_deadline',
            field=models.DateField(blank=True, help_text='Bis wann muss die Ware zurückgesendet werden?', null=True, verbose_name='Rückgabetermin'),
        ),
    ]
