# Generated by Django 5.0 on 2025-12-31 14:12

import loans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_return_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanreceipt',
            name='delivery_note',
            field=models.FileField(blank=True, help_text='Lieferschein des Lieferanten als PDF/Bild', null=True, upload_to=loans.models.loan_receipt_document_path, verbose_name='Lieferschein'),
        ),
        migrations.AddField(
            model_name='loanreceipt',
            name='loan_agreement',
            field=models.FileField(blank=True, help_text='Unterschriebene Leihvereinbarung als PDF/Bild', null=True, upload_to=loans.models.loan_receipt_document_path, verbose_name='Leihvereinbarung'),
        ),
    ]
