# Generated by Django 5.0 on 2026-01-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanreceipt_delivery_note_loanreceipt_loan_agreement'),
        ('users', '0024_add_reminder_notification_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observed_loans', to='users.employee', verbose_name='Beobachter'),
        ),
        migrations.AddField(
            model_name='loan',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_loans', to='users.employee', verbose_name='Zuständiger Mitarbeiter'),
        ),
    ]
