# Generated by Django 5.0 on 2026-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_observers_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanreturn',
            name='pdf_language',
            field=models.CharField(blank=True, choices=[('DE', 'Deutsch'), ('EN', 'Englisch')], default='DE', max_length=2, verbose_name='Sprache des Rücklieferscheins'),
        ),
    ]
