# Generated by Django 5.0 on 2026-10-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_model_organisms_customer_research_fields_and_more'),
        ('loans', '0006_loanreturn_pdf_language'),
        ('suppliers', '0021_supplierattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender_customer',
            field=models.ForeignKey(blank=True, help_text='Nur wenn als Gegenpartei "Kunde" gewählt ist', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_loans_as_lender', to='customers.customer', verbose_name='Kunde als Gegenpartei'),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender_type',
            field=models.CharField(choices=[('supplier', 'Lieferant'), ('customer', 'Kunde')], default='supplier', help_text='Von wem wird geliehen? Lieferant oder Kunde', max_length=10, verbose_name='Gegenpartei'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='suppliers.supplier', verbose_name='Lieferant'),
        ),
    ]
