# Generated by Django 5.0 on 2026-10-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('loans', '0007_loan_lender_customer_loan_lender_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='lender_distributor_employee',
            field=models.ForeignKey(blank=True, help_text='Nur wenn als Gegenpartei "Distributormitarbeiter" gewählt ist', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_loans_as_lender', to='dealers.dealeremployee', verbose_name='Distributormitarbeiter als Gegenpartei'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='lender_type',
            field=models.CharField(choices=[('supplier', 'Lieferant'), ('customer', 'Kunde'), ('distributor_employee', 'Distributormitarbeiter')], default='supplier', help_text='Von wem wird geliehen? Lieferant, Kunde oder Distributormitarbeiter', max_length=24, verbose_name='Gegenpartei'),
        ),
    ]
