# Generated by Django 5.0 on 2025-12-29 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verp_settings', '0006_add_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiViewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format VV-00001', max_length=10, null=True, unique=True, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_products_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_products', to='verp_settings.productcategory', verbose_name='Warenkategorie')),
            ],
            options={
                'verbose_name': 'VisiView Produkt',
                'verbose_name_plural': 'VisiView Produkte',
                'ordering': ['article_number'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Einkaufspreis in EUR', max_digits=12, verbose_name='Einkaufspreis (EK)')),
                ('list_price', models.DecimalField(decimal_places=2, help_text='Listenpreis für Angebote in EUR', max_digits=12, verbose_name='Listenpreis (LP)')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, help_text='Leer = unbegrenzt gültig', null=True, verbose_name='Gültig bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_prices_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='visiview.visiviewproduct', verbose_name='VisiView Produkt')),
            ],
            options={
                'verbose_name': 'VisiView Preis',
                'verbose_name_plural': 'VisiView Preise',
                'ordering': ['product', '-valid_from'],
            },
        ),
    ]
