# Generated by Django 5.0 on 2026-01-01 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_advertising_status_customer_description_and_more'),
        ('visiview', '0002_visiviewproduct_description_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiViewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit_position', models.IntegerField(help_text='Position im Options-Bitfeld (0-63)', unique=True, verbose_name='Bit-Position')),
                ('name', models.CharField(max_length=100, verbose_name='Optionsname')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Listenpreis (EUR)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'VisiView Option',
                'verbose_name_plural': 'VisiView Optionen',
                'ordering': ['bit_position'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(help_text='Automatisch generiert: L-00001', max_length=20, unique=True, verbose_name='Lizenznummer')),
                ('serial_number', models.CharField(help_text='Dongle-Seriennummer', max_length=50, unique=True, verbose_name='Seriennummer (Dongle)')),
                ('internal_serial', models.CharField(blank=True, help_text='Interne Dongle-ID (z.B. 0x7)', max_length=50, verbose_name='Interne Seriennummer')),
                ('customer_name_legacy', models.CharField(blank=True, help_text='Importierter Kundenname vor Verknüpfung', max_length=200, verbose_name='Kundenname (Import)')),
                ('customer_address_legacy', models.CharField(blank=True, help_text='Importierte Adresse vor Verknüpfung', max_length=500, verbose_name='Kundenadresse (Import)')),
                ('distributor', models.CharField(blank=True, max_length=200, verbose_name='Distributor')),
                ('version', models.CharField(blank=True, max_length=20, verbose_name='Version')),
                ('options_bitmask', models.BigIntegerField(default=0, help_text='Bitfeld für freigeschaltete Optionen', verbose_name='Optionen (Bitmaske)')),
                ('options_upper_32bit', models.IntegerField(default=0, help_text='Obere 32-bit für Optionen 32-63', verbose_name='Optionen (Upper 32-bit)')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Lieferdatum')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Ablaufdatum')),
                ('maintenance_date', models.DateField(blank=True, null=True, verbose_name='Wartung bis')),
                ('purchase_order', models.CharField(blank=True, max_length=100, verbose_name='Bestellnummer')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('demo', 'Demo'), ('loaner', 'Leihgerät'), ('returned', 'Zurückgegeben'), ('cancelled', 'Storniert'), ('defect', 'Defekt'), ('lost', 'Verloren')], default='active', max_length=20, verbose_name='Status')),
                ('is_demo', models.BooleanField(default=False, verbose_name='Demo')),
                ('is_loaner', models.BooleanField(default=False, verbose_name='Leihgerät')),
                ('is_defect', models.BooleanField(default=False, verbose_name='Defekt')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Zurückgegeben')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Storniert')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Verloren')),
                ('is_outdated', models.BooleanField(default=False, verbose_name='Veraltet')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Rückgabedatum')),
                ('demo_options', models.BigIntegerField(default=0, verbose_name='Demo-Optionen')),
                ('demo_options_expire_date', models.DateField(blank=True, null=True, verbose_name='Demo-Optionen Ablauf')),
                ('dongle_batch_id', models.IntegerField(blank=True, null=True, verbose_name='Dongle Batch ID')),
                ('dongle_version', models.IntegerField(default=1, verbose_name='Dongle Version')),
                ('dongle_mod_count', models.IntegerField(default=0, verbose_name='Dongle Änderungszähler')),
                ('support_end', models.DateField(blank=True, null=True, verbose_name='Support Ende')),
                ('support_warning', models.BooleanField(default=False, verbose_name='Support-Warnung')),
                ('info', models.TextField(blank=True, verbose_name='Info/Notizen')),
                ('todo', models.TextField(blank=True, verbose_name='To-Do')),
                ('legacy_id', models.IntegerField(blank=True, help_text='Original-ID aus CSV-Import', null=True, verbose_name='Legacy ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_licenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_licenses', to='customers.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'VisiView Lizenz',
                'verbose_name_plural': 'VisiView Lizenzen',
                'ordering': ['-serial_number'],
            },
        ),
    ]
