# Generated by Django 5.0 on 2026-01-02 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0003_visiviewoption_visiviewlicense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiViewTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Vierstellige Ticket-Nummer (z.B. 4874)', max_length=10, unique=True, verbose_name='Ticket-Nummer')),
                ('tracker', models.CharField(choices=[('bug', 'Bug/Fehler'), ('feature', 'Feature Request')], default='bug', max_length=20, verbose_name='Tracker')),
                ('title', models.CharField(max_length=500, verbose_name='Thema')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('assigned', 'Zugewiesen'), ('in_progress', 'Bearbeitet'), ('testing', 'Testen: Extern'), ('tested', 'Getestet'), ('resolved', 'Gelöst'), ('closed', 'Geschlossen'), ('rejected', 'Abgelehnt')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('normal', 'Normal'), ('high', 'Hoch'), ('urgent', 'Dringend'), ('immediate', 'Sofort')], default='normal', max_length=20, verbose_name='Priorität')),
                ('category', models.CharField(blank=True, choices=[('application', 'Applikation'), ('data_analysis', 'Datenanalyse Allgemein'), ('data_management', 'Datenmanagement'), ('deconvolution', 'Deconvolution'), ('hardware_camera', 'Hardware: Kamera'), ('hardware_microscope', 'Hardware: Mikroskop'), ('hardware_orbital', 'Hardware: Orbital'), ('hardware_tirf_frap', 'Hardware: VisiTIRF/FRAP'), ('hardware_other', 'Hardware: Sonstiges'), ('other', 'Sonstiges')], max_length=50, verbose_name='Kategorie')),
                ('author', models.CharField(blank=True, help_text='Name des Ticket-Erstellers', max_length=200, verbose_name='Autor')),
                ('assigned_to_name', models.CharField(blank=True, help_text='Importierter Name falls kein User zugeordnet', max_length=200, verbose_name='Zugewiesen an (Name)')),
                ('last_changed_by', models.CharField(blank=True, max_length=200, verbose_name='Zuletzt geändert von')),
                ('target_version', models.CharField(blank=True, help_text='z.B. VV 7.0.0.10', max_length=50, verbose_name='Zielversion')),
                ('affected_version', models.CharField(blank=True, max_length=50, verbose_name='Betroffene Version')),
                ('visiview_id', models.CharField(blank=True, help_text='z.B. VV 2040', max_length=50, verbose_name='VisiView ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Beginn')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Abgabedatum')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Geschätzter Aufwand (h)')),
                ('total_estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Summe geschätzter Aufwand (h)')),
                ('spent_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aufgewendete Zeit (h)')),
                ('percent_done', models.IntegerField(default=0, verbose_name='% erledigt')),
                ('customers', models.TextField(blank=True, help_text='Betroffene Kunden (kommasepariert)', verbose_name='Kunden')),
                ('attachments', models.TextField(blank=True, help_text='Angehängte Dateien', verbose_name='Dateien')),
                ('related_tickets', models.TextField(blank=True, help_text='Verknüpfte Ticket-Nummern', verbose_name='Zugehörige Tickets')),
                ('is_private', models.BooleanField(default=False, verbose_name='Privat')),
                ('add_to_worklist', models.BooleanField(default=False, verbose_name='Add to Worklist')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Rank')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geschlossen am')),
                ('imported_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Angelegt (Import)')),
                ('imported_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktualisiert (Import)')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_tickets_authored', to=settings.AUTH_USER_MODEL, verbose_name='Autor (User)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('parent_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tickets', to='visiview.visiviewticket', verbose_name='Übergeordnetes Ticket')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_visiview_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Beobachter')),
            ],
            options={
                'verbose_name': 'VisiView Ticket',
                'verbose_name_plural': 'VisiView Tickets',
                'ordering': ['-ticket_number'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewTicketChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Feld')),
                ('old_value', models.TextField(blank=True, verbose_name='Alter Wert')),
                ('new_value', models.TextField(blank=True, verbose_name='Neuer Wert')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_ticket_changes', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='visiview.visiviewticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'VisiView Ticket Änderung',
                'verbose_name_plural': 'VisiView Ticket Änderungen',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewTicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Importiert')),
                ('created_by_name', models.CharField(blank=True, help_text='Importierter Name falls kein User zugeordnet', max_length=200, verbose_name='Erstellt von (Name)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='visiview.visiviewticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'VisiView Ticket Kommentar',
                'verbose_name_plural': 'VisiView Ticket Kommentare',
                'ordering': ['-created_at'],
            },
        ),
    ]
