# Generated by Django 5.0 on 2026-01-02 13:14

import django.db.models.deletion
import visiview.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0004_visiview_tickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiViewMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_id', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format M-00001', max_length=10, null=True, unique=True, verbose_name='Macro-ID')),
                ('title', models.CharField(help_text='Titel des Macros', max_length=200, verbose_name='Titel')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('visiview_version', models.CharField(blank=True, help_text='z.B. VV 7.0.0.10', max_length=50, verbose_name='VisiView Version')),
                ('purpose', models.TextField(blank=True, help_text='Beschreibung wofür das Macro gut ist', verbose_name='Zweck')),
                ('usage', models.TextField(blank=True, help_text='Beschreibung wie das Macro anzuwenden ist (Schritt für Schritt)', verbose_name='Anwendung')),
                ('code', models.TextField(blank=True, help_text='Python-Code des Macros', verbose_name='Macro Code')),
                ('keywords', models.CharField(blank=True, help_text='Kommaseparierte Schlüsselwörter für die Suche', max_length=500, verbose_name='Keywords')),
                ('category', models.CharField(blank=True, help_text='Kategorie oder Ordner des Macros', max_length=200, verbose_name='Kategorie')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('released', 'Freigegeben'), ('deprecated', 'Veraltet')], default='new', max_length=20, verbose_name='Status')),
                ('changelog', models.TextField(blank=True, help_text='Änderungshistorie des Macros', verbose_name='Changelog')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original Dateiname')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_macros_authored', to=settings.AUTH_USER_MODEL, verbose_name='Autor (User)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_macros_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Andere Macros, die für dieses Macro benötigt werden', related_name='dependent_macros', to='visiview.visiviewmacro', verbose_name='Abhängigkeiten')),
            ],
            options={
                'verbose_name': 'VisiView Macro',
                'verbose_name_plural': 'VisiView Macros',
                'ordering': ['-macro_id'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewMacroChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Version')),
                ('description', models.TextField(verbose_name='Änderungsbeschreibung')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_macro_changes', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('macro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='visiview.visiviewmacro', verbose_name='Macro')),
            ],
            options={
                'verbose_name': 'Macro Änderung',
                'verbose_name_plural': 'Macro Änderungen',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewMacroExampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=visiview.models.macro_example_upload_path, verbose_name='Bild')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Beschreibung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('macro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_images', to='visiview.visiviewmacro', verbose_name='Macro')),
            ],
            options={
                'verbose_name': 'Macro Beispielbild',
                'verbose_name_plural': 'Macro Beispielbilder',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
