# Generated by Django 5.0 on 2026-01-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0005_visiviewmacro_visiviewmacrochangelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiviewticket',
            name='visiview_license',
            field=models.ForeignKey(blank=True, help_text='Verknüpfte VisiView-Lizenz (Dongle-Seriennummer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_tickets', to='visiview.visiviewlicense', verbose_name='VisiView Lizenz'),
        ),
    ]
