# Generated by Django 5.0 on 2026-01-04 13:04

import core.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0006_visiviewticket_visiview_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiviewticket',
            name='attachments',
        ),
        migrations.AddField(
            model_name='visiviewticket',
            name='attachment_notes',
            field=models.TextField(blank=True, help_text='Notizen zu angehängten Dateien (Altsystem)', verbose_name='Datei-Notizen'),
        ),
        migrations.CreateModel(
            name='VisiViewTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.upload_paths.visiview_ticket_attachment_path, verbose_name='Datei')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='visiview.visiviewticket', verbose_name='Ticket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_ticket_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'VisiView-Ticket Anhang',
                'verbose_name_plural': 'VisiView-Ticket Anhänge',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
