# Generated by Django 5.0 on 2026-01-04 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0007_remove_visiviewticket_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiViewTicketTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('time', models.TimeField(verbose_name='Uhrzeit')),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aufgewendete Stunden')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_time_entries_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='visiview.visiviewticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'VisiView-Ticket Zeiteintrag',
                'verbose_name_plural': 'VisiView-Ticket Zeiteinträge',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
