# Generated by Django 5.0 on 2026-01-04 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0008_visiviewtickettimeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTimeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Beginn-Datum')),
                ('end_date', models.DateField(verbose_name='Ende-Datum')),
                ('credit_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Zeitgutschrift (h)')),
                ('remaining_hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rest-Zeitgutschrift (h)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_credits_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_credits', to='visiview.visiviewlicense', verbose_name='Lizenz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_credits_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Wartungs-Zeitgutschrift',
                'verbose_name_plural': 'Wartungs-Zeitgutschriften',
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTimeExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit')),
                ('activity', models.CharField(choices=[('email_support', 'Email Support'), ('remote_support', 'Remote Support'), ('phone_support', 'Telefon Support')], max_length=20, verbose_name='Aktivität')),
                ('task_type', models.CharField(choices=[('training', 'Schulung'), ('testing', 'Test'), ('bugs', 'Bugs'), ('other', 'Sonstiges')], max_length=20, verbose_name='Tätigkeit')),
                ('hours_spent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aufgewendete Zeit (h)')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('is_goodwill', models.BooleanField(default=False, verbose_name='Kulanz')),
                ('created_debt', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Erzeugte Zeitschuld (h)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_expenditures_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('deducted_from_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditures', to='visiview.maintenancetimecredit', verbose_name='Abgezogen von')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_expenditures', to='visiview.visiviewlicense', verbose_name='Lizenz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_expenditures_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Wartungs-Zeitaufwendung',
                'verbose_name_plural': 'Wartungs-Zeitaufwendungen',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
