# Generated by Django 5.0 on 2026-01-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0009_maintenancetimecredit_maintenancetimeexpenditure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancetimeexpenditure',
            name='deducted_from_credit',
        ),
        migrations.CreateModel(
            name='MaintenanceTimeCreditDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_deducted', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Abgezogene Stunden (h)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='visiview.maintenancetimecredit', verbose_name='Zeitgutschrift')),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='visiview.maintenancetimeexpenditure', verbose_name='Zeitaufwendung')),
            ],
            options={
                'verbose_name': 'Gutschrift-Abzug',
                'verbose_name_plural': 'Gutschrift-Abzüge',
                'ordering': ['created_at'],
            },
        ),
    ]
