# Generated by Django 5.0 on 2026-01-05 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0010_remove_maintenancetimeexpenditure_deducted_from_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, help_text='Optional: Interne Referenznummer', max_length=50, verbose_name='Rechnungsnummer')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Zeitraum von')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Zeitraum bis')),
                ('pdf_file', models.FileField(upload_to='VisiView/Lizenzen/', verbose_name='PDF-Datei')),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Zeitgutschriften (h)')),
                ('total_expenditures', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Zeitaufwendungen (h)')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Saldo (h)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_invoices_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_invoices', to='visiview.visiviewlicense', verbose_name='Lizenz')),
            ],
            options={
                'verbose_name': 'Maintenance-Abrechnung',
                'verbose_name_plural': 'Maintenance-Abrechnungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
