# Generated by Django 5.0 on 2026-01-14 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_orders', '0010_customerordercommissionrecipient_employeecommission'),
        ('customers', '0005_customer_advertising_status_customer_description_and_more'),
        ('visiview', '0011_maintenanceinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiViewProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Automatisch generiert: VVP-00001', max_length=20, unique=True, verbose_name='Auftragsnummer')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_PROGRESS', 'In Bearbeitung'), ('COMPLETED', 'Abgeschlossen'), ('CANCELLED', 'Storniert')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('processing_type', models.CharField(blank=True, choices=[('NEW_LICENSE', 'Neue Lizenz'), ('EXTEND_LICENSE', 'Lizenz erweitern'), ('MAINTENANCE_CREDIT', 'Maintenance-Gutschrift')], max_length=30, null=True, verbose_name='Bearbeitungsart')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_production_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visiview_production_orders', to='customers.customer', verbose_name='Kunde')),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visiview_production_orders', to='customer_orders.customerorder', verbose_name='Kundenauftrag')),
                ('target_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='visiview.visiviewlicense', verbose_name='Ziel-Lizenz')),
            ],
            options={
                'verbose_name': 'VisiView Fertigungsauftrag',
                'verbose_name_plural': 'VisiView Fertigungsaufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewLicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CREATED', 'Lizenz erstellt'), ('OPTION_ADDED', 'Option hinzugefügt'), ('OPTION_REMOVED', 'Option entfernt'), ('MAINTENANCE_EXTENDED', 'Maintenance verlängert'), ('STATUS_CHANGED', 'Status geändert'), ('CUSTOMER_CHANGED', 'Kunde geändert'), ('OTHER', 'Sonstige Änderung')], max_length=30, verbose_name='Änderungstyp')),
                ('description', models.TextField(help_text='Detaillierte Beschreibung der Änderung', verbose_name='Beschreibung')),
                ('old_value', models.TextField(blank=True, verbose_name='Alter Wert')),
                ('new_value', models.TextField(blank=True, verbose_name='Neuer Wert')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Geändert am')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_license_changes', to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='visiview.visiviewlicense', verbose_name='Lizenz')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_changes', to='visiview.visiviewproductionorder', verbose_name='Fertigungsauftrag')),
            ],
            options={
                'verbose_name': 'Lizenz-Änderungsprotokoll',
                'verbose_name_plural': 'Lizenz-Änderungsprotokolle',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VisiViewProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_months', models.IntegerField(blank=True, null=True, verbose_name='Maintenance-Monate')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('customer_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visiview_production_items', to='customer_orders.customerorderitem', verbose_name='Auftragsposition')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='visiview.visiviewproductionorder', verbose_name='Fertigungsauftrag')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='production_order_items', to='visiview.visiviewoption', verbose_name='Ausgewählte Optionen')),
            ],
            options={
                'verbose_name': 'VisiView Fertigungsauftrags-Position',
                'verbose_name_plural': 'VisiView Fertigungsauftrags-Positionen',
            },
        ),
    ]
