# Generated by Django 5.0 on 2026-01-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0012_visiviewproductionorder_visiviewlicensehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiviewlicensehistory',
            name='change_type',
            field=models.CharField(choices=[('CREATED', 'Lizenz erstellt'), ('OPTION_ADDED', 'Option hinzugefügt'), ('OPTION_REMOVED', 'Option entfernt'), ('MAINTENANCE_EXTENDED', 'Maintenance verlängert'), ('MAJOR_VERSION_UPDATE', 'Major Version Update'), ('STATUS_CHANGED', 'Status geändert'), ('CUSTOMER_CHANGED', 'Kunde geändert'), ('OTHER', 'Sonstige Änderung')], max_length=30, verbose_name='Änderungstyp'),
        ),
    ]
