# Generated by Django 5.0 on 2026-02-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_add_responsible_employee_and_sales_territory'),
        ('visiview', '0013_alter_visiviewlicensehistory_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiviewticket',
            name='linked_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_tickets', to='systems.system', verbose_name='Verknüpftes System'),
        ),
    ]
