# Generated by Django 5.0 on 2026-02-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0014_add_linked_system_to_visiviewticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Camera', 'Camera'), ('Microscope', 'Microscope'), ('Hardware Autofocus', 'Hardware Autofocus'), ('Light source', 'Light source'), ('Controller', 'Controller'), ('Filterwheel', 'Filterwheel'), ('Component', 'Component'), ('Computer hardware', 'Computer hardware'), ('Accessory', 'Accessory')], max_length=50, verbose_name='Kategorie')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Hersteller')),
                ('device', models.CharField(max_length=200, verbose_name='Gerät')),
                ('driver_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Treiber Name')),
                ('driver_version', models.CharField(blank=True, default='', max_length=100, verbose_name='Treiber Version')),
                ('visiview_version', models.CharField(blank=True, default='', max_length=100, verbose_name='VisiView Version')),
                ('limitations', models.TextField(blank=True, default='', verbose_name='Einschränkungen')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Kommentar')),
                ('required_visiview_option', models.CharField(blank=True, default='', max_length=200, verbose_name='Benötigte VisiView Option')),
                ('support_level', models.CharField(blank=True, choices=[('Official Support', 'Official Support'), ('Tested by Visitron', 'Tested by Visitron'), ('Untested, driver provided by manufacturer', 'Untested, driver provided by manufacturer'), ('Basic Support', 'Basic Support'), ('Experimental', 'Experimental'), ('Third-party driver', 'Third-party driver'), ('Discontinued', 'Discontinued')], default='', max_length=100, verbose_name='Support Level')),
                ('service_status', models.CharField(blank=True, default='', max_length=100, verbose_name='Service Status (Hersteller)')),
                ('data_quality', models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Verified', 'Verified'), ('Incomplete', 'Incomplete'), ('Needs review', 'Needs review')], default='', max_length=50, verbose_name='Datenqualität')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='Autor')),
                ('actualization_date', models.DateField(blank=True, null=True, verbose_name='Aktualisierungsdatum')),
                ('dual_cam', models.BooleanField(default=False, verbose_name='Dual Cam')),
                ('device_streaming', models.BooleanField(default=False, verbose_name='Device Streaming')),
                ('virtex', models.BooleanField(default=False, verbose_name='Virtex')),
                ('splitview', models.BooleanField(default=False, verbose_name='Splitview')),
                ('xy_support', models.BooleanField(default=False, verbose_name='XY Support')),
                ('z_support', models.BooleanField(default=False, verbose_name='Z Support')),
                ('objective_support', models.BooleanField(default=False, verbose_name='Objective Support')),
                ('beam_path_support', models.BooleanField(default=False, verbose_name='Beam path Support')),
                ('light_support', models.BooleanField(default=False, verbose_name='Light Support')),
                ('ttl_shutter', models.BooleanField(default=False, verbose_name='TTL Shutter')),
                ('sw_shutter', models.BooleanField(default=False, verbose_name='SW Shutter')),
                ('analog_intensity', models.BooleanField(default=False, verbose_name='Analog Intensity')),
                ('sw_intensity', models.BooleanField(default=False, verbose_name='SW Intensity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_hardware_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Unterstützte Hardware',
                'verbose_name_plural': 'Unterstützte Hardware',
                'ordering': ['category', 'manufacturer', 'device'],
                'indexes': [models.Index(fields=['category'], name='visiview_su_categor_4348e3_idx'), models.Index(fields=['manufacturer'], name='visiview_su_manufac_c38b9a_idx'), models.Index(fields=['support_level'], name='visiview_su_support_01f09c_idx')],
            },
        ),
    ]
