# Generated by Django 5.0 on 2026-02-05 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_add_contact_history'),
        ('systems', '0008_change_status_choices'),
        ('visiview', '0015_supportedhardware'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedHardwareUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('visiview_version', models.CharField(blank=True, default='', max_length=100, verbose_name='VisiView Version')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_use_cases_created', to=settings.AUTH_USER_MODEL, verbose_name='Eingetragen von')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_use_cases', to='customers.customer', verbose_name='Kunde')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='visiview.supportedhardware', verbose_name='Hardware')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_use_cases', to='visiview.visiviewlicense', verbose_name='VisiView Lizenz')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_use_cases', to='systems.system', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Hardware Use Case',
                'verbose_name_plural': 'Hardware Use Cases',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
