# Generated by Django 5.0 on 2026-02-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0016_supportedhardwareusecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedhardwareusecase',
            name='device_firmware',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Geräte Firmware'),
        ),
        migrations.AddField(
            model_name='supportedhardwareusecase',
            name='driver_version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Treiber Version'),
        ),
    ]
