# Generated by Django 5.0 on 2026-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0017_add_usecase_driver_firmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedhardware',
            name='category',
            field=models.CharField(choices=[('Camera', 'Camera'), ('Microscope', 'Microscope'), ('Hardware Autofocus', 'Hardware Autofocus'), ('Light source', 'Light source'), ('Controller', 'Controller'), ('Filterwheel', 'Filterwheel'), ('Component', 'Component'), ('Computer hardware', 'Computer hardware'), ('Accessory', 'Accessory'), ('Illumination', 'Illumination'), ('Image Splitter', 'Image Splitter'), ('Shutter', 'Shutter'), ('Spinning Disk', 'Spinning Disk'), ('xy-stage', 'XY-Stage'), ('z-drive', 'Z-Drive'), ('Peripherals', 'Peripherals')], max_length=50, verbose_name='Kategorie'),
        ),
    ]
