# Generated by Django 5.0 on 2026-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0018_add_hardware_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetimecredit',
            name='redmine_id',
            field=models.IntegerField(blank=True, help_text='ID des Zeitgutschrift-Tickets im Redmine-System', null=True, unique=True, verbose_name='Redmine Issue ID'),
        ),
        migrations.AddField(
            model_name='maintenancetimecredit',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Redmine Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='maintenancetimeexpenditure',
            name='redmine_time_entry_id',
            field=models.IntegerField(blank=True, help_text='ID des Zeiteintrags im Redmine-System', null=True, unique=True, verbose_name='Redmine Time Entry ID'),
        ),
        migrations.AddField(
            model_name='visiviewticket',
            name='redmine_id',
            field=models.IntegerField(blank=True, help_text='ID des Tickets im Redmine-System', null=True, unique=True, verbose_name='Redmine Issue ID'),
        ),
        migrations.AddField(
            model_name='visiviewticket',
            name='redmine_updated_on',
            field=models.DateTimeField(blank=True, help_text='Letzter Aktualisierungszeitpunkt in Redmine', null=True, verbose_name='Redmine Aktualisiert am'),
        ),
        migrations.AddField(
            model_name='visiviewticketcomment',
            name='redmine_journal_id',
            field=models.IntegerField(blank=True, help_text='ID des Journals/Kommentars im Redmine-System', null=True, unique=True, verbose_name='Redmine Journal ID'),
        ),
    ]
