# Generated by Django 5.0 on 2026-02-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('visiview', '0019_add_redmine_sync_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visiviewlicense',
            old_name='distributor',
            new_name='distributor_legacy',
        ),
        migrations.AddField(
            model_name='visiviewlicense',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiview_licenses', to='dealers.dealer', verbose_name='Händler'),
        ),
    ]
