# Generated by Django 5.0 on 2026-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiview', '0020_remove_visiviewlicense_distributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiviewlicense',
            name='distributor_legacy',
            field=models.CharField(blank=True, help_text='Legacy: Importierter Distributor-Name als Text', max_length=200, verbose_name='Distributor (Import)'),
        ),
    ]
