# Generated by Django 5.0 on 2026-01-03 07:55

import django.db.models.deletion
import procurement.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('suppliers', '0019_tradingproduct_description_en_and_more'),
        ('verp_settings', '0004_alter_productcategory_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format WS-00001', max_length=10, null=True, unique=True, verbose_name='Warensammlungsnummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel (Deutsch)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Titel (Englisch)')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Kurzbeschreibung (Deutsch)')),
                ('short_description_en', models.CharField(blank=True, max_length=500, verbose_name='Kurzbeschreibung (Englisch)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung (Deutsch)')),
                ('description_en', models.TextField(blank=True, verbose_name='Beschreibung (Englisch)')),
                ('product_source', models.CharField(choices=[('TRADING_GOODS', 'Trading Goods'), ('VS_SERVICE', 'VS-Service Produkte'), ('VISIVIEW', 'VisiView-Produkte'), ('VS_HARDWARE', 'VS-Hardware')], help_text='Aus welcher Produktdatenbank stammen die Positionen', max_length=20, verbose_name='Produktdatenbank')),
                ('total_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Summe der Einzel-Einkaufspreise', max_digits=12, verbose_name='Gesamt-Einkaufspreis')),
                ('total_list_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Summe der Visitron-Listenpreise', max_digits=12, verbose_name='Gesamt-Listenpreis')),
                ('price_valid_until', models.DateField(blank=True, help_text='Wird aus der kürzesten Gültigkeit der Positionen berechnet', null=True, verbose_name='Preis gültig bis')),
                ('quotation_text_short', models.TextField(blank=True, verbose_name='Angebotstext kurz (Deutsch)')),
                ('quotation_text_short_en', models.TextField(blank=True, verbose_name='Angebotstext kurz (Englisch)')),
                ('quotation_text_long', models.TextField(blank=True, verbose_name='Angebotstext lang (Deutsch)')),
                ('quotation_text_long_en', models.TextField(blank=True, verbose_name='Angebotstext lang (Englisch)')),
                ('manual', models.FileField(blank=True, help_text='Handbuch/Dokumentation zur Warensammlung', null=True, upload_to=procurement.models.product_collection_manual_upload_path, verbose_name='Manual')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_collections_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_collections', to='verp_settings.productcategory', verbose_name='Warenkategorie')),
                ('supplier', models.ForeignKey(blank=True, help_text='Erforderlich bei Trading Goods - nur ein Lieferant pro Sammlung', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_collections', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Warensammlung',
                'verbose_name_plural': 'Warensammlungen',
                'ordering': ['collection_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Position')),
                ('object_id', models.PositiveIntegerField(verbose_name='Produkt-ID')),
                ('article_number', models.CharField(max_length=100, verbose_name='Artikelnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Produktname (Englisch)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, verbose_name='Beschreibung (Englisch)')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('unit_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Einkaufspreis pro Einheit')),
                ('unit_list_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Listenpreis pro Einheit')),
                ('total_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gesamt-Einkaufspreis')),
                ('total_list_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gesamt-Listenpreis')),
                ('price_valid_until', models.DateField(blank=True, null=True, verbose_name='Preis gültig bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.productcollection', verbose_name='Warensammlung')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['tradingproduct', 'vsservice', 'visiviewproduct', 'vshardware']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Produkttyp')),
            ],
            options={
                'verbose_name': 'Warensammlungs-Position',
                'verbose_name_plural': 'Warensammlungs-Positionen',
                'ordering': ['collection', 'position'],
                'unique_together': {('collection', 'position')},
            },
        ),
    ]
