# Generated by Django 5.0 on 2026-01-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcollection',
            name='description',
            field=models.TextField(blank=True, max_length=20000, verbose_name='Beschreibung (Deutsch)'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='description_en',
            field=models.TextField(blank=True, max_length=20000, verbose_name='Beschreibung (Englisch)'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='short_description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Kurzbeschreibung (Deutsch)'),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Kurzbeschreibung (Englisch)'),
        ),
    ]
