# Generated by Django 5.0 on 2026-01-10 00:05

import core.upload_paths
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0020_alter_tradingproduct_release_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert im Format DEV-00001', max_length=15, null=True, unique=True, verbose_name='Projektnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Projektname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('in_progress', 'In Arbeit'), ('testing', 'Im Test'), ('paused', 'Pausiert'), ('completed', 'Abgeschlossen'), ('rejected', 'Abgelehnt')], default='new', max_length=20, verbose_name='Status')),
                ('project_start', models.DateField(auto_now_add=True, verbose_name='Projektbeginn')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='Geplantes Projektende')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_development_projects', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_development_projects', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Entwicklungsprojekt',
                'verbose_name_plural': 'Entwicklungsprojekte',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.upload_paths.development_project_attachment_path, verbose_name='Datei')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='development.developmentproject', verbose_name='Projekt')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_project_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Projekt-Anhang',
                'verbose_name_plural': 'Projekt-Anhänge',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_project_comments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='development.developmentproject', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projekt Kommentar',
                'verbose_name_plural': 'Projekt Kommentare',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectCostCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=100, verbose_name='Kalkulationsname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Arbeitsstunden')),
                ('labor_rate', models.DecimalField(decimal_places=2, default=Decimal('65.00'), max_digits=8, verbose_name='Stundensatz (EUR)')),
                ('development_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamtentwicklungskosten (EUR)')),
                ('expected_sales_volume', models.PositiveIntegerField(default=1, verbose_name='Erwarteter Absatz (Stück)')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Materialkosten (EUR)')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Arbeitskosten (EUR)')),
                ('development_cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Entwicklungskosten pro Stück (EUR)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamtkosten (EUR)')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_cost_calculations_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_calculations', to='development.developmentproject', verbose_name='Entwicklungsprojekt')),
            ],
            options={
                'verbose_name': 'Kostenkalkulation',
                'verbose_name_plural': 'Kostenkalkulationen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='Menge')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notizen')),
                ('material_supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_project_usages', to='suppliers.materialsupply', verbose_name='Material & Supply')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='development.developmentproject', verbose_name='Entwicklungsprojekt')),
            ],
            options={
                'verbose_name': 'Material-Position',
                'verbose_name_plural': 'Material-Positionen',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Datum der Arbeitsleistung', verbose_name='Datum')),
                ('time', models.TimeField(help_text='Uhrzeit der Arbeitsleistung', verbose_name='Uhrzeit')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Aufgewendete Zeit in Stunden (z.B. 2.5 für 2,5 Stunden)', max_digits=5, verbose_name='Aufgewendete Zeit (Stunden)')),
                ('description', models.TextField(help_text='Kurze Beschreibung der durchgeführten Arbeiten', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dev_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_project_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='development.developmentproject', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteinträge',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Aufgabe')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dev_todos', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='development.developmentproject', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDos',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
