# Generated by Django 5.0 on 2026-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentprojectmaterialitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Menge'),
        ),
    ]
