# Generated by Django 5.0 on 2026-03-03 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_alter_developmentprojectmaterialitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentproject',
            name='priority',
            field=models.CharField(choices=[('very_high', 'Sehr hoch'), ('high', 'Hoch'), ('normal', 'Normal'), ('low', 'Niedrig')], default='normal', max_length=20, verbose_name='Priorität'),
        ),
        migrations.AddField(
            model_name='developmentprojecttodo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dev_todos', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an'),
        ),
    ]
