# Generated by Django 5.0 on 2026-03-03 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_developmentproject_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProjectSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Beschreibender Titel der Quelle', max_length=200, verbose_name='Titel')),
                ('url', models.URLField(help_text='Link zur Quelle', max_length=500, verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Optionale Beschreibung oder Notizen zur Quelle', verbose_name='Beschreibung')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dev_sources', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='development.developmentproject', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Quelle',
                'verbose_name_plural': 'Quellen',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
