# Generated by Django 5.0 on 2026-04-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_developmentprojectsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentprojectcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
    ]
