# Generated by Django 5.0 on 2026-09-17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_developmentprojectcomment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentproject',
            name='project_start',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Projektbeginn'),
        ),
    ]
