# Generated by Django 5.0 on 2025-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_access_accounting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_customers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_hr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_manufacturing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_service',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_suppliers',
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_accounting',
            field=models.BooleanField(default=False, verbose_name='Buchhaltung - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_customers',
            field=models.BooleanField(default=False, verbose_name='Kunden - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_hr',
            field=models.BooleanField(default=False, verbose_name='HR - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_manufacturing',
            field=models.BooleanField(default=False, verbose_name='Produktion - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_service',
            field=models.BooleanField(default=False, verbose_name='Service - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_suppliers',
            field=models.BooleanField(default=False, verbose_name='Lieferanten - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_accounting',
            field=models.BooleanField(default=False, verbose_name='Buchhaltung - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_customers',
            field=models.BooleanField(default=False, verbose_name='Kunden - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_hr',
            field=models.BooleanField(default=False, verbose_name='HR - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_manufacturing',
            field=models.BooleanField(default=False, verbose_name='Produktion - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_service',
            field=models.BooleanField(default=False, verbose_name='Service - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_suppliers',
            field=models.BooleanField(default=False, verbose_name='Lieferanten - Schreiben'),
        ),
    ]
