# Generated by Django 5.0 on 2025-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_can_access_accounting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_settings',
            field=models.BooleanField(default=False, verbose_name='Einstellungen - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_settings',
            field=models.BooleanField(default=False, verbose_name='Einstellungen - Schreiben'),
        ),
    ]
