# Generated by Django 5.0 on 2025-12-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_read_settings_user_can_write_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Mitarbeiter-ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('date_of_birth', models.DateField(verbose_name='Geburtsdatum')),
                ('address', models.TextField(blank=True, verbose_name='Anschrift/Adresse')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Private E-Mail')),
                ('work_email', models.EmailField(blank=True, max_length=254, verbose_name='Dienstliche E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('employment_start_date', models.DateField(verbose_name='Eintrittsdatum')),
                ('employment_end_date', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('contract_type', models.CharField(choices=[('unbefristet', 'Unbefristet'), ('befristet', 'Befristet'), ('teilzeit', 'Teilzeit'), ('vollzeit', 'Vollzeit'), ('ausbildung', 'Ausbildung'), ('minijob', 'Minijob'), ('praktikum', 'Praktikum')], max_length=20, verbose_name='Vertragsart')),
                ('job_title', models.CharField(max_length=150, verbose_name='Stellenbezeichnung')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Abteilung')),
                ('working_time_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Beschäftigungsumfang (%)')),
                ('employment_status', models.CharField(choices=[('aktiv', 'Aktiv'), ('inaktiv', 'Inaktiv'), ('urlaub', 'Urlaub'), ('krank', 'Krank'), ('aufkündigung', 'Aufkündigung')], max_length=20, verbose_name='Beschäftigungsstatus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
