# Generated by Django 5.0 on 2025-12-21 18:30

from django.db import migrations, models


def generate_employee_ids(apps, schema_editor):
    Employee = apps.get_model('users', 'Employee')
    employees = Employee.objects.filter(employee_id='').order_by('id')
    for i, employee in enumerate(employees, start=1):
        employee.employee_id = f"EMP{i:03d}"
        employee.save(update_fields=['employee_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Mitarbeiter-ID'),
        ),
        migrations.RunPython(generate_employee_ids, migrations.RunPython.noop),
    ]
