# Generated by Django 5.0 on 2025-12-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_reminder_vacationrequest_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='break_time',
            field=models.CharField(default='00:30:00', max_length=20, verbose_name='Pausenzeit'),
        ),
    ]
