# Generated by Django 5.0 on 2025-12-22 12:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employee_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='weekly_work_hours',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5, verbose_name='Wochenarbeitszeit (h)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_days',
            field=models.JSONField(default=users.models.default_work_days, verbose_name='Arbeitstage'),
        ),
    ]
