# Generated by Django 5.0 on 2025-12-22 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_employee_weekly_work_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Monat')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Ist-Stunden')),
                ('expected_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Soll-Stunden')),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Differenz')),
                ('note', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_summaries', to='users.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monatliche Arbeitsübersicht',
                'verbose_name_plural': 'Monatliche Arbeitsübersichten',
                'ordering': ['-month'],
                'unique_together': {('employee', 'month'), ('user', 'month')},
            },
        ),
    ]
