# Generated by Django 5.0 on 2025-12-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_monthlyworksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_vacation_days',
            field=models.IntegerField(default=30, verbose_name='Jahresurlaubstage'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacation_balance',
            field=models.IntegerField(default=30, verbose_name='Urlaubskonto (Tage)'),
        ),
    ]
