# Generated by Django 5.0 on 2025-12-22 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employee_annual_vacation_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_vacation_days',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jahresurlaubstage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacation_balance',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=5, verbose_name='Urlaubskonto (Tage)'),
        ),
    ]
