# Generated by Django 5.0 on 2025-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_employee_annual_vacation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='end_half',
            field=models.CharField(choices=[('none', 'Kein Halbtag'), ('am', 'Vormittag'), ('pm', 'Nachmittag')], default='none', max_length=10, verbose_name='Ende als Halbtag'),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='start_half',
            field=models.CharField(choices=[('none', 'Kein Halbtag'), ('am', 'Vormittag'), ('pm', 'Nachmittag')], default='none', max_length=10, verbose_name='Beginn als Halbtag'),
        ),
    ]
