# Generated by Django 5.0 on 2025-12-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_add_app_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
