# Generated by Django 5.0 on 2025-12-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_read_assets',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_write_assets',
        ),
    ]
