# Generated by Django 5.0 on 2025-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_can_read_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='closing_greeting',
            field=models.CharField(blank=True, default='Mit freundlichen Grüßen', help_text='z.B. "Mit freundlichen Grüßen" oder "Best regards"', max_length=200, verbose_name='Grußformel'),
        ),
        migrations.AddField(
            model_name='employee',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Unterschriftsbild für Angebote und Dokumente (PNG/JPG)', null=True, upload_to='hr/signatures/', verbose_name='Unterschrift'),
        ),
    ]
