# Generated by Django 5.0 on 2025-12-30 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_add_employee_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpenseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Aufenthaltsort')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('per_diem_full', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tagespauschale (Vollständig)')),
                ('per_diem_partial', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tagespauschale (Teil)')),
                ('per_diem_applied', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Angewendete Pauschale')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Abfahrt')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Ankunft')),
                ('is_full_day', models.BooleanField(default=True, verbose_name='Ganztags')),
                ('overnight_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Übernachtungspauschale')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reisetag',
                'verbose_name_plural': 'Reisetage',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TravelPerDiemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True, verbose_name='Land')),
                ('country_code', models.CharField(blank=True, max_length=3, verbose_name='Ländercode')),
                ('full_day_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tagespauschale (24h)')),
                ('partial_day_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tagespauschale (>8h)')),
                ('overnight_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Übernachtungspauschale')),
                ('valid_from', models.DateField(verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reisekostenpauschale',
                'verbose_name_plural': 'Reisekostenpauschalen',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='TravelExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('transport', 'Transport'), ('hotel', 'Hotel'), ('parking', 'Parken'), ('shipping', 'Versand'), ('hospitality', 'Bewirtung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kostenart')),
                ('description', models.CharField(max_length=500, verbose_name='Beschreibung')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('guest_names', models.TextField(blank=True, verbose_name='Gastnamen')),
                ('hospitality_reason', models.TextField(blank=True, verbose_name='Bewirtungsgrund')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='myverp/travel_expenses/receipts/', verbose_name='Beleg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.travelexpenseday')),
            ],
            options={
                'verbose_name': 'Reisekostenposition',
                'verbose_name_plural': 'Reisekostenpositionen',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_week', models.PositiveIntegerField(verbose_name='Kalenderwoche')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('destination', models.CharField(max_length=200, verbose_name='Reiseziel')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('purpose', models.TextField(verbose_name='Reisezweck')),
                ('start_date', models.DateField(verbose_name='Reisebeginn')),
                ('end_date', models.DateField(verbose_name='Reiseende')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='draft', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gesamtbetrag')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='myverp/travel_expenses/', verbose_name='PDF-Datei')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_travel_expenses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_expense_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reisekostenabrechnung',
                'verbose_name_plural': 'Reisekostenabrechnungen',
                'ordering': ['-year', '-calendar_week'],
                'unique_together': {('user', 'calendar_week', 'year')},
            },
        ),
        migrations.AddField(
            model_name='travelexpenseday',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='users.travelexpensereport'),
        ),
        migrations.AlterUniqueTogether(
            name='travelexpenseday',
            unique_together={('report', 'date')},
        ),
    ]
