# Generated by Django 5.0 on 2025-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_travelexpenseday_travelperdiemrate_travelexpenseitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelexpenseday',
            name='travel_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Reisestunden'),
        ),
    ]
