# Generated by Django 5.0 on 2025-12-30 20:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_travel_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_holder',
            field=models.CharField(blank=True, help_text='Name des Kontoinhabers', max_length=200, verbose_name='Kontoinhaber'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_bic',
            field=models.CharField(blank=True, help_text='Bank Identifier Code', max_length=11, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='Internationale Bankkontonummer', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Name der Bank', max_length=200, verbose_name='Bankname'),
        ),
        migrations.AlterField(
            model_name='travelexpenseitem',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=users.models.travel_expense_receipt_path, verbose_name='Beleg'),
        ),
        migrations.AlterField(
            model_name='travelexpensereport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.travel_expense_pdf_path, verbose_name='PDF-Datei'),
        ),
    ]
