# Generated by Django 5.0 on 2025-12-31 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_serviceticket_options_and_more'),
        ('users', '0022_add_employee_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_recipient',
            field=models.BooleanField(default=False, verbose_name='Vom Empfänger gelöscht'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False, verbose_name='Vom Sender gelöscht'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user', 'Benutzer'), ('system', 'System'), ('ticket', 'Ticket-Benachrichtigung')], default='user', max_length=20, verbose_name='Nachrichtentyp'),
        ),
        migrations.AddField(
            model_name='message',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='service.serviceticket', verbose_name='Verknüpftes Ticket'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Absender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Betreff'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger'),
        ),
    ]
