# Generated by Django 5.0 on 2026-01-03 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_message_is_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['due_date', '-created_at'], 'verbose_name': 'Erinnerung', 'verbose_name_plural': 'Erinnerungen'},
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_dismissed',
            field=models.BooleanField(default=False, help_text='Vom Benutzer ausgeblendet, wird nicht mehr im Modal angezeigt', verbose_name='Ausgeblendet'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Verknüpfte Objekt-ID'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='z.B. "loan", "quotation", "order"', max_length=50, verbose_name='Verknüpfter Objekttyp'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='related_url',
            field=models.CharField(blank=True, help_text='URL zum verknüpften Objekt', max_length=500, verbose_name='Verknüpfte URL'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(verbose_name='Fälligkeitsdatum'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warnung'), ('success', 'Erfolg'), ('loan', 'Leihung'), ('order', 'Bestellung'), ('quotation', 'Angebot')], default='info', max_length=20, verbose_name='Typ')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('related_url', models.CharField(blank=True, max_length=500, verbose_name='Verknüpfte URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Mitteilung',
                'verbose_name_plural': 'Mitteilungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
