# Generated by Django 5.0 on 2026-01-03 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_reminder_notification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationYearBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('entitlement', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Jahresanspruch (anteilig)')),
                ('carryover', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Übertrag aus Vorjahr')),
                ('manual_adjustment', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Manuelle Anpassungen')),
                ('taken', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Genommen')),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resturlaub')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Jahr abgeschlossen')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_vacation_years', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_year_balances', to='users.employee')),
            ],
            options={
                'verbose_name': 'Jahresurlaubskonto',
                'verbose_name_plural': 'Jahresurlaubskonten',
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='VacationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('manual', 'Manuelle Anpassung'), ('carryover', 'Übertrag'), ('year_close', 'Jahresabschluss'), ('correction', 'Korrektur'), ('approval', 'Genehmigung'), ('rejection', 'Ablehnung'), ('cancellation', 'Stornierung'), ('entitlement_change', 'Anspruchsänderung')], max_length=20, verbose_name='Art der Anpassung')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Tage (+/-)')),
                ('balance_before', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Kontostand vorher')),
                ('balance_after', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Kontostand nachher')),
                ('reason', models.TextField(verbose_name='Begründung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_adjustments', to='users.employee')),
                ('vacation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='users.vacationrequest')),
                ('year_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='users.vacationyearbalance')),
            ],
            options={
                'verbose_name': 'Urlaubsanpassung',
                'verbose_name_plural': 'Urlaubsanpassungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
