# Generated by Django 5.0 on 2026-01-05 22:28

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_vacationyearbalance_vacationadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_bi',
            field=models.BooleanField(default=False, verbose_name='BI - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_documents',
            field=models.BooleanField(default=False, verbose_name='Documents - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_finance',
            field=models.BooleanField(default=False, verbose_name='Finance - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_hr_employees',
            field=models.BooleanField(default=False, verbose_name='Mitarbeiter - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_inventory',
            field=models.BooleanField(default=False, verbose_name='Inventory - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_inventory_warehouse',
            field=models.BooleanField(default=False, verbose_name='Lager - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_manufacturing_production_orders',
            field=models.BooleanField(default=False, verbose_name='Fertigungsaufträge - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_manufacturing_vs_hardware',
            field=models.BooleanField(default=False, verbose_name='VS-Hardware - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_procurement',
            field=models.BooleanField(default=False, verbose_name='Procurement - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_procurement_loans',
            field=models.BooleanField(default=False, verbose_name='Leihgeräte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_procurement_orders',
            field=models.BooleanField(default=False, verbose_name='Bestellungen - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_procurement_product_collections',
            field=models.BooleanField(default=False, verbose_name='Produktsammlungen - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_dealers',
            field=models.BooleanField(default=False, verbose_name='Händler - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_marketing',
            field=models.BooleanField(default=False, verbose_name='Marketing - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_order_processing',
            field=models.BooleanField(default=False, verbose_name='Auftragsbearbeitung - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_pricelists',
            field=models.BooleanField(default=False, verbose_name='Preislisten - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_projects',
            field=models.BooleanField(default=False, verbose_name='Projekte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_quotations',
            field=models.BooleanField(default=False, verbose_name='Angebote - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_systems',
            field=models.BooleanField(default=False, verbose_name='Systeme - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_sales_tickets',
            field=models.BooleanField(default=False, verbose_name='Sales Tickets - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_service_rma',
            field=models.BooleanField(default=False, verbose_name='RMA - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_service_tickets',
            field=models.BooleanField(default=False, verbose_name='Service Tickets - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_service_troubleshooting',
            field=models.BooleanField(default=False, verbose_name='Troubleshooting - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_service_vs_service',
            field=models.BooleanField(default=False, verbose_name='VS-Service Produkte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview',
            field=models.BooleanField(default=False, verbose_name='VisiView - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_licenses',
            field=models.BooleanField(default=False, verbose_name='VisiView Lizenzen - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_macros',
            field=models.BooleanField(default=False, verbose_name='VisiView Macros - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_products',
            field=models.BooleanField(default=False, verbose_name='VisiView Produkte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_tickets',
            field=models.BooleanField(default=False, verbose_name='VisiView Tickets - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_bi',
            field=models.BooleanField(default=False, verbose_name='BI - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_documents',
            field=models.BooleanField(default=False, verbose_name='Documents - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_finance',
            field=models.BooleanField(default=False, verbose_name='Finance - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_hr_employees',
            field=models.BooleanField(default=False, verbose_name='Mitarbeiter - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_inventory',
            field=models.BooleanField(default=False, verbose_name='Inventory - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_inventory_warehouse',
            field=models.BooleanField(default=False, verbose_name='Lager - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_manufacturing_production_orders',
            field=models.BooleanField(default=False, verbose_name='Fertigungsaufträge - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_manufacturing_vs_hardware',
            field=models.BooleanField(default=False, verbose_name='VS-Hardware - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_procurement',
            field=models.BooleanField(default=False, verbose_name='Procurement - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_procurement_loans',
            field=models.BooleanField(default=False, verbose_name='Leihgeräte - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_procurement_orders',
            field=models.BooleanField(default=False, verbose_name='Bestellungen - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_procurement_product_collections',
            field=models.BooleanField(default=False, verbose_name='Produktsammlungen - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_dealers',
            field=models.BooleanField(default=False, verbose_name='Händler - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_marketing',
            field=models.BooleanField(default=False, verbose_name='Marketing - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_order_processing',
            field=models.BooleanField(default=False, verbose_name='Auftragsbearbeitung - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_pricelists',
            field=models.BooleanField(default=False, verbose_name='Preislisten - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_projects',
            field=models.BooleanField(default=False, verbose_name='Projekte - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_quotations',
            field=models.BooleanField(default=False, verbose_name='Angebote - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_systems',
            field=models.BooleanField(default=False, verbose_name='Systeme - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_tickets',
            field=models.BooleanField(default=False, verbose_name='Sales Tickets - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_service_rma',
            field=models.BooleanField(default=False, verbose_name='RMA - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_service_tickets',
            field=models.BooleanField(default=False, verbose_name='Service Tickets - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_service_troubleshooting',
            field=models.BooleanField(default=False, verbose_name='Troubleshooting - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_service_vs_service',
            field=models.BooleanField(default=False, verbose_name='VS-Service Produkte - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview',
            field=models.BooleanField(default=False, verbose_name='VisiView - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_licenses',
            field=models.BooleanField(default=False, verbose_name='VisiView Lizenzen - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_macros',
            field=models.BooleanField(default=False, verbose_name='VisiView Macros - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_products',
            field=models.BooleanField(default=False, verbose_name='VisiView Produkte - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_tickets',
            field=models.BooleanField(default=False, verbose_name='VisiView Tickets - Schreiben'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Unterschriftsbild für Angebote und Dokumente (PNG/JPG)', null=True, upload_to=core.upload_paths.hr_signature_upload_path, verbose_name='Unterschrift'),
        ),
    ]
