# Generated by Django 5.0 on 2026-01-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_add_hierarchical_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelperdiemrate',
            options={'ordering': ['country', 'city'], 'verbose_name': 'Reisekostenpauschale', 'verbose_name_plural': 'Reisekostenpauschalen'},
        ),
        migrations.AddField(
            model_name='travelperdiemrate',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt (optional)'),
        ),
        migrations.AlterField(
            model_name='travelperdiemrate',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Land'),
        ),
        migrations.AlterUniqueTogether(
            name='travelperdiemrate',
            unique_together={('country', 'city')},
        ),
    ]
