# Generated by Django 5.0 on 2026-01-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_travelperdiemrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_development',
            field=models.BooleanField(default=False, verbose_name='Entwicklung - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_development_projects',
            field=models.BooleanField(default=False, verbose_name='Entwicklungsprojekte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_maintenance_time',
            field=models.BooleanField(default=True, verbose_name='VisiView Maintenance Zeiterfassung - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_development',
            field=models.BooleanField(default=False, verbose_name='Entwicklung - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_development_projects',
            field=models.BooleanField(default=False, verbose_name='Entwicklungsprojekte - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_maintenance_time',
            field=models.BooleanField(default=True, verbose_name='VisiView Maintenance Zeiterfassung - Schreiben'),
        ),
    ]
