# Generated by Django 5.0 on 2026-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_can_read_development_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Provisionssatz in Prozent (z.B. 1.75 für 1,75%)', max_digits=5, verbose_name='Provisionssatz (%)'),
        ),
    ]
