# Generated by Django 5.0 on 2026-01-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='employee',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Provisionssatz in Prozent (z.B. 1.75 für 1,75%)', max_digits=5, verbose_name='Provisionssatz (%)'),
        ),
    ]
