# Generated by Django 5.0 on 2026-01-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_move_commission_rate_to_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Mitarbeiter', 'verbose_name_plural': 'Mitarbeiter'},
        ),
    ]
