# Generated by Django 5.0 on 2026-01-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_extended_project_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_meetings',
            field=models.BooleanField(default=True, verbose_name='Meetings - Lesen'),
        ),
    ]
