# Generated by Django 5.0 on 2026-01-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_can_read_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_write_meetings',
            field=models.BooleanField(default=False, verbose_name='Meetings - Schreiben'),
        ),
    ]
