# Generated by Django 5.0 on 2026-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_can_write_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sales_territory_countries',
            field=models.JSONField(blank=True, default=list, help_text='Liste der Länder-ISO-Codes (z.B. ["DE", "AT", "CH"])', verbose_name='Vertriebsgebiet Länder'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sales_territory_postal_codes',
            field=models.JSONField(blank=True, default=list, help_text='Liste der PLZ-Präfixe (z.B. ["8", "9"] für PLZ 80000-99999)', verbose_name='Vertriebsgebiet PLZ-Bereiche'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('vertrieb', 'Vertrieb'), ('geschaeftsfuehrung', 'Geschäftsführung'), ('entwicklung', 'Entwicklung'), ('fertigung', 'Fertigung'), ('verwaltung', 'Verwaltung')], max_length=100, verbose_name='Abteilung'),
        ),
    ]
