# Generated by Django 5.0 on 2026-02-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_responsible_employee_and_sales_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myverp_visible_tabs',
            field=models.JSONField(blank=True, default=list, help_text='Liste der sichtbaren Tab-IDs in MyVERP. Leer = alle Tabs sichtbar.', verbose_name='MyVERP sichtbare Tabs'),
        ),
    ]
