# Generated by Django 5.0 on 2026-02-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_add_myverp_visible_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_company_calendar',
            field=models.BooleanField(default=True, verbose_name='Firmenkalender - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_production_orders',
            field=models.BooleanField(default=False, verbose_name='VisiView Fertigungsaufträge - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_company_calendar',
            field=models.BooleanField(default=False, verbose_name='Firmenkalender - Schreiben'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_production_orders',
            field=models.BooleanField(default=False, verbose_name='VisiView Fertigungsaufträge - Schreiben'),
        ),
    ]
