# Generated by Django 5.0 on 2026-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_add_visiview_production_orders_and_company_calendar_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_visiview_supported_hardware',
            field=models.BooleanField(default=True, verbose_name='VisiView Unterstützte Hardware - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_visiview_supported_hardware',
            field=models.BooleanField(default=False, verbose_name='VisiView Unterstützte Hardware - Schreiben'),
        ),
    ]
