# Generated by Django 5.0 on 2026-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_user_can_read_visiview_supported_hardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_sales_travel_reports',
            field=models.BooleanField(default=False, verbose_name='Reise-/Serviceberichte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_travel_reports',
            field=models.BooleanField(default=False, verbose_name='Reise-/Serviceberichte - Schreiben'),
        ),
    ]
