# Generated by Django 5.0 on 2026-04-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_can_read_sales_travel_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_inventory_customer_loans',
            field=models.BooleanField(default=False, verbose_name='Verleihungen - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_inventory_customer_loans',
            field=models.BooleanField(default=False, verbose_name='Verleihungen - Schreiben'),
        ),
    ]
