# Generated by Django 5.0 on 2026-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_can_read_inventory_customer_loans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sql_verkaeufer_id',
            field=models.IntegerField(blank=True, help_text='VerkäuferID aus der Legacy SQL Server Datenbank (Mitarbeiter-Tabelle)', null=True, verbose_name='SQL Verkäufer-ID'),
        ),
    ]
