# Generated by Django 5.0 on 2026-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_add_sql_verkaeufer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_sales_sql_projekte',
            field=models.BooleanField(default=False, verbose_name='SQL-Projekte - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_sql_projekte',
            field=models.BooleanField(default=False, verbose_name='SQL-Projekte - Schreiben'),
        ),
    ]
