# Generated by Django 5.0 on 2026-04-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_can_read_sales_sql_projekte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_sales_sql_angebote',
            field=models.BooleanField(default=False, verbose_name='SQL-Angebote - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_sales_sql_angebote',
            field=models.BooleanField(default=False, verbose_name='SQL-Angebote - Schreiben'),
        ),
    ]
