# Generated by Django 5.0 on 2026-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_reminder_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_inventory_demo_systems',
            field=models.BooleanField(default=False, verbose_name='Demo-Systeme - Lesen'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_write_inventory_demo_systems',
            field=models.BooleanField(default=False, verbose_name='Demo-Systeme - Schreiben'),
        ),
    ]
