# Generated by Django 5.0 on 2025-12-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Produktkategorie',
                'verbose_name_plural': 'Produktkategorien',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lieferant',
                'verbose_name_plural': 'Lieferanten',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('service', 'Service'), ('sales', 'Vertrieb'), ('orders', 'Bestellungen')], max_length=20, verbose_name='Kontakttyp')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('contact_function', models.CharField(blank=True, max_length=100, verbose_name='Funktion')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Lieferanten-Kontakt',
                'verbose_name_plural': 'Lieferanten-Kontakte',
                'ordering': ['contact_type', 'contact_person'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_article_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Artikelnummer')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Einkaufspreis')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('delivery_time_days', models.IntegerField(blank=True, null=True, verbose_name='Lieferzeit (Tage)')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Mindestbestellmenge')),
                ('is_preferred_supplier', models.BooleanField(default=False, verbose_name='Bevorzugter Lieferant')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Lieferanten-Produkt',
                'verbose_name_plural': 'Lieferanten-Produkte',
                'ordering': ['-is_preferred_supplier', 'supplier__company_name'],
            },
        ),
        migrations.CreateModel(
            name='TradingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('article_number', models.CharField(max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mindestbestand')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.productcategory', verbose_name='Kategorie')),
                ('suppliers', models.ManyToManyField(related_name='trading_products', through='suppliers.SupplierProduct', to='suppliers.supplier', verbose_name='Lieferanten')),
            ],
            options={
                'verbose_name': 'Vertriebsware',
                'verbose_name_plural': 'Vertriebswaren',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.tradingproduct', verbose_name='Produkt'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together={('supplier', 'product')},
        ),
    ]
