# Generated by Django 5.0 on 2025-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('SOFTWARE', 'Software'), ('MIKROSKOPE', 'Mikroskope'), ('BELEUCHTUNG', 'Beleuchtung'), ('KAMERAS', 'Kameras'), ('CONFOCALS', 'Confocals'), ('PERIPHERALS', 'Peripherals')], max_length=20, null=True, verbose_name='Kategorie'),
        ),
        migrations.RemoveField(
            model_name='tradingproduct',
            name='currency',
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='costs_currency',
            field=models.CharField(default='EUR', help_text='Währung für Versand-, Import-, Handling- und Lagerkosten', max_length=3, verbose_name='Kostenw ährung'),
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='list_price_currency',
            field=models.CharField(default='EUR', help_text='EUR, USD, CHF, etc.', max_length=3, verbose_name='Listenpreis Währung'),
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aufschlag auf Einkaufspreis für Visitron-Listenpreis', max_digits=5, verbose_name='Aufschlag %'),
        ),
        migrations.AlterField(
            model_name='tradingproduct',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lieferanten-Listenpreis'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
