# Generated by Django 5.0 on 2025-12-17 17:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_tradingproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingproduct',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Wechselkurs von Listenpreis-Währung zu EUR', max_digits=10, verbose_name='Wechselkurs zu EUR'),
        ),
    ]
