# Generated by Django 5.0 on 2025-12-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_tradingproduct_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Warengruppe')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabatt (%)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Warengruppe',
                'verbose_name_plural': 'Warengruppen',
                'ordering': ['supplier', 'name'],
                'unique_together': {('supplier', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.productgroup', verbose_name='Warengruppe'),
        ),
    ]
