# Generated by Django 5.0 on 2025-12-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_productgroup_tradingproduct_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Preisliste')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Preisliste',
                'verbose_name_plural': 'Preislisten',
                'ordering': ['supplier', '-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.pricelist', verbose_name='Preisliste'),
        ),
    ]
