# Generated by Django 5.0 on 2025-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_pricelist_tradingproduct_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_number',
            field=models.CharField(blank=True, editable=False, help_text='Automatisch generierte 3-stellige Nummer', max_length=3, null=True, unique=True, verbose_name='Lieferantennummer'),
        ),
        migrations.AlterField(
            model_name='tradingproduct',
            name='visitron_part_number',
            field=models.CharField(blank=True, editable=False, help_text='Automatisch generiert: Lieferantennummer-laufende Nummer (z.B. 100-0001)', max_length=100, null=True, unique=True, verbose_name='Visitron Partnummer'),
        ),
    ]
