# Generated by Django 5.0 on 2025-12-18 12:29

from django.db import migrations


def populate_supplier_numbers(apps, schema_editor):
    """Generiere Lieferantennummern für bestehende Lieferanten"""
    Supplier = apps.get_model('suppliers', 'Supplier')
    
    suppliers = Supplier.objects.filter(supplier_number__isnull=True).order_by('id')
    next_number = 100
    
    for supplier in suppliers:
        supplier.supplier_number = str(next_number).zfill(3)
        supplier.save()
        next_number += 1


def populate_visitron_part_numbers(apps, schema_editor):
    """Generiere Visitron-Partnummern für bestehende Handelswaren"""
    TradingProduct = apps.get_model('suppliers', 'TradingProduct')
    
    # Gruppiere Produkte nach Lieferant
    products = TradingProduct.objects.filter(visitron_part_number__isnull=True).select_related('supplier').order_by('supplier_id', 'id')
    
    current_supplier_id = None
    next_suffix = 1
    
    for product in products:
        if not product.supplier or not product.supplier.supplier_number:
            continue
            
        # Wenn neuer Lieferant, setze Suffix zurück
        if current_supplier_id != product.supplier_id:
            current_supplier_id = product.supplier_id
            next_suffix = 1
        
        # Generiere Partnummer
        product.visitron_part_number = f"{product.supplier.supplier_number}-{str(next_suffix).zfill(4)}"
        product.save()
        next_suffix += 1


def reverse_migration(apps, schema_editor):
    """Rückgängig machen - Nummern zurücksetzen"""
    Supplier = apps.get_model('suppliers', 'Supplier')
    TradingProduct = apps.get_model('suppliers', 'TradingProduct')
    
    Supplier.objects.all().update(supplier_number=None)
    TradingProduct.objects.all().update(visitron_part_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_supplier_number_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_supplier_numbers, reverse_migration),
        migrations.RunPython(populate_visitron_part_numbers, migrations.RunPython.noop),
    ]
