# Generated by Django 5.0 on 2025-12-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_populate_supplier_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('visitron_part_number', models.CharField(blank=True, editable=False, help_text='Automatisch generiert: Lieferantennummer-laufende Nummer (z.B. 100-A001)', max_length=100, null=True, unique=True, verbose_name='Visitron Partnummer')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('supplier_part_number', models.CharField(blank=True, max_length=100, verbose_name='Händler-Partnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einkaufspreis')),
                ('purchase_currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung Einkauf')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Verkaufspreis')),
                ('purchase_date', models.DateField(verbose_name='Kaufdatum')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Erwartetes Lieferdatum')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Tatsächliches Lieferdatum')),
                ('warranty_months', models.IntegerField(default=12, verbose_name='Garantiezeitraum (Monate)')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aktueller Restwert')),
                ('status', models.CharField(choices=[('in_progress', 'In Bearbeitung'), ('ordered', 'Bestellt'), ('confirmed', 'Bestätigt'), ('in_stock', 'Auf Lager'), ('sold', 'Verkauft')], default='in_progress', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('product_group', models.ForeignKey(blank=True, help_text='Automatisch auf "Anlage" gesetzt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='suppliers.productgroup', verbose_name='Warengruppe')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Anlage',
                'verbose_name_plural': 'Anlagen',
                'ordering': ['-created_at'],
            },
        ),
    ]
