# Generated by Django 5.0 on 2025-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address_supplement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, default='DE', help_text='ISO 3166-1 Alpha-2 Code', max_length=2, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bundesland/Provinz'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='address_supplement',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='country',
            field=models.CharField(blank=True, default='DE', help_text='ISO 3166-1 Alpha-2 Code', max_length=2, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bundesland/Provinz'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Wird durch neue Adressfelder ersetzt', verbose_name='Adresse (veraltet)'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='address',
            field=models.TextField(blank=True, help_text='Wird durch neue Adressfelder ersetzt', verbose_name='Adresse (veraltet)'),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='contact_type',
            field=models.CharField(choices=[('service', 'Service'), ('sales', 'Vertrieb'), ('orders', 'Bestellungen'), ('order_processing', 'Auftragsabwicklung')], max_length=20, verbose_name='Kontakttyp'),
        ),
        migrations.AddConstraint(
            model_name='suppliercontact',
            constraint=models.UniqueConstraint(condition=models.Q(('contact_type', 'orders')), fields=('supplier', 'contact_type'), name='unique_orders_contact_per_supplier'),
        ),
    ]
