# Generated by Django 5.0 on 2025-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_supplier_address_supplement_supplier_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingproduct',
            name='markup_percent',
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marge in % für Visitron-Listenpreis (VLP = EK / (1 - Marge/100))', max_digits=5, verbose_name='Marge %'),
        ),
        migrations.AlterField(
            model_name='tradingproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('SOFTWARE', 'Software'), ('MIKROSKOPE', 'Mikroskope'), ('BELEUCHTUNG', 'Beleuchtung'), ('KAMERAS', 'Kameras'), ('DIENSTLEISTUNG', 'Dienstleistung'), ('LICHTQUELLEN', 'Lichtquellen'), ('SCANNING_BELEUCHTUNG', 'Scanning- und Beleuchtungsmodule'), ('PERIPHERALS', 'Peripherals')], max_length=20, null=True, verbose_name='Kategorie'),
        ),
    ]
