# Generated by Django 5.0 on 2025-12-19 13:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_remove_tradingproduct_markup_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('visitron_part_number', models.CharField(blank=True, help_text='Automatisch generiert: Lieferantennummer-M-laufende Nummer (z.B. 100-M0001)', max_length=50, unique=True, verbose_name='Visitron Partnummer')),
                ('supplier_part_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Partnummer')),
                ('category', models.CharField(blank=True, choices=[('ROHSTOFF', 'Rohstoff'), ('HILFSSTOFF', 'Hilfsstoff'), ('BETRIEBSSTOFF', 'Betriebsstoff')], max_length=20, null=True, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lieferanten-Listenpreis')),
                ('list_price_currency', models.CharField(default='EUR', help_text='EUR, USD, CHF, etc.', max_length=3, verbose_name='Listenpreis Währung')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), help_text='Wechselkurs von Listenpreis-Währung zu EUR', max_digits=10, verbose_name='Wechselkurs zu EUR')),
                ('costs_currency', models.CharField(default='EUR', help_text='Währung für Versand-, Import-, Handling- und Lagerkosten', max_length=3, verbose_name='Kostenwährung')),
                ('price_valid_from', models.DateField(verbose_name='Preis gültig von')),
                ('price_valid_until', models.DateField(blank=True, null=True, verbose_name='Preis gültig bis')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Rabatt in Prozent', max_digits=5, verbose_name='Rabatt (%)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Versandkosten')),
                ('shipping_cost_is_percent', models.BooleanField(default=False, verbose_name='Versandkosten in %')),
                ('import_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importkosten')),
                ('import_cost_is_percent', models.BooleanField(default=False, verbose_name='Importkosten in %')),
                ('handling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Handlingkosten')),
                ('handling_cost_is_percent', models.BooleanField(default=False, verbose_name='Handlingkosten in %')),
                ('storage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lagerkosten')),
                ('storage_cost_is_percent', models.BooleanField(default=False, verbose_name='Lagerkosten in %')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mindestbestand')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_supplies', to='suppliers.pricelist', verbose_name='Preisliste')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_supplies', to='suppliers.productgroup', verbose_name='Warengruppe')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_supplies', to='suppliers.supplier', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Material & Supplies',
                'verbose_name_plural': 'Material & Supplies',
                'ordering': ['visitron_part_number'],
            },
        ),
    ]
