# Generated by Django 5.0 on 2025-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0011_materialsupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='Website'),
        ),
    ]
