# Generated by Django 5.0 on 2025-12-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_supplier_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='customer_number',
            field=models.CharField(blank=True, help_text='Unsere Kundennummer beim Lieferanten', max_length=100, verbose_name='Unsere Kundennummer'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='z.B. 30 Tage netto, 14 Tage 2% Skonto', verbose_name='Zahlungsbedingungen'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipping_instructions',
            field=models.TextField(blank=True, help_text='Besondere Versandanweisungen für diesen Lieferanten', verbose_name='Versandanweisungen'),
        ),
    ]
