# Generated by Django 5.0 on 2025-12-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_supplier_customer_number_supplier_payment_terms_and_more'),
        ('verp_settings', '0004_deliveryinstruction_deliveryterm_paymentterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='shipping_instructions',
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='verp_settings.deliveryinstruction', verbose_name='Lieferanweisung'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='delivery_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='verp_settings.deliveryterm', verbose_name='Lieferbedingung (Incoterm)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='verp_settings.paymentterm', verbose_name='Zahlungsbedingung'),
        ),
    ]
