# Generated by Django 5.0 on 2025-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_remove_supplier_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='short_description',
            field=models.CharField(blank=True, help_text='Kurze Beschreibung für Bestellungen', max_length=200, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='materialsupply',
            name='short_description',
            field=models.CharField(blank=True, help_text='Kurze Beschreibung für Bestellungen', max_length=200, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='short_description',
            field=models.CharField(blank=True, help_text='Kurze Beschreibung für Bestellungen', max_length=200, verbose_name='Kurzbeschreibung'),
        ),
    ]
