# Generated by Django 5.0 on 2025-12-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_asset_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='visitron_part_number',
            field=models.CharField(blank=True, editable=False, help_text='Automatisch generiert: Lieferantennummer-laufende Nummer (z.B. 100-A00001)', max_length=100, null=True, unique=True, verbose_name='Visitron Partnummer'),
        ),
        migrations.AlterField(
            model_name='materialsupply',
            name='visitron_part_number',
            field=models.CharField(blank=True, help_text='Automatisch generiert: Lieferantennummer-M-laufende Nummer (z.B. 100-M00001)', max_length=50, unique=True, verbose_name='Visitron Partnummer'),
        ),
        migrations.AlterField(
            model_name='tradingproduct',
            name='visitron_part_number',
            field=models.CharField(blank=True, editable=False, help_text='Automatisch generiert: Lieferantennummer-laufende Nummer (z.B. 100-00001)', max_length=100, null=True, unique=True, verbose_name='Visitron Partnummer'),
        ),
    ]
