# Generated by Django 5.0 on 2025-12-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderitem_asset'),
        ('suppliers', '0016_alter_asset_visitron_part_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
