# Generated by Django 5.0 on 2025-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingproduct',
            name='release_manual',
            field=models.FileField(blank=True, help_text='Freigegebenes Handbuch zum Produkt', null=True, upload_to='TradingProducts/manuals/', verbose_name='Release-Manual'),
        ),
    ]
