# Generated by Django 5.0 on 2025-12-29 09:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_tradingproduct_release_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingproduct',
            name='description_en',
            field=models.TextField(blank=True, help_text='English description for international quotations', verbose_name='Beschreibung (Englisch)'),
        ),
        migrations.AddField(
            model_name='tradingproduct',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='Short English description for orders', max_length=200, verbose_name='Kurzbeschreibung (Englisch)'),
        ),
        migrations.CreateModel(
            name='TradingProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_list_price', models.DecimalField(decimal_places=2, help_text='Original-Listenpreis des Lieferanten', max_digits=12, verbose_name='Lieferanten-Listenpreis')),
                ('supplier_currency', models.CharField(default='EUR', max_length=3, verbose_name='Listenpreis-Währung')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=10, verbose_name='Wechselkurs zu EUR')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rabatt (%)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Versandkosten')),
                ('shipping_cost_is_percent', models.BooleanField(default=False, verbose_name='Versandkosten in %')),
                ('import_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importkosten')),
                ('import_cost_is_percent', models.BooleanField(default=False, verbose_name='Importkosten in %')),
                ('handling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Handlingkosten')),
                ('handling_cost_is_percent', models.BooleanField(default=False, verbose_name='Handlingkosten in %')),
                ('storage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lagerkosten')),
                ('storage_cost_is_percent', models.BooleanField(default=False, verbose_name='Lagerkosten in %')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, help_text='Marge für Visitron-Listenpreis', max_digits=5, verbose_name='Marge (%)')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Berechneter Einkaufspreis in EUR', max_digits=12, verbose_name='Einkaufspreis (EK)')),
                ('list_price', models.DecimalField(decimal_places=2, help_text='Berechneter Verkaufspreis für Angebote in EUR', max_digits=12, verbose_name='Visitron-Listenpreis (LP/VK)')),
                ('valid_from', models.DateField(verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, help_text='Leer = unbegrenzt gültig', null=True, verbose_name='Gültig bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_product_prices_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='suppliers.tradingproduct', verbose_name='Trading Product')),
            ],
            options={
                'verbose_name': 'Trading Product Preis',
                'verbose_name_plural': 'Trading Product Preise',
                'ordering': ['product', '-valid_from'],
            },
        ),
    ]
