# Generated by Django 5.0 on 2026-01-07 15:25

import core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0019_tradingproduct_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingproduct',
            name='release_manual',
            field=models.FileField(blank=True, help_text='Freigegebenes Handbuch zum Produkt', null=True, upload_to=core.upload_paths.trading_product_manual_upload_path, verbose_name='Release-Manual'),
        ),
    ]
