# Generated by Django 5.0 on 2026-01-20 09:25

import django.db.models.deletion
import suppliers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0020_alter_tradingproduct_release_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('price_list', 'Preisliste'), ('brochure', 'Prospekt'), ('contract', 'Vertrag'), ('certificate', 'Zertifikat'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Dateityp')),
                ('name', models.CharField(max_length=200, verbose_name='Name/Beschreibung')),
                ('file', models.FileField(upload_to=suppliers.models.supplier_attachment_upload_path, verbose_name='Datei')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Dateiname')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-Type')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig von')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lieferanten-Anhang',
                'verbose_name_plural': 'Lieferanten-Anhänge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='suppliercontact',
            name='unique_orders_contact_per_supplier',
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Ist dies der Hauptkontakt in dieser Kategorie?', verbose_name='Hauptkontakt'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mobilnummer'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suppliercontact',
            name='contact_type',
            field=models.CharField(choices=[('main', 'Hauptansprechpartner'), ('service', 'Service'), ('sales', 'Vertrieb'), ('orders', 'Bestellungen'), ('order_processing', 'Auftragsabwicklung'), ('ceo', 'Geschäftsführung')], max_length=20, verbose_name='Kontakttyp'),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='suppliers.pricelist', verbose_name='Zugehörige Preisliste'),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='suppliers.supplier', verbose_name='Lieferant'),
        ),
        migrations.AddField(
            model_name='supplierattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von'),
        ),
    ]
