# Generated by Django 5.0 on 2026-01-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('quotation', 'Angebot'), ('customer_order', 'Kundenauftrag'), ('customer', 'Kunde'), ('supplier', 'Lieferant'), ('distributor', 'Distributor'), ('project', 'Projekt'), ('system', 'System'), ('order', 'Bestellung'), ('other', 'Sonstiges')], max_length=50, verbose_name='Entitätstyp')),
                ('entity_id', models.PositiveIntegerField(verbose_name='Entitäts-ID')),
                ('entity_description', models.CharField(help_text='Z.B. "ANG-2024-001 - Kunde Mustermann"', max_length=500, verbose_name='Entitätsbeschreibung')),
                ('action', models.CharField(choices=[('deleted', 'Gelöscht'), ('cancelled', 'Storniert'), ('force_deleted', 'Zwangsgelöscht')], max_length=20, verbose_name='Aktion')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Durchgeführt am')),
                ('reason', models.TextField(blank=True, verbose_name='Grund')),
                ('was_forced', models.BooleanField(default=False, help_text='Wurde die Entwicklungscheckbox verwendet?', verbose_name='Erzwungene Löschung')),
                ('media_count', models.IntegerField(default=0, verbose_name='Anzahl gelöschter Medien')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Durchgeführt von')),
            ],
            options={
                'verbose_name': 'Löschprotokoll',
                'verbose_name_plural': 'Löschprotokolle',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=500, verbose_name='Ursprünglicher Pfad')),
                ('trash_path', models.CharField(max_length=500, verbose_name='Papierkorb-Pfad')),
                ('filename', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dateigröße (Bytes)')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('object_description', models.CharField(help_text='Z.B. "Angebot ANG-2024-001"', max_length=500, verbose_name='Objektbeschreibung')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gelöscht am')),
                ('deletion_reason', models.TextField(blank=True, verbose_name='Grund der Löschung')),
                ('can_restore', models.BooleanField(default=True, help_text='Kann die Datei wiederhergestellt werden?', verbose_name='Wiederherstellbar')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von')),
            ],
            options={
                'verbose_name': 'Gelöschte Medien',
                'verbose_name_plural': 'Gelöschte Medien',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
