# Generated by Django 5.0 on 2025-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='ISO Währungscode (USD, CHF, GBP, etc.)', max_length=3, unique=True, verbose_name='Währung')),
                ('rate_to_eur', models.DecimalField(decimal_places=6, help_text='1 Einheit dieser Währung = X EUR', max_digits=10, verbose_name='Kurs zu EUR')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
            ],
            options={
                'verbose_name': 'Wechselkurs',
                'verbose_name_plural': 'Wechselkurse',
                'ordering': ['currency'],
            },
        ),
    ]
