# Generated by Django 5.0 on 2025-12-19 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Firmenname')),
                ('email_orders', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail für Kundenbestellungen')),
                ('email_general', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail für allgemeine Anfragen')),
                ('email_service', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail für Service')),
                ('email_sales', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail für Vertrieb')),
                ('phone_central', models.CharField(blank=True, max_length=50, verbose_name='Zentrale Telefonnummer')),
                ('trade_register_number', models.CharField(blank=True, max_length=100, verbose_name='Handelsregisternummer')),
                ('professional_association', models.CharField(blank=True, max_length=200, verbose_name='Berufsgenossenschaft')),
                ('vat_id', models.CharField(blank=True, help_text='z.B. DE123456789', max_length=50, verbose_name='Umsatzsteuer-ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmeneinstellungen',
                'verbose_name_plural': 'Firmeneinstellungen',
            },
        ),
        migrations.CreateModel(
            name='CompanyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('title', models.CharField(blank=True, help_text='z.B. Dr., Prof.', max_length=50, verbose_name='Titel')),
                ('position', models.CharField(default='Geschäftsführer', max_length=100, verbose_name='Position')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='verp_settings.companysettings', verbose_name='Firmeneinstellungen')),
            ],
            options={
                'verbose_name': 'Geschäftsführer',
                'verbose_name_plural': 'Geschäftsführer',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Bankname')),
                ('account_holder', models.CharField(blank=True, max_length=200, verbose_name='Kontoinhaber')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Währung')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptkonto')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='verp_settings.companysettings', verbose_name='Firmeneinstellungen')),
            ],
            options={
                'verbose_name': 'Bankverbindung',
                'verbose_name_plural': 'Bankverbindungen',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(help_text='z.B. Hauptsitz, Niederlassung, Lager', max_length=50, verbose_name='Adresstyp')),
                ('street', models.CharField(max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(max_length=20, verbose_name='Hausnummer')),
                ('address_supplement', models.CharField(blank=True, max_length=200, verbose_name='Adresszusatz')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postleitzahl')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Bundesland/Staat')),
                ('country', models.CharField(default='DE', max_length=2, verbose_name='Land (ISO-Code)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptadresse')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='verp_settings.companysettings', verbose_name='Firmeneinstellungen')),
            ],
            options={
                'verbose_name': 'Firmenadresse',
                'verbose_name_plural': 'Firmenadressen',
                'ordering': ['-is_primary', 'address_type'],
            },
        ),
    ]
