# Generated by Django 5.0 on 2025-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0002_companysettings_companymanager_companybankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='Firmenwebsite'),
        ),
    ]
