# Generated by Django 5.0 on 2026-01-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0003_add_dienstleistung_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(choices=[('KAMERA', 'Kamera'), ('CONFOCAL', 'Confocal'), ('VIRTEX', 'ViRTEx'), ('FRAP', 'FRAP'), ('ORBITAL', 'Orbital'), ('VS_LMS', 'VS-LMS'), ('INKUBATION', 'Inkubation'), ('SCANNINGTISCH', 'Scanningtisch'), ('LED', 'LED'), ('LASER', 'Laser'), ('VISIVIEW', 'VisiView'), ('DUALCAM_SPLITTER', 'DualCam/Splitter'), ('FILTER', 'Filter'), ('FILTERRAD', 'Filterrad'), ('MIKROSKOP', 'Mikroskop'), ('PC', 'PC'), ('KABEL', 'Kabel'), ('ROHSTOFF', 'Rohstoff'), ('HILFSSTOFF', 'Hilfsstoff'), ('BETRIEBSSTOFF', 'Betriebsstoff'), ('SOFTWARE', 'Software'), ('SERVICE', 'Service'), ('DIENSTLEISTUNG', 'Dienstleistung'), ('SONSTIGES', 'Sonstiges')], max_length=30, unique=True, verbose_name='Kategorie-Code'),
        ),
    ]
