# Generated by Django 5.0 on 2025-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0003_companysettings_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "Standard Lieferung", "Express", "Nur Mo-Fr 8-16 Uhr"', max_length=200, unique=True, verbose_name='Bezeichnung')),
                ('instruction_text', models.TextField(help_text='Detaillierte Lieferanweisungen für den Lieferanten', verbose_name='Anweisungstext')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Lieferanweisung',
                'verbose_name_plural': 'Lieferanweisungen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW - Ex Works (ab Werk)'), ('FCA', 'FCA - Free Carrier (frei Frachtführer)'), ('CPT', 'CPT - Carriage Paid To (frachtfrei)'), ('CIP', 'CIP - Carriage and Insurance Paid To (frachtfrei versichert)'), ('DAP', 'DAP - Delivered at Place (geliefert benannter Ort)'), ('DPU', 'DPU - Delivered at Place Unloaded (geliefert entladen)'), ('DDP', 'DDP - Delivered Duty Paid (geliefert verzollt)'), ('FAS', 'FAS - Free Alongside Ship (frei Längsseite Schiff)'), ('FOB', 'FOB - Free On Board (frei an Bord)'), ('CFR', 'CFR - Cost and Freight (Kosten und Fracht)'), ('CIF', 'CIF - Cost, Insurance and Freight (Kosten, Versicherung und Fracht)')], max_length=3, unique=True, verbose_name='Incoterm 2020')),
                ('is_active', models.BooleanField(default=True, help_text='Für Lieferantenauswahl verfügbar', verbose_name='Aktiviert')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Erklärung oder Hinweise', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Lieferbedingung (Incoterm)',
                'verbose_name_plural': 'Lieferbedingungen (Incoterms)',
                'ordering': ['incoterm'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "30 Tage netto", "Vorkasse", "Anzahlung 30% + Rest bei Lieferung"', max_length=200, unique=True, verbose_name='Bezeichnung')),
                ('is_prepayment', models.BooleanField(default=False, help_text='Zahlung vor Lieferung', verbose_name='Vorkasse')),
                ('payment_days', models.PositiveIntegerField(blank=True, help_text='Tage ab Rechnungsdatum', null=True, verbose_name='Zahlungsfrist in Tagen')),
                ('discount_days', models.PositiveIntegerField(blank=True, help_text='Zahlungsfrist für Skonto', null=True, verbose_name='Skonto-Frist in Tagen')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='z.B. 2.00 für 2% Skonto', max_digits=5, null=True, verbose_name='Skonto %')),
                ('has_custom_terms', models.BooleanField(default=False, help_text='Aktiviert benutzerdefinierte Zahlungsziele', verbose_name='Custom Zahlungsziele')),
                ('down_payment_percent', models.DecimalField(blank=True, decimal_places=2, help_text='z.B. 30.00 für 30% Anzahlung', max_digits=5, null=True, verbose_name='Anzahlung %')),
                ('down_payment_description', models.CharField(blank=True, help_text='z.B. "Bei Auftragserteilung"', max_length=200, verbose_name='Anzahlung Beschreibung')),
                ('delivery_payment_percent', models.DecimalField(blank=True, decimal_places=2, help_text='z.B. 50.00 für 50% bei Lieferung', max_digits=5, null=True, verbose_name='Zahlung bei Lieferung %')),
                ('delivery_payment_description', models.CharField(blank=True, help_text='z.B. "Bei Lieferung"', max_length=200, verbose_name='Lieferung Beschreibung')),
                ('acceptance_payment_percent', models.DecimalField(blank=True, decimal_places=2, help_text='z.B. 20.00 für 20% bei Abnahme', max_digits=5, null=True, verbose_name='Zahlung bei Abnahme %')),
                ('acceptance_payment_description', models.CharField(blank=True, help_text='z.B. "30 Tage nach Abnahme"', max_length=200, verbose_name='Abnahme Beschreibung')),
                ('notes', models.TextField(blank=True, verbose_name='Zusätzliche Informationen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Zahlungsbedingung',
                'verbose_name_plural': 'Zahlungsbedingungen',
                'ordering': ['name'],
            },
        ),
    ]
