# Generated by Django 5.0 on 2025-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0005_populate_incoterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('KAMERA', 'Kamera'), ('CONFOCAL', 'Confocal'), ('VIRTEX', 'ViRTEx'), ('FRAP', 'FRAP'), ('ORBITAL', 'Orbital'), ('VS_LMS', 'VS-LMS'), ('INKUBATION', 'Inkubation'), ('SCANNINGTISCH', 'Scanningtisch'), ('LED', 'LED'), ('LASER', 'Laser'), ('VISIVIEW', 'VisiView'), ('DUALCAM_SPLITTER', 'DualCam/Splitter'), ('FILTER', 'Filter'), ('FILTERRAD', 'Filterrad'), ('MIKROSKOP', 'Mikroskop'), ('PC', 'PC'), ('KABEL', 'Kabel'), ('ROHSTOFF', 'Rohstoff'), ('HILFSSTOFF', 'Hilfsstoff'), ('BETRIEBSSTOFF', 'Betriebsstoff'), ('SOFTWARE', 'Software'), ('SERVICE', 'Service'), ('SONSTIGES', 'Sonstiges')], max_length=30, unique=True, verbose_name='Kategorie-Code')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriename')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('applies_to_trading_goods', models.BooleanField(default=True, verbose_name='Für Handelswaren')),
                ('applies_to_material_supplies', models.BooleanField(default=True, verbose_name='Für M&S')),
                ('applies_to_vs_hardware', models.BooleanField(default=True, verbose_name='Für VS-Hardware')),
                ('applies_to_vs_software', models.BooleanField(default=False, verbose_name='Für VS-Software')),
                ('applies_to_vs_service', models.BooleanField(default=False, verbose_name='Für VS-Service')),
                ('requires_serial_number', models.BooleanField(default=True, help_text='Ob Waren dieser Kategorie eine Seriennummer benötigen', verbose_name='Seriennummer erforderlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Warenkategorie',
                'verbose_name_plural': 'Warenkategorien',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
