# Generated by Django 5.0 on 2025-12-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0006_add_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "12 Monate Garantie", "24 Monate auf Teile"', max_length=200, unique=True, verbose_name='Bezeichnung')),
                ('name_en', models.CharField(blank=True, help_text='Englische Bezeichnung für internationale Dokumente', max_length=200, verbose_name='Bezeichnung (EN)')),
                ('duration_months', models.PositiveIntegerField(default=12, verbose_name='Garantiedauer (Monate)')),
                ('description', models.TextField(blank=True, help_text='Detaillierte Garantiebedingungen', verbose_name='Beschreibung')),
                ('description_en', models.TextField(blank=True, help_text='Englische Beschreibung', verbose_name='Beschreibung (EN)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Garantiebedingung',
                'verbose_name_plural': 'Garantiebedingungen',
                'ordering': ['duration_months', 'name'],
            },
        ),
    ]
