# Generated by Django 5.0 on 2026-02-19 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0006_alter_productcategory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('production', 'Fertigungscheckliste'), ('outgoing', 'Ausgangscheckliste')], max_length=20, verbose_name='Checklistentyp')),
                ('name', models.CharField(blank=True, help_text='Optionaler Name für die Checkliste', max_length=200, verbose_name='Name')),
                ('sections', models.JSONField(default=list, help_text='Aufbau: [{title, items: [{id, label}]}]', verbose_name='Sektionen')),
                ('special_tables', models.JSONField(blank=True, default=dict, help_text='z.B. galvo_table, laser_table, leoni_sn', verbose_name='Spezielle Tabellen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='verp_settings.productcategory', verbose_name='Warenkategorie')),
            ],
            options={
                'verbose_name': 'Checklistenvorlage',
                'verbose_name_plural': 'Checklistenvorlagen',
                'ordering': ['product_category__sort_order', 'checklist_type'],
                'unique_together': {('product_category', 'checklist_type')},
            },
        ),
    ]
