# Generated by Django 5.0 on 2026-02-19 14:52

from django.db import migrations


def seed_checklist_templates(apps, schema_editor):
    """
    Erstellt initiale Checklistenvorlagen aus den bisher hartkodierten Checklisten.
    """
    ProductCategory = apps.get_model('verp_settings', 'ProductCategory')
    ChecklistTemplate = apps.get_model('verp_settings', 'ChecklistTemplate')

    # Helper to get or skip missing categories
    def get_cat(code):
        try:
            return ProductCategory.objects.get(code=code)
        except ProductCategory.DoesNotExist:
            return None

    # ===== PRODUCTION CHECKLISTS =====

    # VIRTEX
    cat = get_cat('VIRTEX')
    if cat:
        ChecklistTemplate.objects.get_or_create(
            product_category=cat,
            checklist_type='production',
            defaults={
                'name': 'ViRTEx Fertigungscheckliste',
                'sections': [
                    {
                        'title': 'Allgemein',
                        'items': [
                            {'id': 'fw_update', 'label': 'FW Update OK'},
                            {'id': 'sn_aufkleber', 'label': 'SN Aufkleber OK'}
                        ]
                    },
                    {
                        'title': 'Digital Ports Test',
                        'items': [
                            {'id': 'ttl_out', 'label': 'TTL out OK'},
                            {'id': 'cam_input', 'label': 'Cam Input OK'},
                            {'id': 'ln0_trigger_sync', 'label': 'ln0 / TriggerIN / SyncIn OK'},
                            {'id': 'cam_out', 'label': 'Cam out OK'},
                            {'id': 'trigger_ready', 'label': 'Trigger ready OK'}
                        ]
                    },
                    {
                        'title': 'mit Laser Logic',
                        'items': [
                            {'id': 'ttl_output_laser_logic', 'label': 'TTL Output Laser Logic OK'},
                            {'id': 'interlock', 'label': 'Interlock OK'}
                        ]
                    },
                    {
                        'title': 'mit Multiplexer',
                        'items': [
                            {'id': 'ttl_output_led', 'label': 'TTL Output LED Lampe OK'},
                            {'id': 'ttl_output_laser_mux', 'label': 'TTL Output Laser OK'}
                        ]
                    },
                    {
                        'title': 'mit Orbital',
                        'items': [
                            {'id': 'orbital_ok', 'label': 'Orbital OK'},
                            {'id': 'ttl_output_laser_orbital', 'label': 'TTL Output Laser OK'}
                        ]
                    },
                    {
                        'title': 'mit Break-out Box',
                        'items': [
                            {'id': 'qswitch', 'label': 'QSwitch OK'},
                            {'id': 'ttl_a0_a3', 'label': 'TTL A0-A3 OK'},
                            {'id': 'ttl_b0_b6', 'label': 'TTL B0-B6 OK'}
                        ]
                    },
                    {
                        'title': 'Analog Ports Test',
                        'items': [
                            {'id': 'number_ports_onstate', 'label': 'Number of ports on-state OK'},
                            {'id': 'analog_0_10v', 'label': '0-10V OK'},
                            {'id': 'analog_0_5v', 'label': '0-5V OK'},
                            {'id': 'analog_3_4', 'label': 'Analog #3 #4 OK'},
                            {'id': 'analog_minus5_plus5', 'label': '-5V..+5V OK'}
                        ]
                    }
                ],
                'special_tables': {},
            }
        )

    # ORBITAL
    cat = get_cat('ORBITAL')
    if cat:
        ChecklistTemplate.objects.get_or_create(
            product_category=cat,
            checklist_type='production',
            defaults={
                'name': 'Orbital Fertigungscheckliste',
                'sections': [
                    {
                        'title': 'Allgemein',
                        'items': [
                            {'id': 'beschriftung', 'label': 'Beschriftung OK'},
                            {'id': 'tirf', 'label': 'TIRF OK'},
                            {'id': 'frap', 'label': 'FRAP OK'}
                        ]
                    },
                    {
                        'title': 'TTL Outputs',
                        'items': [
                            {'id': 'ttl_out1', 'label': 'TTL Out1 OK'},
                            {'id': 'ttl_out2', 'label': 'TTL Out2 OK'},
                            {'id': 'ttl_out3', 'label': 'TTL Out3 OK'},
                            {'id': 'ttl_out4', 'label': 'TTL Out4 OK'},
                            {'id': 'ttl_out5', 'label': 'TTL Out5 OK'},
                            {'id': 'ttl_out6', 'label': 'TTL Out6 OK'}
                        ]
                    },
                    {
                        'title': 'System',
                        'items': [
                            {'id': 'fw_update', 'label': 'FW Update OK'},
                            {'id': 'sn_aufkleber', 'label': 'SN Aufkleber OK'}
                        ]
                    }
                ],
                'special_tables': {
                    'galvo_table': {
                        'headers': ['Galvo-Offset', 'X-Galvo-Spannung V', 'Y-Galvo-Spannung V'],
                        'rows': [
                            {'offset': '2,49', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '2,00', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '1,50', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '1,00', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '0,50', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '-0,50', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '-1,00', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '-1,50', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '-2,00', 'x_voltage': '', 'y_voltage': ''},
                            {'offset': '-2,49', 'x_voltage': '', 'y_voltage': ''}
                        ]
                    }
                },
            }
        )

    # FRAP
    cat = get_cat('FRAP')
    if cat:
        ChecklistTemplate.objects.get_or_create(
            product_category=cat,
            checklist_type='production',
            defaults={
                'name': 'FRAP Fertigungscheckliste',
                'sections': [
                    {
                        'title': 'Allgemein',
                        'items': [
                            {'id': 'sn_aufkleber', 'label': 'SN Aufkleber OK'},
                            {'id': 'galvo_funktion', 'label': 'Galvo-Funktion OK'}
                        ]
                    }
                ],
                'special_tables': {},
            }
        )

    # KABEL
    cat = get_cat('KABEL')
    if cat:
        ChecklistTemplate.objects.get_or_create(
            product_category=cat,
            checklist_type='production',
            defaults={
                'name': 'Kabel Fertigungscheckliste',
                'sections': [
                    {
                        'title': 'Allgemein',
                        'items': [
                            {'id': 'funktion', 'label': 'Funktion OK'},
                            {'id': 'beschriftung', 'label': 'Beschriftung OK'}
                        ]
                    }
                ],
                'special_tables': {},
            }
        )

    # VS_LMS
    cat = get_cat('VS_LMS')
    if cat:
        ChecklistTemplate.objects.get_or_create(
            product_category=cat,
            checklist_type='production',
            defaults={
                'name': 'VS-LMS Fertigungscheckliste',
                'sections': [
                    {
                        'title': 'Allgemein',
                        'items': [
                            {'id': 'sn_aufkleber', 'label': 'SN Aufkleber OK'},
                            {'id': 'beschriftung', 'label': 'Beschriftung OK'}
                        ]
                    },
                    {
                        'title': 'Stromversorgung',
                        'items': [
                            {'id': 'test_laser_1_405', 'label': 'Test Laser 1 (405) OK?'},
                            {'id': 'test_laser_2_445', 'label': 'Test Laser 2 (445) OK?'},
                            {'id': 'test_laser_3_488', 'label': 'Test Laser 3 (488) OK?'},
                            {'id': 'test_laser_4_515', 'label': 'Test Laser 4 (515) OK?'},
                            {'id': 'test_laser_5_561', 'label': 'Test Laser 5 (561) OK?'},
                            {'id': 'test_laser_6_640', 'label': 'Test Laser 6 (640) OK?'},
                            {'id': 'test_laser_safety_12v', 'label': 'Test Laser Safety 12V OK?'},
                            {'id': 'lms_power_12v', 'label': 'LMS Power 12V'},
                            {'id': 'lms_power_15v', 'label': 'LMS Power 15V'},
                            {'id': 'test_galvo_15v', 'label': 'Test Galvo ±15V OK?'}
                        ]
                    },
                    {
                        'title': 'Test Digital Ports',
                        'items': [
                            {'id': 'test_lms_ttl1', 'label': 'Test LMS TTL1 OK?'},
                            {'id': 'test_ttl_input', 'label': 'Test TTL-Input OK?'},
                            {'id': 'test_lms_ttl2', 'label': 'Test LMS TTL2 OK?'},
                            {'id': 'test_interlock', 'label': 'Test Interlock OK?'},
                            {'id': 'test_psw0', 'label': 'Test PSw0 OK?'},
                            {'id': 'test_smb', 'label': 'Test SMB OK?'},
                            {'id': 'test_psw1', 'label': 'Test PSw1 OK?'},
                            {'id': 'test_orbital_ilas', 'label': 'Test Orbital / iLas OK?'}
                        ]
                    },
                    {
                        'title': 'Cable-Kit',
                        'items': [
                            {'id': 'laser_power_neutrik', 'label': 'Laser Power Kabel Neutrik 12p 2m'},
                            {'id': 'galvo_power_safety', 'label': 'Galvo Power / Laser Safety Kabel DIN 7p 2m'},
                            {'id': 'ttl_kabel_no1', 'label': 'TTL-Kabel mini Rund 8p 2m No1'},
                            {'id': 'ttl_kabel_no2', 'label': 'TTL-Kabel mini Rund 8p 2m No2'}
                        ]
                    }
                ],
                'special_tables': {
                    'laser_table': {
                        'headers': ['Laser nm', 'Modell', 'Serialnr.', 'Leistung mW', 'Output SDC mW', 'Output TIRF mW', 'Output FRAP mW'],
                        'rows': [
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''},
                            {'nm': '', 'modell': '', 'serial': '', 'leistung': '', 'output_sdc': '', 'output_tirf': '', 'output_frap': ''}
                        ]
                    },
                    'leoni_sn': ''
                },
            }
        )

    # ===== OUTGOING CHECKLISTS =====
    # Allgemeine Ausgangscheckliste (als Vorlage für die häufigsten Kategorien)
    outgoing_sections = [
        {
            'title': 'Allgemeine Ausgangschecks',
            'items': [
                {'id': 'sauber', 'label': 'Sauber'},
                {'id': 'funktion', 'label': 'Funktion'},
                {'id': 'vslabel', 'label': 'VSLabel'},
                {'id': 'tools', 'label': 'Tools'},
                {'id': 'manual', 'label': 'Manual'},
                {'id': 'keys', 'label': 'Keys'},
                {'id': 'interlock', 'label': 'Interlock'},
                {'id': 'datenkabel', 'label': 'Datenkabel'},
                {'id': 'interface', 'label': 'Interface'},
                {'id': 'triggerkabel', 'label': 'Triggerkabel'},
                {'id': 'dongle', 'label': 'Dongle'},
                {'id': 'stromkabel', 'label': 'Stromkabel'},
                {'id': 'netzteil', 'label': 'Netzteil'},
                {'id': 'v230', 'label': '230V'},
                {'id': 'v120', 'label': '120V'},
                {'id': 'fiber_llg', 'label': 'Fiber/LLG'},
                {'id': 'sn', 'label': 'S/N'},
                {'id': 'supportjacks', 'label': 'Support Jacks'},
                {'id': 'geraetverpackt', 'label': 'Gerät verpackt'}
            ]
        }
    ]

    # Create outgoing checklist for all VS-Hardware categories
    hw_categories = ProductCategory.objects.filter(applies_to_vs_hardware=True, is_active=True)
    for cat in hw_categories:
        ChecklistTemplate.objects.get_or_create(
            product_category=cat,
            checklist_type='outgoing',
            defaults={
                'name': f'{cat.name} Ausgangscheckliste',
                'sections': outgoing_sections,
                'special_tables': {},
            }
        )


def undo_seed(apps, schema_editor):
    ChecklistTemplate = apps.get_model('verp_settings', 'ChecklistTemplate')
    ChecklistTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('verp_settings', '0007_checklisttemplate'),
    ]

    operations = [
        migrations.RunPython(seed_checklist_templates, undo_seed),
    ]
